
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated in "Generate Kalman Filter C Code.ipynb" from https://github.com/tudelft/kalman_filter   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "ekf_calc.h"
#include <math.h>
#include <stdio.h>
#include "qr_solve/qr_solve.h"

#if (AS_N_U*AS_N_C) < 49
#error "Preallocation in ActiveSetSolver too small for EKF. Increase AS_N_U such that (AS_N_U+AS_N_V)*AS_N_U >= 49"
#endif

float ekf_use_phi;
float ekf_use_theta;
float ekf_use_psi;

float ekf_Q[N_PROC_NOISES];         // Kalman filter process noise covariance matrix (diagonal)
float ekf_R[N_MEASUREMENTS];   // Kalman filter measurement noise covariance matrix (diagonal)

// state
float ekf_X[N_STATES];
float ekf_X_new[N_STATES];

// covariance matrix (upper diagonal) P[i,j] = P_upper_diagonal[i*(i+1)/2+j] (if i>=j)
float ekf_P_upper_diagonal[N_STATES*(N_STATES+1)/2];
float ekf_P_upper_diagonal_new[N_STATES*(N_STATES+1)/2];

// gain matrix calculations
float ekf_S_full[N_MEASUREMENTS*N_MEASUREMENTS];
float ekf_S_chol[N_MEASUREMENTS*N_MEASUREMENTS];
float ekf_S_iDiag[N_MEASUREMENTS];
float ekf_HP[N_STATES*N_MEASUREMENTS];
float ekf_K[N_STATES*N_MEASUREMENTS];

// temporary variables
float tmp[318];

// pointers
float *X = ekf_X;
float *X_new = ekf_X_new;

float *P = ekf_P_upper_diagonal;
float *P_new = ekf_P_upper_diagonal_new;

float *S = ekf_S_full;
float *HP = ekf_HP;
float *K = ekf_K;

// renaming
float *Q = ekf_Q;
float *R = ekf_R;

// pointer for swapping
float *swap_ptr;

float* ekf_get_X() {
    return X;
}

float* ekf_get_P() {
    return P;
}

void ekf_set_Q(float Q[N_INPUTS]) {
    for (int i=0; i<N_PROC_NOISES; i++) {
        ekf_Q[i] = Q[i];
    }
}

void ekf_set_R(float R[N_MEASUREMENTS]) {
    for (int i=0; i<N_MEASUREMENTS; i++) {
        ekf_R[i] = R[i];
    }
}

void ekf_set_X(float X0[N_STATES]) {
    for (int i=0; i<N_STATES; i++) {
        X[i] = X0[i];
    }
}

void ekf_set_P_diag(float P_diag[N_STATES]) {
    // set P to zeros
    for (int i=0; i<N_STATES*(N_STATES+1)/2; i++) {
        P[i] = 0.;
    }
    // set diagonal
    for (int i=0; i<N_STATES; i++) {
        P[i*(i+1)/2+i] = P_diag[i];
    }
}

//void ekf_set_P(float P0[N_STATES*(N_STATES+1)/2]) {
//    for (int i=0; i<N_STATES*(N_STATES+1)/2; i++) {
//        P[i] = P0[i];
//    }
//}

void ekf_predict(float U[N_INPUTS], float dt) {
    // PREDICTION STEP X_new, P_new = ...
    tmp[0] = U[2] - X[12];
	tmp[1] = X[8]*tmp[0];
	tmp[2] = U[0] - X[10];
	tmp[3] = X[6]*tmp[2];
	tmp[4] = U[1] - X[11];
	tmp[5] = X[9]*tmp[4];
	tmp[6] = tmp[3] - tmp[5];
	tmp[7] = tmp[1] + tmp[6];
	tmp[8] = X[6]*tmp[0];
	tmp[9] = X[7]*tmp[4];
	tmp[10] = X[8]*tmp[2];
	tmp[11] = -tmp[10];
	tmp[12] = tmp[11] + tmp[9];
	tmp[13] = tmp[12] + tmp[8];
	tmp[14] = X[9]*tmp[2];
	tmp[15] = X[6]*tmp[4];
	tmp[16] = X[7]*tmp[0];
	tmp[17] = -tmp[16];
	tmp[18] = tmp[15] + tmp[17];
	tmp[19] = tmp[14] + tmp[18];
	tmp[20] = X[8]*tmp[4];
	tmp[21] = X[7]*tmp[2];
	tmp[22] = X[9]*tmp[0];
	tmp[23] = tmp[21] + tmp[22];
	tmp[24] = -tmp[20] - tmp[23];
	tmp[25] = 0.5*U[3] - 0.5*X[13];
	tmp[26] = -tmp[25];
	tmp[27] = 0.5*U[4] - 0.5*X[14];
	tmp[28] = -tmp[27];
	tmp[29] = 0.5*U[5] - 0.5*X[15];
	tmp[30] = -tmp[29];
	tmp[31] = P[6] + P[9]*dt;
	tmp[32] = P[13]*dt;
	tmp[33] = P[10] + tmp[32];
	tmp[34] = P[18]*dt;
	tmp[35] = P[15] + tmp[34];
	tmp[36] = 2*tmp[1];
	tmp[37] = 2*tmp[3] - 2*tmp[5];
	tmp[38] = tmp[36] + tmp[37];
	tmp[39] = P[24]*dt;
	tmp[40] = P[21] + tmp[39];
	tmp[41] = dt*tmp[40];
	tmp[42] = -tmp[2];
	tmp[43] = X[7]*tmp[42];
	tmp[44] = -tmp[0];
	tmp[45] = X[9]*tmp[44];
	tmp[46] = -tmp[45];
	tmp[47] = 2*tmp[20] + tmp[23] - tmp[43] + tmp[46];
	tmp[48] = P[31]*dt;
	tmp[49] = P[28] + tmp[48];
	tmp[50] = dt*tmp[49];
	tmp[51] = 2*tmp[8];
	tmp[52] = X[8]*tmp[42];
	tmp[53] = -tmp[4];
	tmp[54] = -X[7]*tmp[53] + tmp[12] + tmp[51] + tmp[52];
	tmp[55] = P[39]*dt;
	tmp[56] = P[36] + tmp[55];
	tmp[57] = dt*tmp[56];
	tmp[58] = X[7]*tmp[44];
	tmp[59] = X[6]*tmp[53] - 2*tmp[14] - tmp[18] - tmp[58];
	tmp[60] = P[48]*dt;
	tmp[61] = P[45] + tmp[60];
	tmp[62] = dt*tmp[61];
	tmp[63] = powf(X[7], 2);
	tmp[64] = powf(X[8], 2);
	tmp[65] = -tmp[64];
	tmp[66] = powf(X[6], 2);
	tmp[67] = powf(X[9], 2);
	tmp[68] = tmp[66] - tmp[67];
	tmp[69] = -tmp[63] - tmp[65] - tmp[68];
	tmp[70] = P[58]*dt;
	tmp[71] = P[55] + tmp[70];
	tmp[72] = dt*tmp[71];
	tmp[73] = 2*X[9];
	tmp[74] = X[6]*tmp[73];
	tmp[75] = 2*X[8];
	tmp[76] = X[7]*tmp[75];
	tmp[77] = tmp[74] - tmp[76];
	tmp[78] = P[69]*dt;
	tmp[79] = P[66] + tmp[78];
	tmp[80] = dt*tmp[79];
	tmp[81] = X[6]*tmp[75];
	tmp[82] = X[7]*tmp[73];
	tmp[83] = -tmp[81] - tmp[82];
	tmp[84] = P[81]*dt;
	tmp[85] = P[78] + tmp[84];
	tmp[86] = dt*tmp[85];
	tmp[87] = -X[9]*tmp[42] + tmp[14] + 2*tmp[15];
	tmp[88] = -2*tmp[16] + tmp[87];
	tmp[89] = 2*tmp[9];
	tmp[90] = X[6]*tmp[44] - tmp[11] - tmp[52] - tmp[89] - tmp[8];
	tmp[91] = X[8]*tmp[53];
	tmp[92] = tmp[20] + tmp[21] + tmp[22] - tmp[43] - tmp[45] - tmp[91];
	tmp[93] = -X[8]*tmp[44] + tmp[1] + tmp[37];
	tmp[94] = -tmp[74] - tmp[76];
	tmp[95] = -tmp[63];
	tmp[96] = -tmp[64] - tmp[68] - tmp[95];
	tmp[97] = X[6]*X[7];
	tmp[98] = 2*tmp[97];
	tmp[99] = X[9]*tmp[75];
	tmp[100] = tmp[98] - tmp[99];
	tmp[101] = -2*tmp[10] + tmp[51] + tmp[89];
	tmp[102] = tmp[17] + tmp[58] + tmp[87];
	tmp[103] = X[6]*tmp[42] - X[9]*tmp[53] - tmp[36] - tmp[6];
	tmp[104] = tmp[20] + 2*tmp[21] + tmp[22] + tmp[46] - tmp[91];
	tmp[105] = tmp[81] - tmp[82];
	tmp[106] = -tmp[98] - tmp[99];
	tmp[107] = -tmp[65] - tmp[66] - tmp[67] - tmp[95];
	tmp[108] = P[91] + P[94]*dt;
	tmp[109] = 0.5*dt;
	tmp[110] = tmp[108]*tmp[109];
	tmp[111] = P[105] + P[108]*dt;
	tmp[112] = tmp[109]*tmp[111];
	tmp[113] = P[120] + P[123]*dt;
	tmp[114] = tmp[109]*tmp[113];
	tmp[115] = P[11] + P[14]*dt;
	tmp[116] = P[19]*dt;
	tmp[117] = P[16] + tmp[116];
	tmp[118] = P[70]*dt;
	tmp[119] = P[67] + tmp[118];
	tmp[120] = dt*tmp[119];
	tmp[121] = P[82]*dt;
	tmp[122] = P[79] + tmp[121];
	tmp[123] = dt*tmp[122];
	tmp[124] = P[59]*dt;
	tmp[125] = P[56] + tmp[124];
	tmp[126] = dt*tmp[125];
	tmp[127] = P[25]*dt;
	tmp[128] = P[22] + tmp[127];
	tmp[129] = dt*tmp[128];
	tmp[130] = P[32]*dt;
	tmp[131] = P[29] + tmp[130];
	tmp[132] = dt*tmp[131];
	tmp[133] = P[40]*dt;
	tmp[134] = P[37] + tmp[133];
	tmp[135] = dt*tmp[134];
	tmp[136] = P[49]*dt;
	tmp[137] = P[46] + tmp[136];
	tmp[138] = dt*tmp[137];
	tmp[139] = P[92] + P[95]*dt;
	tmp[140] = tmp[109]*tmp[139];
	tmp[141] = P[106] + P[109]*dt;
	tmp[142] = tmp[109]*tmp[141];
	tmp[143] = P[121] + P[124]*dt;
	tmp[144] = tmp[109]*tmp[143];
	tmp[145] = P[17] + P[20]*dt;
	tmp[146] = P[71]*dt;
	tmp[147] = P[68] + tmp[146];
	tmp[148] = dt*tmp[147];
	tmp[149] = P[83]*dt;
	tmp[150] = P[80] + tmp[149];
	tmp[151] = dt*tmp[150];
	tmp[152] = P[60]*dt;
	tmp[153] = P[57] + tmp[152];
	tmp[154] = dt*tmp[153];
	tmp[155] = P[26]*dt;
	tmp[156] = P[23] + tmp[155];
	tmp[157] = dt*tmp[156];
	tmp[158] = P[33]*dt;
	tmp[159] = P[30] + tmp[158];
	tmp[160] = dt*tmp[159];
	tmp[161] = P[41]*dt;
	tmp[162] = P[38] + tmp[161];
	tmp[163] = dt*tmp[162];
	tmp[164] = P[50]*dt;
	tmp[165] = P[47] + tmp[164];
	tmp[166] = dt*tmp[165];
	tmp[167] = P[93] + P[96]*dt;
	tmp[168] = tmp[109]*tmp[167];
	tmp[169] = P[107] + P[110]*dt;
	tmp[170] = tmp[109]*tmp[169];
	tmp[171] = P[122] + P[125]*dt;
	tmp[172] = tmp[109]*tmp[171];
	tmp[173] = powf(dt, 2);
	tmp[174] = Q[1]*tmp[173];
	tmp[175] = Q[2]*tmp[173];
	tmp[176] = Q[0]*tmp[173];
	tmp[177] = dt*tmp[77];
	tmp[178] = dt*tmp[83];
	tmp[179] = dt*tmp[69];
	tmp[180] = dt*tmp[38];
	tmp[181] = dt*tmp[47];
	tmp[182] = dt*tmp[54];
	tmp[183] = dt*tmp[59];
	tmp[184] = P[81] + P[84]*tmp[180] + P[85]*tmp[181] + P[86]*tmp[182] + P[87]*tmp[183] + P[88]*tmp[179] + P[89]*tmp[177] + P[90]*tmp[178];
	tmp[185] = P[69] + P[72]*tmp[180] + P[73]*tmp[181] + P[74]*tmp[182] + P[75]*tmp[183] + P[76]*tmp[179] + P[77]*tmp[177] + P[89]*tmp[178];
	tmp[186] = P[58] + P[61]*tmp[180] + P[62]*tmp[181] + P[63]*tmp[182] + P[64]*tmp[183] + P[65]*tmp[179] + P[76]*tmp[177] + P[88]*tmp[178];
	tmp[187] = P[24] + P[27]*tmp[180] + P[34]*tmp[181] + P[42]*tmp[182] + P[51]*tmp[183] + P[61]*tmp[179] + P[72]*tmp[177] + P[84]*tmp[178];
	tmp[188] = P[48] + P[51]*tmp[180] + P[52]*tmp[181] + P[53]*tmp[182] + P[54]*tmp[183] + P[64]*tmp[179] + P[75]*tmp[177] + P[87]*tmp[178];
	tmp[189] = P[39] + P[42]*tmp[180] + P[43]*tmp[181] + P[44]*tmp[182] + P[53]*tmp[183] + P[63]*tmp[179] + P[74]*tmp[177] + P[86]*tmp[178];
	tmp[190] = P[31] + P[34]*tmp[180] + P[35]*tmp[181] + P[43]*tmp[182] + P[52]*tmp[183] + P[62]*tmp[179] + P[73]*tmp[177] + P[85]*tmp[178];
	tmp[191] = tmp[175]*tmp[83];
	tmp[192] = tmp[176]*tmp[69];
	tmp[193] = tmp[174]*tmp[77];
	tmp[194] = dt*tmp[184];
	tmp[195] = dt*tmp[186];
	tmp[196] = dt*tmp[185];
	tmp[197] = dt*tmp[188];
	tmp[198] = dt*tmp[187];
	tmp[199] = dt*tmp[190];
	tmp[200] = dt*tmp[189];
	tmp[201] = P[100]*tmp[183] + P[101]*tmp[179] + P[102]*tmp[177] + P[103]*tmp[178] + P[94] + P[97]*tmp[180] + P[98]*tmp[181] + P[99]*tmp[182];
	tmp[202] = tmp[109]*tmp[201];
	tmp[203] = P[108] + P[111]*tmp[180] + P[112]*tmp[181] + P[113]*tmp[182] + P[114]*tmp[183] + P[115]*tmp[179] + P[116]*tmp[177] + P[117]*tmp[178];
	tmp[204] = tmp[109]*tmp[203];
	tmp[205] = P[123] + P[126]*tmp[180] + P[127]*tmp[181] + P[128]*tmp[182] + P[129]*tmp[183] + P[130]*tmp[179] + P[131]*tmp[177] + P[132]*tmp[178];
	tmp[206] = tmp[109]*tmp[205];
	tmp[207] = dt*tmp[94];
	tmp[208] = dt*tmp[100];
	tmp[209] = dt*tmp[96];
	tmp[210] = dt*tmp[88];
	tmp[211] = dt*tmp[93];
	tmp[212] = dt*tmp[90];
	tmp[213] = dt*tmp[92];
	tmp[214] = P[82] + P[84]*tmp[210] + P[85]*tmp[212] + P[86]*tmp[213] + P[87]*tmp[211] + P[88]*tmp[207] + P[89]*tmp[209] + P[90]*tmp[208];
	tmp[215] = P[59] + P[61]*tmp[210] + P[62]*tmp[212] + P[63]*tmp[213] + P[64]*tmp[211] + P[65]*tmp[207] + P[76]*tmp[209] + P[88]*tmp[208];
	tmp[216] = P[70] + P[72]*tmp[210] + P[73]*tmp[212] + P[74]*tmp[213] + P[75]*tmp[211] + P[76]*tmp[207] + P[77]*tmp[209] + P[89]*tmp[208];
	tmp[217] = P[49] + P[51]*tmp[210] + P[52]*tmp[212] + P[53]*tmp[213] + P[54]*tmp[211] + P[64]*tmp[207] + P[75]*tmp[209] + P[87]*tmp[208];
	tmp[218] = P[25] + P[27]*tmp[210] + P[34]*tmp[212] + P[42]*tmp[213] + P[51]*tmp[211] + P[61]*tmp[207] + P[72]*tmp[209] + P[84]*tmp[208];
	tmp[219] = P[32] + P[34]*tmp[210] + P[35]*tmp[212] + P[43]*tmp[213] + P[52]*tmp[211] + P[62]*tmp[207] + P[73]*tmp[209] + P[85]*tmp[208];
	tmp[220] = P[40] + P[42]*tmp[210] + P[43]*tmp[212] + P[44]*tmp[213] + P[53]*tmp[211] + P[63]*tmp[207] + P[74]*tmp[209] + P[86]*tmp[208];
	tmp[221] = dt*tmp[106];
	tmp[222] = dt*tmp[105];
	tmp[223] = dt*tmp[107];
	tmp[224] = dt*tmp[218];
	tmp[225] = dt*tmp[220];
	tmp[226] = dt*tmp[219];
	tmp[227] = dt*tmp[217];
	tmp[228] = P[100]*tmp[211] + P[101]*tmp[207] + P[102]*tmp[209] + P[103]*tmp[208] + P[95] + P[97]*tmp[210] + P[98]*tmp[212] + P[99]*tmp[213];
	tmp[229] = tmp[109]*tmp[228];
	tmp[230] = P[109] + P[111]*tmp[210] + P[112]*tmp[212] + P[113]*tmp[213] + P[114]*tmp[211] + P[115]*tmp[207] + P[116]*tmp[209] + P[117]*tmp[208];
	tmp[231] = tmp[109]*tmp[230];
	tmp[232] = P[124] + P[126]*tmp[210] + P[127]*tmp[212] + P[128]*tmp[213] + P[129]*tmp[211] + P[130]*tmp[207] + P[131]*tmp[209] + P[132]*tmp[208];
	tmp[233] = tmp[109]*tmp[232];
	tmp[234] = dt*tmp[101];
	tmp[235] = dt*tmp[102];
	tmp[236] = dt*tmp[103];
	tmp[237] = dt*tmp[104];
	tmp[238] = P[71] + P[72]*tmp[234] + P[73]*tmp[235] + P[74]*tmp[236] + P[75]*tmp[237] + P[76]*tmp[222] + P[77]*tmp[221] + P[89]*tmp[223];
	tmp[239] = P[60] + P[61]*tmp[234] + P[62]*tmp[235] + P[63]*tmp[236] + P[64]*tmp[237] + P[65]*tmp[222] + P[76]*tmp[221] + P[88]*tmp[223];
	tmp[240] = P[83] + P[84]*tmp[234] + P[85]*tmp[235] + P[86]*tmp[236] + P[87]*tmp[237] + P[88]*tmp[222] + P[89]*tmp[221] + P[90]*tmp[223];
	tmp[241] = P[26] + P[27]*tmp[234] + P[34]*tmp[235] + P[42]*tmp[236] + P[51]*tmp[237] + P[61]*tmp[222] + P[72]*tmp[221] + P[84]*tmp[223];
	tmp[242] = P[41] + P[42]*tmp[234] + P[43]*tmp[235] + P[44]*tmp[236] + P[53]*tmp[237] + P[63]*tmp[222] + P[74]*tmp[221] + P[86]*tmp[223];
	tmp[243] = P[33] + P[34]*tmp[234] + P[35]*tmp[235] + P[43]*tmp[236] + P[52]*tmp[237] + P[62]*tmp[222] + P[73]*tmp[221] + P[85]*tmp[223];
	tmp[244] = P[50] + P[51]*tmp[234] + P[52]*tmp[235] + P[53]*tmp[236] + P[54]*tmp[237] + P[64]*tmp[222] + P[75]*tmp[221] + P[87]*tmp[223];
	tmp[245] = dt*tmp[243];
	tmp[246] = dt*tmp[242];
	tmp[247] = dt*tmp[244];
	tmp[248] = P[100]*tmp[237] + P[101]*tmp[222] + P[102]*tmp[221] + P[103]*tmp[223] + P[96] + P[97]*tmp[234] + P[98]*tmp[235] + P[99]*tmp[236];
	tmp[249] = tmp[109]*tmp[248];
	tmp[250] = P[110] + P[111]*tmp[234] + P[112]*tmp[235] + P[113]*tmp[236] + P[114]*tmp[237] + P[115]*tmp[222] + P[116]*tmp[221] + P[117]*tmp[223];
	tmp[251] = tmp[109]*tmp[250];
	tmp[252] = P[125] + P[126]*tmp[234] + P[127]*tmp[235] + P[128]*tmp[236] + P[129]*tmp[237] + P[130]*tmp[222] + P[131]*tmp[221] + P[132]*tmp[223];
	tmp[253] = tmp[109]*tmp[252];
	tmp[254] = dt*tmp[241];
	tmp[255] = 0.01*tmp[173];
	tmp[256] = X[8]*tmp[109];
	tmp[257] = X[9]*tmp[109];
	tmp[258] = X[7]*tmp[109];
	tmp[259] = dt*tmp[26];
	tmp[260] = dt*tmp[28];
	tmp[261] = dt*tmp[30];
	tmp[262] = P[52]*tmp[261];
	tmp[263] = P[112]*tmp[256] + P[127]*tmp[257] + P[34] + P[35]*tmp[259] + P[43]*tmp[260] + P[98]*tmp[258] + tmp[262];
	tmp[264] = P[43]*tmp[259];
	tmp[265] = P[113]*tmp[256] + P[128]*tmp[257] + P[42] + P[44]*tmp[260] + P[53]*tmp[261] + P[99]*tmp[258] + tmp[264];
	tmp[266] = P[53]*tmp[260];
	tmp[267] = P[100]*tmp[258] + P[114]*tmp[256] + P[129]*tmp[257] + P[51] + P[52]*tmp[259] + P[54]*tmp[261] + tmp[266];
	tmp[268] = 0.25*tmp[173];
	tmp[269] = Q[3]*tmp[268];
	tmp[270] = Q[4]*tmp[268];
	tmp[271] = Q[5]*tmp[268];
	tmp[272] = P[118]*tmp[256];
	tmp[273] = P[133]*tmp[257];
	tmp[274] = P[100]*tmp[261] + P[104]*tmp[258] + P[97] + P[98]*tmp[259] + P[99]*tmp[260] + tmp[272] + tmp[273];
	tmp[275] = P[118]*tmp[258];
	tmp[276] = P[134]*tmp[257];
	tmp[277] = P[111] + P[112]*tmp[259] + P[113]*tmp[260] + P[114]*tmp[261] + P[119]*tmp[256] + tmp[275] + tmp[276];
	tmp[278] = P[133]*tmp[258];
	tmp[279] = P[134]*tmp[256];
	tmp[280] = P[126] + P[127]*tmp[259] + P[128]*tmp[260] + P[129]*tmp[261] + P[135]*tmp[257] + tmp[278] + tmp[279];
	tmp[281] = P[111]*tmp[256] + P[126]*tmp[257] + P[27] + P[34]*tmp[259] + P[42]*tmp[260] + P[51]*tmp[261] + P[97]*tmp[258];
	tmp[282] = dt*tmp[25];
	tmp[283] = dt*tmp[29];
	tmp[284] = X[6]*tmp[109];
	tmp[285] = X[8]*X[9];
	tmp[286] = dt*tmp[27];
	tmp[287] = X[7]*X[9];
	tmp[288] = X[8]*tmp[270];
	tmp[289] = X[7]*X[8];
	tmp[290] = X[6]*X[9];
	tmp[291] = P[42]*tmp[283];
	tmp[292] = P[111]*tmp[257] - P[126]*tmp[256] + P[27]*tmp[282] + P[34] + P[51]*tmp[260] - P[97]*tmp[284] + tmp[291];
	tmp[293] = P[113]*tmp[257] - P[128]*tmp[256] + P[42]*tmp[282] + P[43] + P[44]*tmp[283] - P[99]*tmp[284] + tmp[266];
	tmp[294] = P[51]*tmp[282];
	tmp[295] = -P[100]*tmp[284] + P[114]*tmp[257] - P[129]*tmp[256] + P[52] + P[53]*tmp[283] + P[54]*tmp[260] + tmp[294];
	tmp[296] = -P[118]*tmp[284];
	tmp[297] = P[111]*tmp[282] + P[112] + P[113]*tmp[283] + P[114]*tmp[260] + P[119]*tmp[257] - tmp[279] + tmp[296];
	tmp[298] = P[118]*tmp[257];
	tmp[299] = P[133]*tmp[256];
	tmp[300] = P[100]*tmp[260] - P[104]*tmp[284] + P[97]*tmp[282] + P[98] + P[99]*tmp[283] + tmp[298] - tmp[299];
	tmp[301] = -P[133]*tmp[284];
	tmp[302] = P[126]*tmp[282] + P[127] + P[128]*tmp[283] + P[129]*tmp[260] - P[135]*tmp[256] + tmp[276] + tmp[301];
	tmp[303] = P[112]*tmp[257] - P[127]*tmp[256] + P[34]*tmp[282] + P[35] + P[43]*tmp[283] + P[52]*tmp[260] - P[98]*tmp[284];
	tmp[304] = X[6]*X[8];
	tmp[305] = -P[100]*tmp[257] - P[114]*tmp[284] + P[129]*tmp[258] + P[51]*tmp[286] + P[53] + P[54]*tmp[282] + tmp[262];
	tmp[306] = -P[111]*tmp[284] + P[126]*tmp[258] + P[27]*tmp[286] + P[34]*tmp[261] + P[42] - P[97]*tmp[257] + tmp[294];
	tmp[307] = P[34]*tmp[286];
	tmp[308] = -P[112]*tmp[284] + P[127]*tmp[258] + P[35]*tmp[261] + P[43] + P[52]*tmp[282] - P[98]*tmp[257] + tmp[307];
	tmp[309] = -P[134]*tmp[284];
	tmp[310] = P[126]*tmp[286] + P[127]*tmp[261] + P[128] + P[129]*tmp[282] + P[135]*tmp[258] - tmp[273] + tmp[309];
	tmp[311] = P[134]*tmp[258];
	tmp[312] = P[111]*tmp[286] + P[112]*tmp[261] + P[113] + P[114]*tmp[282] - P[119]*tmp[284] - tmp[298] + tmp[311];
	tmp[313] = P[100]*tmp[282] - P[104]*tmp[257] + P[97]*tmp[286] + P[98]*tmp[261] + P[99] + tmp[278] + tmp[296];
	tmp[314] = -P[113]*tmp[284] + P[128]*tmp[258] + P[42]*tmp[286] + P[43]*tmp[261] + P[44] + P[53]*tmp[282] - P[99]*tmp[257];
	tmp[315] = P[126]*tmp[283] + P[127]*tmp[286] + P[128]*tmp[259] + P[129] - P[135]*tmp[284] + tmp[299] - tmp[311];
	tmp[316] = P[111]*tmp[283] + P[112]*tmp[286] + P[113]*tmp[259] + P[114] - P[119]*tmp[258] + tmp[272] + tmp[309];
	tmp[317] = P[100] + P[104]*tmp[256] + P[97]*tmp[283] + P[98]*tmp[286] + P[99]*tmp[259] - tmp[275] + tmp[301];
	X_new[0] = X[0] + X[3]*dt;
	X_new[1] = X[1] + X[4]*dt;
	X_new[2] = X[2] + X[5]*dt;
	X_new[3] = X[3] + dt*(X[6]*tmp[7] - X[7]*tmp[24] + X[8]*tmp[13] - X[9]*tmp[19]);
	X_new[4] = X[4] + dt*(X[6]*tmp[19] - X[7]*tmp[13] - X[8]*tmp[24] + X[9]*tmp[7]);
	X_new[5] = X[5] + dt*(X[6]*tmp[13] + X[7]*tmp[19] - X[8]*tmp[7] - X[9]*tmp[24] + 9.8100000000000005);
	X_new[6] = X[6] + dt*(X[7]*tmp[26] + X[8]*tmp[28] + X[9]*tmp[30]);
	X_new[7] = X[7] + dt*(X[6]*tmp[25] + X[8]*tmp[29] + X[9]*tmp[28]);
	X_new[8] = X[8] + dt*(X[6]*tmp[27] + X[7]*tmp[30] + X[9]*tmp[25]);
	X_new[9] = X[9] + dt*(X[6]*tmp[29] + X[7]*tmp[27] + X[8]*tmp[26]);
	X_new[10] = X[10];
	X_new[11] = X[11];
	X_new[12] = X[12];
	X_new[13] = X[13];
	X_new[14] = X[14];
	X_new[15] = X[15];
	P_new[0] = P[0] + P[6]*dt + dt*tmp[31];
	P_new[1] = P[1] + P[7]*dt + dt*tmp[33];
	P_new[3] = P[3] + P[8]*dt + dt*tmp[35];
	P_new[6] = tmp[31] + tmp[38]*tmp[41] + tmp[47]*tmp[50] + tmp[54]*tmp[57] + tmp[59]*tmp[62] + tmp[69]*tmp[72] + tmp[77]*tmp[80] + tmp[83]*tmp[86];
	P_new[10] = tmp[100]*tmp[86] + tmp[33] + tmp[41]*tmp[88] + tmp[50]*tmp[90] + tmp[57]*tmp[92] + tmp[62]*tmp[93] + tmp[72]*tmp[94] + tmp[80]*tmp[96];
	P_new[15] = tmp[101]*tmp[41] + tmp[102]*tmp[50] + tmp[103]*tmp[57] + tmp[104]*tmp[62] + tmp[105]*tmp[72] + tmp[106]*tmp[80] + tmp[107]*tmp[86] + tmp[35];
	P_new[21] = X[7]*tmp[110] + X[8]*tmp[112] + X[9]*tmp[114] + tmp[26]*tmp[50] + tmp[28]*tmp[57] + tmp[30]*tmp[62] + tmp[40];
	P_new[28] = -X[6]*tmp[110] - X[8]*tmp[114] + X[9]*tmp[112] + tmp[25]*tmp[41] + tmp[28]*tmp[62] + tmp[29]*tmp[57] + tmp[49];
	P_new[36] = -X[6]*tmp[112] + X[7]*tmp[114] - X[9]*tmp[110] + tmp[25]*tmp[62] + tmp[27]*tmp[41] + tmp[30]*tmp[50] + tmp[56];
	P_new[45] = -X[6]*tmp[114] - X[7]*tmp[112] + X[8]*tmp[110] + tmp[26]*tmp[57] + tmp[27]*tmp[50] + tmp[29]*tmp[41] + tmp[61];
	P_new[55] = tmp[71];
	P_new[66] = tmp[79];
	P_new[78] = tmp[85];
	P_new[91] = tmp[108];
	P_new[105] = tmp[111];
	P_new[120] = tmp[113];
	P_new[2] = P[11]*dt + P[2] + dt*tmp[115];
	P_new[4] = P[12]*dt + P[4] + dt*tmp[117];
	P_new[7] = P[7] + tmp[120]*tmp[77] + tmp[123]*tmp[83] + tmp[126]*tmp[69] + tmp[129]*tmp[38] + tmp[132]*tmp[47] + tmp[135]*tmp[54] + tmp[138]*tmp[59] + tmp[32];
	P_new[11] = tmp[100]*tmp[123] + tmp[115] + tmp[120]*tmp[96] + tmp[126]*tmp[94] + tmp[129]*tmp[88] + tmp[132]*tmp[90] + tmp[135]*tmp[92] + tmp[138]*tmp[93];
	P_new[16] = tmp[101]*tmp[129] + tmp[102]*tmp[132] + tmp[103]*tmp[135] + tmp[104]*tmp[138] + tmp[105]*tmp[126] + tmp[106]*tmp[120] + tmp[107]*tmp[123] + tmp[117];
	P_new[22] = X[7]*tmp[140] + X[8]*tmp[142] + X[9]*tmp[144] + tmp[128] + tmp[132]*tmp[26] + tmp[135]*tmp[28] + tmp[138]*tmp[30];
	P_new[29] = -X[6]*tmp[140] - X[8]*tmp[144] + X[9]*tmp[142] + tmp[129]*tmp[25] + tmp[131] + tmp[135]*tmp[29] + tmp[138]*tmp[28];
	P_new[37] = -X[6]*tmp[142] + X[7]*tmp[144] - X[9]*tmp[140] + tmp[129]*tmp[27] + tmp[132]*tmp[30] + tmp[134] + tmp[138]*tmp[25];
	P_new[46] = -X[6]*tmp[144] - X[7]*tmp[142] + X[8]*tmp[140] + tmp[129]*tmp[29] + tmp[132]*tmp[27] + tmp[135]*tmp[26] + tmp[137];
	P_new[56] = tmp[125];
	P_new[67] = tmp[119];
	P_new[79] = tmp[122];
	P_new[92] = tmp[139];
	P_new[106] = tmp[141];
	P_new[121] = tmp[143];
	P_new[5] = P[17]*dt + P[5] + dt*tmp[145];
	P_new[8] = P[8] + tmp[148]*tmp[77] + tmp[151]*tmp[83] + tmp[154]*tmp[69] + tmp[157]*tmp[38] + tmp[160]*tmp[47] + tmp[163]*tmp[54] + tmp[166]*tmp[59] + tmp[34];
	P_new[12] = P[12] + tmp[100]*tmp[151] + tmp[116] + tmp[148]*tmp[96] + tmp[154]*tmp[94] + tmp[157]*tmp[88] + tmp[160]*tmp[90] + tmp[163]*tmp[92] + tmp[166]*tmp[93];
	P_new[17] = tmp[101]*tmp[157] + tmp[102]*tmp[160] + tmp[103]*tmp[163] + tmp[104]*tmp[166] + tmp[105]*tmp[154] + tmp[106]*tmp[148] + tmp[107]*tmp[151] + tmp[145];
	P_new[23] = X[7]*tmp[168] + X[8]*tmp[170] + X[9]*tmp[172] + tmp[156] + tmp[160]*tmp[26] + tmp[163]*tmp[28] + tmp[166]*tmp[30];
	P_new[30] = -X[6]*tmp[168] - X[8]*tmp[172] + X[9]*tmp[170] + tmp[157]*tmp[25] + tmp[159] + tmp[163]*tmp[29] + tmp[166]*tmp[28];
	P_new[38] = -X[6]*tmp[170] + X[7]*tmp[172] - X[9]*tmp[168] + tmp[157]*tmp[27] + tmp[160]*tmp[30] + tmp[162] + tmp[166]*tmp[25];
	P_new[47] = -X[6]*tmp[172] - X[7]*tmp[170] + X[8]*tmp[168] + tmp[157]*tmp[29] + tmp[160]*tmp[27] + tmp[163]*tmp[26] + tmp[165];
	P_new[57] = tmp[153];
	P_new[68] = tmp[147];
	P_new[80] = tmp[150];
	P_new[93] = tmp[167];
	P_new[107] = tmp[169];
	P_new[122] = tmp[171];
	P_new[9] = P[9] + tmp[174]*powf(tmp[77], 2) + tmp[175]*powf(tmp[83], 2) + tmp[176]*powf(tmp[69], 2) + tmp[177]*tmp[185] + tmp[178]*tmp[184] + tmp[179]*tmp[186] + tmp[180]*tmp[187] + tmp[181]*tmp[190] + tmp[182]*tmp[189] + tmp[183]*tmp[188] + tmp[38]*tmp[39] + tmp[47]*tmp[48] + tmp[54]*tmp[55] + tmp[59]*tmp[60] + tmp[69]*tmp[70] + tmp[77]*tmp[78] + tmp[83]*tmp[84];
	P_new[13] = P[13] + tmp[100]*tmp[191] + tmp[100]*tmp[194] + tmp[118]*tmp[77] + tmp[121]*tmp[83] + tmp[124]*tmp[69] + tmp[127]*tmp[38] + tmp[130]*tmp[47] + tmp[133]*tmp[54] + tmp[136]*tmp[59] + tmp[192]*tmp[94] + tmp[193]*tmp[96] + tmp[195]*tmp[94] + tmp[196]*tmp[96] + tmp[197]*tmp[93] + tmp[198]*tmp[88] + tmp[199]*tmp[90] + tmp[200]*tmp[92];
	P_new[18] = P[18] + tmp[101]*tmp[198] + tmp[102]*tmp[199] + tmp[103]*tmp[200] + tmp[104]*tmp[197] + tmp[105]*tmp[192] + tmp[105]*tmp[195] + tmp[106]*tmp[193] + tmp[106]*tmp[196] + tmp[107]*tmp[191] + tmp[107]*tmp[194] + tmp[146]*tmp[77] + tmp[149]*tmp[83] + tmp[152]*tmp[69] + tmp[155]*tmp[38] + tmp[158]*tmp[47] + tmp[161]*tmp[54] + tmp[164]*tmp[59];
	P_new[24] = X[7]*tmp[202] + X[8]*tmp[204] + X[9]*tmp[206] + tmp[187] + tmp[197]*tmp[30] + tmp[199]*tmp[26] + tmp[200]*tmp[28];
	P_new[31] = -X[6]*tmp[202] - X[8]*tmp[206] + X[9]*tmp[204] + tmp[190] + tmp[197]*tmp[28] + tmp[198]*tmp[25] + tmp[200]*tmp[29];
	P_new[39] = -X[6]*tmp[204] + X[7]*tmp[206] - X[9]*tmp[202] + tmp[189] + tmp[197]*tmp[25] + tmp[198]*tmp[27] + tmp[199]*tmp[30];
	P_new[48] = -X[6]*tmp[206] - X[7]*tmp[204] + X[8]*tmp[202] + tmp[188] + tmp[198]*tmp[29] + tmp[199]*tmp[27] + tmp[200]*tmp[26];
	P_new[58] = tmp[186];
	P_new[69] = tmp[185];
	P_new[81] = tmp[184];
	P_new[94] = tmp[201];
	P_new[108] = tmp[203];
	P_new[123] = tmp[205];
	P_new[14] = P[14] + powf(tmp[100], 2)*tmp[175] + tmp[100]*tmp[121] + tmp[118]*tmp[96] + tmp[124]*tmp[94] + tmp[127]*tmp[88] + tmp[130]*tmp[90] + tmp[133]*tmp[92] + tmp[136]*tmp[93] + tmp[174]*powf(tmp[96], 2) + tmp[176]*powf(tmp[94], 2) + tmp[207]*tmp[215] + tmp[208]*tmp[214] + tmp[209]*tmp[216] + tmp[210]*tmp[218] + tmp[211]*tmp[217] + tmp[212]*tmp[219] + tmp[213]*tmp[220];
	P_new[19] = P[19] + tmp[100]*tmp[107]*tmp[175] + tmp[100]*tmp[149] + tmp[101]*tmp[224] + tmp[102]*tmp[226] + tmp[103]*tmp[225] + tmp[104]*tmp[227] + tmp[105]*tmp[176]*tmp[94] + tmp[106]*tmp[174]*tmp[96] + tmp[146]*tmp[96] + tmp[152]*tmp[94] + tmp[155]*tmp[88] + tmp[158]*tmp[90] + tmp[161]*tmp[92] + tmp[164]*tmp[93] + tmp[214]*tmp[223] + tmp[215]*tmp[222] + tmp[216]*tmp[221];
	P_new[25] = X[7]*tmp[229] + X[8]*tmp[231] + X[9]*tmp[233] + tmp[218] + tmp[225]*tmp[28] + tmp[226]*tmp[26] + tmp[227]*tmp[30];
	P_new[32] = -X[6]*tmp[229] - X[8]*tmp[233] + X[9]*tmp[231] + tmp[219] + tmp[224]*tmp[25] + tmp[225]*tmp[29] + tmp[227]*tmp[28];
	P_new[40] = -X[6]*tmp[231] + X[7]*tmp[233] - X[9]*tmp[229] + tmp[220] + tmp[224]*tmp[27] + tmp[226]*tmp[30] + tmp[227]*tmp[25];
	P_new[49] = -X[6]*tmp[233] - X[7]*tmp[231] + X[8]*tmp[229] + tmp[217] + tmp[224]*tmp[29] + tmp[225]*tmp[26] + tmp[226]*tmp[27];
	P_new[59] = tmp[215];
	P_new[70] = tmp[216];
	P_new[82] = tmp[214];
	P_new[95] = tmp[228];
	P_new[109] = tmp[230];
	P_new[124] = tmp[232];
	P_new[20] = P[20] + tmp[101]*tmp[155] + tmp[102]*tmp[158] + tmp[103]*tmp[161] + tmp[104]*tmp[164] + powf(tmp[105], 2)*tmp[176] + tmp[105]*tmp[152] + powf(tmp[106], 2)*tmp[174] + tmp[106]*tmp[146] + powf(tmp[107], 2)*tmp[175] + tmp[107]*tmp[149] + tmp[221]*tmp[238] + tmp[222]*tmp[239] + tmp[223]*tmp[240] + tmp[234]*tmp[241] + tmp[235]*tmp[243] + tmp[236]*tmp[242] + tmp[237]*tmp[244];
	P_new[26] = X[7]*tmp[249] + X[8]*tmp[251] + X[9]*tmp[253] + tmp[241] + tmp[245]*tmp[26] + tmp[246]*tmp[28] + tmp[247]*tmp[30];
	P_new[33] = -X[6]*tmp[249] - X[8]*tmp[253] + X[9]*tmp[251] + tmp[243] + tmp[246]*tmp[29] + tmp[247]*tmp[28] + tmp[254]*tmp[25];
	P_new[41] = -X[6]*tmp[251] + X[7]*tmp[253] - X[9]*tmp[249] + tmp[242] + tmp[245]*tmp[30] + tmp[247]*tmp[25] + tmp[254]*tmp[27];
	P_new[50] = -X[6]*tmp[253] - X[7]*tmp[251] + X[8]*tmp[249] + tmp[244] + tmp[245]*tmp[27] + tmp[246]*tmp[26] + tmp[254]*tmp[29];
	P_new[60] = tmp[239];
	P_new[71] = tmp[238];
	P_new[83] = tmp[240];
	P_new[96] = tmp[248];
	P_new[110] = tmp[250];
	P_new[125] = tmp[252];
	P_new[27] = tmp[255] + tmp[256]*tmp[277] + tmp[257]*tmp[280] + tmp[258]*tmp[274] + tmp[259]*tmp[263] + tmp[260]*tmp[265] + tmp[261]*tmp[267] + tmp[269]*tmp[63] + tmp[270]*tmp[64] + tmp[271]*tmp[67] + tmp[281];
	P_new[34] = -tmp[256]*tmp[280] + tmp[257]*tmp[277] + tmp[260]*tmp[267] + tmp[263] + tmp[265]*tmp[283] - tmp[269]*tmp[97] + tmp[270]*tmp[285] - tmp[271]*tmp[285] - tmp[274]*tmp[284] + tmp[281]*tmp[282];
	P_new[42] = -X[6]*tmp[288] - tmp[257]*tmp[274] + tmp[258]*tmp[280] + tmp[261]*tmp[263] + tmp[265] + tmp[267]*tmp[282] - tmp[269]*tmp[287] + tmp[271]*tmp[287] - tmp[277]*tmp[284] + tmp[281]*tmp[286];
	P_new[51] = -X[7]*tmp[288] + tmp[256]*tmp[274] - tmp[258]*tmp[277] + tmp[259]*tmp[265] + tmp[263]*tmp[286] + tmp[267] + tmp[269]*tmp[289] - tmp[271]*tmp[290] - tmp[280]*tmp[284] + tmp[281]*tmp[283];
	P_new[61] = P[101]*tmp[258] + P[115]*tmp[256] + P[130]*tmp[257] + P[61] + P[62]*tmp[259] + P[63]*tmp[260] + P[64]*tmp[261];
	P_new[72] = P[102]*tmp[258] + P[116]*tmp[256] + P[131]*tmp[257] + P[72] + P[73]*tmp[259] + P[74]*tmp[260] + P[75]*tmp[261];
	P_new[84] = P[103]*tmp[258] + P[117]*tmp[256] + P[132]*tmp[257] + P[84] + P[85]*tmp[259] + P[86]*tmp[260] + P[87]*tmp[261];
	P_new[97] = tmp[274];
	P_new[111] = tmp[277];
	P_new[126] = tmp[280];
	P_new[35] = tmp[255] - tmp[256]*tmp[302] + tmp[257]*tmp[297] + tmp[260]*tmp[295] + tmp[269]*tmp[66] + tmp[270]*tmp[67] + tmp[271]*tmp[64] + tmp[282]*tmp[292] + tmp[283]*tmp[293] - tmp[284]*tmp[300] + tmp[303];
	P_new[43] = -tmp[257]*tmp[300] + tmp[258]*tmp[302] + tmp[261]*tmp[303] + tmp[269]*tmp[290] - tmp[270]*tmp[290] - tmp[271]*tmp[289] + tmp[282]*tmp[295] - tmp[284]*tmp[297] + tmp[286]*tmp[292] + tmp[293];
	P_new[52] = tmp[256]*tmp[300] - tmp[258]*tmp[297] + tmp[259]*tmp[293] - tmp[269]*tmp[304] - tmp[270]*tmp[287] + tmp[271]*tmp[304] + tmp[283]*tmp[292] - tmp[284]*tmp[302] + tmp[286]*tmp[303] + tmp[295];
	P_new[62] = -P[101]*tmp[284] + P[115]*tmp[257] - P[130]*tmp[256] + P[61]*tmp[282] + P[62] + P[63]*tmp[283] + P[64]*tmp[260];
	P_new[73] = -P[102]*tmp[284] + P[116]*tmp[257] - P[131]*tmp[256] + P[72]*tmp[282] + P[73] + P[74]*tmp[283] + P[75]*tmp[260];
	P_new[85] = -P[103]*tmp[284] + P[117]*tmp[257] - P[132]*tmp[256] + P[84]*tmp[282] + P[85] + P[86]*tmp[283] + P[87]*tmp[260];
	P_new[98] = tmp[300];
	P_new[112] = tmp[297];
	P_new[127] = tmp[302];
	P_new[44] = tmp[255] - tmp[257]*tmp[313] + tmp[258]*tmp[310] + tmp[261]*tmp[308] + tmp[269]*tmp[67] + tmp[270]*tmp[66] + tmp[271]*tmp[63] + tmp[282]*tmp[305] - tmp[284]*tmp[312] + tmp[286]*tmp[306] + tmp[314];
	P_new[53] = tmp[256]*tmp[313] - tmp[258]*tmp[312] + tmp[259]*tmp[314] - tmp[269]*tmp[285] + tmp[270]*tmp[97] - tmp[271]*tmp[97] + tmp[283]*tmp[306] - tmp[284]*tmp[310] + tmp[286]*tmp[308] + tmp[305];
	P_new[63] = -P[101]*tmp[257] - P[115]*tmp[284] + P[130]*tmp[258] + P[61]*tmp[286] + P[62]*tmp[261] + P[63] + P[64]*tmp[282];
	P_new[74] = -P[102]*tmp[257] - P[116]*tmp[284] + P[131]*tmp[258] + P[72]*tmp[286] + P[73]*tmp[261] + P[74] + P[75]*tmp[282];
	P_new[86] = -P[103]*tmp[257] - P[117]*tmp[284] + P[132]*tmp[258] + P[84]*tmp[286] + P[85]*tmp[261] + P[86] + P[87]*tmp[282];
	P_new[99] = tmp[313];
	P_new[113] = tmp[312];
	P_new[128] = tmp[310];
	P_new[54] = P[100]*tmp[256] - P[114]*tmp[258] - P[129]*tmp[284] + P[51]*tmp[283] + P[52]*tmp[286] + P[53]*tmp[259] + P[54] + tmp[255] + tmp[256]*tmp[317] - tmp[258]*tmp[316] + tmp[259]*(-P[113]*tmp[258] - P[128]*tmp[284] + P[43]*tmp[286] + P[44]*tmp[259] + P[53] + P[99]*tmp[256] + tmp[291]) + tmp[269]*tmp[64] + tmp[270]*tmp[63] + tmp[271]*tmp[66] + tmp[283]*(-P[111]*tmp[258] - P[126]*tmp[284] + P[27]*tmp[283] + P[42]*tmp[259] + P[51] + P[97]*tmp[256] + tmp[307]) - tmp[284]*tmp[315] + tmp[286]*(-P[112]*tmp[258] - P[127]*tmp[284] + P[34]*tmp[283] + P[35]*tmp[286] + P[52] + P[98]*tmp[256] + tmp[264]);
	P_new[64] = P[101]*tmp[256] - P[115]*tmp[258] - P[130]*tmp[284] + P[61]*tmp[283] + P[62]*tmp[286] + P[63]*tmp[259] + P[64];
	P_new[75] = P[102]*tmp[256] - P[116]*tmp[258] - P[131]*tmp[284] + P[72]*tmp[283] + P[73]*tmp[286] + P[74]*tmp[259] + P[75];
	P_new[87] = P[103]*tmp[256] - P[117]*tmp[258] - P[132]*tmp[284] + P[84]*tmp[283] + P[85]*tmp[286] + P[86]*tmp[259] + P[87];
	P_new[100] = tmp[317];
	P_new[114] = tmp[316];
	P_new[129] = tmp[315];
	P_new[65] = P[65] + Q[6]*tmp[173];
	P_new[76] = P[76];
	P_new[88] = P[88];
	P_new[101] = P[101];
	P_new[115] = P[115];
	P_new[130] = P[130];
	P_new[77] = P[77] + Q[7]*tmp[173];
	P_new[89] = P[89];
	P_new[102] = P[102];
	P_new[116] = P[116];
	P_new[131] = P[131];
	P_new[90] = P[90] + Q[8]*tmp[173];
	P_new[103] = P[103];
	P_new[117] = P[117];
	P_new[132] = P[132];
	P_new[104] = P[104] + Q[9]*tmp[173];
	P_new[118] = P[118];
	P_new[133] = P[133];
	P_new[119] = P[119] + Q[10]*tmp[173];
	P_new[134] = P[134];
	P_new[135] = P[135] + Q[11]*tmp[173];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

// columns major. upper factor
void chol_ekf(float *U, float *A, float *iDiag, int n)
{
    // rosetta code
    //printf("begin S %d\n", n);
    //for (int i = 0; i < n; i++) {
    //    for (int j = 0; j < n; j++) {
    //        printf("%f, ", A[i+j*n]);
    //    }
    //    printf("\n");
    //}

    for (int i = 0; i < n; i++) {
        for (int j = 0; j < (i+1); j++) {
            float s = 0;
            for (int k = 0; k < j; k++) {
                s += U[i * n + k] * U[j * n + k];
            }
            if (i == j) {
                //printf("%f - %f\n", A[i * n + i], s);
                U[i * n + j] = sqrt(A[i * n + i] - s);
                iDiag[j] = 1.f / U[i * n + j];
            } else {
                U[i * n + j] = iDiag[j] * (A[i * n + j] - s);
            }
        }
    }
}

// column major, upper factor
void chol_solve_ekf(float *U, float* iDiag, int n, float *b, float *x)
{
    // Antoine Drouin, 2007, modified
	int j,k;
	float t;

    for(j = 0 ; j < n ; j++) { // solve Uty=b
        t = b[j];
        for(k = j - 1 ; k >= 0 ; k--)
            t -= U[k + n*j] * x[k];
        x[j] = t*iDiag[j];
    }
    for(j = n - 1 ; j >= 0 ; j--) { // solve Ux=y
        t = x[j];
        for(k = j + 1 ; k < n ; k++)
            t -= U[j + n*k] * x[k];
        x[j] = t*iDiag[j];
    }
}

void normalize_quaternion(float* q) {
    float norm = q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3];
    if (norm > 1e-4f) {
        float inorm = 1.f / sqrtf(norm);
        q[0] *= inorm;
        q[1] *= inorm;
        q[2] *= inorm;
        q[3] *= inorm;
    }
}

void ekf_update(float Z[N_MEASUREMENTS]) {
    // prepare gain calculation
    S[0] = P[0] + R[0];
	S[7] = P[1];
	S[14] = P[3];
	S[21] = P[21];
	S[28] = P[28];
	S[35] = P[36];
	S[42] = P[45];
	S[1] = P[1];
	S[8] = P[2] + R[1];
	S[15] = P[4];
	S[22] = P[22];
	S[29] = P[29];
	S[36] = P[37];
	S[43] = P[46];
	S[2] = P[3];
	S[9] = P[4];
	S[16] = P[5] + R[2];
	S[23] = P[23];
	S[30] = P[30];
	S[37] = P[38];
	S[44] = P[47];
	S[3] = P[21];
	S[10] = P[22];
	S[17] = P[23];
	S[24] = P[27] + R[3];
	S[31] = P[34];
	S[38] = P[42];
	S[45] = P[51];
	S[4] = P[28];
	S[11] = P[29];
	S[18] = P[30];
	S[25] = P[34];
	S[32] = P[35] + R[4];
	S[39] = P[43];
	S[46] = P[52];
	S[5] = P[36];
	S[12] = P[37];
	S[19] = P[38];
	S[26] = P[42];
	S[33] = P[43];
	S[40] = P[44] + R[5];
	S[47] = P[53];
	S[6] = P[45];
	S[13] = P[46];
	S[20] = P[47];
	S[27] = P[51];
	S[34] = P[52];
	S[41] = P[53];
	S[48] = P[54] + R[6];
	HP[0] = P[0];
	HP[1] = P[1];
	HP[2] = P[3];
	HP[3] = P[21];
	HP[4] = P[28];
	HP[5] = P[36];
	HP[6] = P[45];
	HP[7] = P[1];
	HP[8] = P[2];
	HP[9] = P[4];
	HP[10] = P[22];
	HP[11] = P[29];
	HP[12] = P[37];
	HP[13] = P[46];
	HP[14] = P[3];
	HP[15] = P[4];
	HP[16] = P[5];
	HP[17] = P[23];
	HP[18] = P[30];
	HP[19] = P[38];
	HP[20] = P[47];
	HP[21] = P[6];
	HP[22] = P[7];
	HP[23] = P[8];
	HP[24] = P[24];
	HP[25] = P[31];
	HP[26] = P[39];
	HP[27] = P[48];
	HP[28] = P[10];
	HP[29] = P[11];
	HP[30] = P[12];
	HP[31] = P[25];
	HP[32] = P[32];
	HP[33] = P[40];
	HP[34] = P[49];
	HP[35] = P[15];
	HP[36] = P[16];
	HP[37] = P[17];
	HP[38] = P[26];
	HP[39] = P[33];
	HP[40] = P[41];
	HP[41] = P[50];
	HP[42] = P[21];
	HP[43] = P[22];
	HP[44] = P[23];
	HP[45] = P[27];
	HP[46] = P[34];
	HP[47] = P[42];
	HP[48] = P[51];
	HP[49] = P[28];
	HP[50] = P[29];
	HP[51] = P[30];
	HP[52] = P[34];
	HP[53] = P[35];
	HP[54] = P[43];
	HP[55] = P[52];
	HP[56] = P[36];
	HP[57] = P[37];
	HP[58] = P[38];
	HP[59] = P[42];
	HP[60] = P[43];
	HP[61] = P[44];
	HP[62] = P[53];
	HP[63] = P[45];
	HP[64] = P[46];
	HP[65] = P[47];
	HP[66] = P[51];
	HP[67] = P[52];
	HP[68] = P[53];
	HP[69] = P[54];
	HP[70] = P[55];
	HP[71] = P[56];
	HP[72] = P[57];
	HP[73] = P[61];
	HP[74] = P[62];
	HP[75] = P[63];
	HP[76] = P[64];
	HP[77] = P[66];
	HP[78] = P[67];
	HP[79] = P[68];
	HP[80] = P[72];
	HP[81] = P[73];
	HP[82] = P[74];
	HP[83] = P[75];
	HP[84] = P[78];
	HP[85] = P[79];
	HP[86] = P[80];
	HP[87] = P[84];
	HP[88] = P[85];
	HP[89] = P[86];
	HP[90] = P[87];
	HP[91] = P[91];
	HP[92] = P[92];
	HP[93] = P[93];
	HP[94] = P[97];
	HP[95] = P[98];
	HP[96] = P[99];
	HP[97] = P[100];
	HP[98] = P[105];
	HP[99] = P[106];
	HP[100] = P[107];
	HP[101] = P[111];
	HP[102] = P[112];
	HP[103] = P[113];
	HP[104] = P[114];
	HP[105] = P[120];
	HP[106] = P[121];
	HP[107] = P[122];
	HP[108] = P[126];
	HP[109] = P[127];
	HP[110] = P[128];
	HP[111] = P[129];

    // renorm quat
    normalize_quaternion(X+6);

    // we have symmetric S and PHT in col major.
    // Solve K as K^T = invS * H*P, as we have columns of HP. We solve columns of K^T, which are actually rows of K
    //chol_ekf(ekf_S_chol, S, ekf_S_iDiag, N_MEASUREMENTS);
    for (int i = 0; i < N_STATES; i++) {
        float k_row[N_MEASUREMENTS];
        //chol_solve_ekf(ekf_S_chol, ekf_S_iDiag, N_MEASUREMENTS, (HP+(i*N_MEASUREMENTS)), k_row);
        qr_solve( N_MEASUREMENTS, N_MEASUREMENTS, S, (HP+(i*N_MEASUREMENTS)), k_row );
        for (int j = 0; j < N_MEASUREMENTS; j++) {
            K[i + j*N_STATES] = k_row[j];
        }
    }

    float qerror2 = 0.f;
    for (int i = 0; i < 4; i++) {
        qerror2 += (Z[3+i] - X[6+i])*(Z[3+i] - X[6+i]);
    }

    if (qerror2 > 2.f) {
        // quaternion error is too big, negating the measured quaternion will
        // give better convergence
        for (int i = 0; i < 4; i++) {
            Z[3+i] = -Z[3+i];
        }
    }

    // UPDATE STEP X_new, P_new = ...
    tmp[0] = -X[0] + Z[0];
	tmp[1] = -X[1] + Z[1];
	tmp[2] = -X[2] + Z[2];
	tmp[3] = -X[6] + Z[3];
	tmp[4] = -X[7] + Z[4];
	tmp[5] = -X[8] + Z[5];
	tmp[6] = -X[9] + Z[6];
	tmp[7] = 1 - K[0];
	tmp[8] = 1 - K[17];
	tmp[9] = 1 - K[34];
	tmp[10] = 1 - K[54];
	tmp[11] = 1 - K[71];
	tmp[12] = 1 - K[88];
	tmp[13] = 1 - K[105];
	X_new[0] = K[0]*tmp[0] + K[16]*tmp[1] + K[32]*tmp[2] + K[48]*tmp[3] + K[64]*tmp[4] + K[80]*tmp[5] + K[96]*tmp[6] + X[0];
	X_new[1] = K[17]*tmp[1] + K[1]*tmp[0] + K[33]*tmp[2] + K[49]*tmp[3] + K[65]*tmp[4] + K[81]*tmp[5] + K[97]*tmp[6] + X[1];
	X_new[2] = K[18]*tmp[1] + K[2]*tmp[0] + K[34]*tmp[2] + K[50]*tmp[3] + K[66]*tmp[4] + K[82]*tmp[5] + K[98]*tmp[6] + X[2];
	X_new[3] = K[19]*tmp[1] + K[35]*tmp[2] + K[3]*tmp[0] + K[51]*tmp[3] + K[67]*tmp[4] + K[83]*tmp[5] + K[99]*tmp[6] + X[3];
	X_new[4] = K[100]*tmp[6] + K[20]*tmp[1] + K[36]*tmp[2] + K[4]*tmp[0] + K[52]*tmp[3] + K[68]*tmp[4] + K[84]*tmp[5] + X[4];
	X_new[5] = K[101]*tmp[6] + K[21]*tmp[1] + K[37]*tmp[2] + K[53]*tmp[3] + K[5]*tmp[0] + K[69]*tmp[4] + K[85]*tmp[5] + X[5];
	X_new[6] = K[102]*tmp[6] + K[22]*tmp[1] + K[38]*tmp[2] + K[54]*tmp[3] + K[6]*tmp[0] + K[70]*tmp[4] + K[86]*tmp[5] + X[6];
	X_new[7] = K[103]*tmp[6] + K[23]*tmp[1] + K[39]*tmp[2] + K[55]*tmp[3] + K[71]*tmp[4] + K[7]*tmp[0] + K[87]*tmp[5] + X[7];
	X_new[8] = K[104]*tmp[6] + K[24]*tmp[1] + K[40]*tmp[2] + K[56]*tmp[3] + K[72]*tmp[4] + K[88]*tmp[5] + K[8]*tmp[0] + X[8];
	X_new[9] = K[105]*tmp[6] + K[25]*tmp[1] + K[41]*tmp[2] + K[57]*tmp[3] + K[73]*tmp[4] + K[89]*tmp[5] + K[9]*tmp[0] + X[9];
	X_new[10] = K[106]*tmp[6] + K[10]*tmp[0] + K[26]*tmp[1] + K[42]*tmp[2] + K[58]*tmp[3] + K[74]*tmp[4] + K[90]*tmp[5] + X[10];
	X_new[11] = K[107]*tmp[6] + K[11]*tmp[0] + K[27]*tmp[1] + K[43]*tmp[2] + K[59]*tmp[3] + K[75]*tmp[4] + K[91]*tmp[5] + X[11];
	X_new[12] = K[108]*tmp[6] + K[12]*tmp[0] + K[28]*tmp[1] + K[44]*tmp[2] + K[60]*tmp[3] + K[76]*tmp[4] + K[92]*tmp[5] + X[12];
	X_new[13] = K[109]*tmp[6] + K[13]*tmp[0] + K[29]*tmp[1] + K[45]*tmp[2] + K[61]*tmp[3] + K[77]*tmp[4] + K[93]*tmp[5] + X[13];
	X_new[14] = K[110]*tmp[6] + K[14]*tmp[0] + K[30]*tmp[1] + K[46]*tmp[2] + K[62]*tmp[3] + K[78]*tmp[4] + K[94]*tmp[5] + X[14];
	X_new[15] = K[111]*tmp[6] + K[15]*tmp[0] + K[31]*tmp[1] + K[47]*tmp[2] + K[63]*tmp[3] + K[79]*tmp[4] + K[95]*tmp[5] + X[15];
	P_new[0] = -K[16]*P[1] - K[32]*P[3] - K[48]*P[21] - K[64]*P[28] - K[80]*P[36] - K[96]*P[45] + P[0]*tmp[7];
	P_new[1] = -K[16]*P[2] - K[32]*P[4] - K[48]*P[22] - K[64]*P[29] - K[80]*P[37] - K[96]*P[46] + P[1]*tmp[7];
	P_new[3] = -K[16]*P[4] - K[32]*P[5] - K[48]*P[23] - K[64]*P[30] - K[80]*P[38] - K[96]*P[47] + P[3]*tmp[7];
	P_new[6] = -K[16]*P[7] - K[32]*P[8] - K[48]*P[24] - K[64]*P[31] - K[80]*P[39] - K[96]*P[48] + P[6]*tmp[7];
	P_new[10] = -K[16]*P[11] - K[32]*P[12] - K[48]*P[25] - K[64]*P[32] - K[80]*P[40] - K[96]*P[49] + P[10]*tmp[7];
	P_new[15] = -K[16]*P[16] - K[32]*P[17] - K[48]*P[26] - K[64]*P[33] - K[80]*P[41] - K[96]*P[50] + P[15]*tmp[7];
	P_new[21] = -K[16]*P[22] - K[32]*P[23] - K[48]*P[27] - K[64]*P[34] - K[80]*P[42] - K[96]*P[51] + P[21]*tmp[7];
	P_new[28] = -K[16]*P[29] - K[32]*P[30] - K[48]*P[34] - K[64]*P[35] - K[80]*P[43] - K[96]*P[52] + P[28]*tmp[7];
	P_new[36] = -K[16]*P[37] - K[32]*P[38] - K[48]*P[42] - K[64]*P[43] - K[80]*P[44] - K[96]*P[53] + P[36]*tmp[7];
	P_new[45] = -K[16]*P[46] - K[32]*P[47] - K[48]*P[51] - K[64]*P[52] - K[80]*P[53] - K[96]*P[54] + P[45]*tmp[7];
	P_new[55] = -K[16]*P[56] - K[32]*P[57] - K[48]*P[61] - K[64]*P[62] - K[80]*P[63] - K[96]*P[64] + P[55]*tmp[7];
	P_new[66] = -K[16]*P[67] - K[32]*P[68] - K[48]*P[72] - K[64]*P[73] - K[80]*P[74] - K[96]*P[75] + P[66]*tmp[7];
	P_new[78] = -K[16]*P[79] - K[32]*P[80] - K[48]*P[84] - K[64]*P[85] - K[80]*P[86] - K[96]*P[87] + P[78]*tmp[7];
	P_new[91] = -K[16]*P[92] - K[32]*P[93] - K[48]*P[97] - K[64]*P[98] - K[80]*P[99] - K[96]*P[100] + P[91]*tmp[7];
	P_new[105] = -K[16]*P[106] - K[32]*P[107] - K[48]*P[111] - K[64]*P[112] - K[80]*P[113] - K[96]*P[114] + P[105]*tmp[7];
	P_new[120] = -K[16]*P[121] - K[32]*P[122] - K[48]*P[126] - K[64]*P[127] - K[80]*P[128] - K[96]*P[129] + P[120]*tmp[7];
	P_new[2] = -K[1]*P[1] - K[33]*P[4] - K[49]*P[22] - K[65]*P[29] - K[81]*P[37] - K[97]*P[46] + P[2]*tmp[8];
	P_new[4] = -K[1]*P[3] - K[33]*P[5] - K[49]*P[23] - K[65]*P[30] - K[81]*P[38] - K[97]*P[47] + P[4]*tmp[8];
	P_new[7] = -K[1]*P[6] - K[33]*P[8] - K[49]*P[24] - K[65]*P[31] - K[81]*P[39] - K[97]*P[48] + P[7]*tmp[8];
	P_new[11] = -K[1]*P[10] - K[33]*P[12] - K[49]*P[25] - K[65]*P[32] - K[81]*P[40] - K[97]*P[49] + P[11]*tmp[8];
	P_new[16] = -K[1]*P[15] - K[33]*P[17] - K[49]*P[26] - K[65]*P[33] - K[81]*P[41] - K[97]*P[50] + P[16]*tmp[8];
	P_new[22] = -K[1]*P[21] - K[33]*P[23] - K[49]*P[27] - K[65]*P[34] - K[81]*P[42] - K[97]*P[51] + P[22]*tmp[8];
	P_new[29] = -K[1]*P[28] - K[33]*P[30] - K[49]*P[34] - K[65]*P[35] - K[81]*P[43] - K[97]*P[52] + P[29]*tmp[8];
	P_new[37] = -K[1]*P[36] - K[33]*P[38] - K[49]*P[42] - K[65]*P[43] - K[81]*P[44] - K[97]*P[53] + P[37]*tmp[8];
	P_new[46] = -K[1]*P[45] - K[33]*P[47] - K[49]*P[51] - K[65]*P[52] - K[81]*P[53] - K[97]*P[54] + P[46]*tmp[8];
	P_new[56] = -K[1]*P[55] - K[33]*P[57] - K[49]*P[61] - K[65]*P[62] - K[81]*P[63] - K[97]*P[64] + P[56]*tmp[8];
	P_new[67] = -K[1]*P[66] - K[33]*P[68] - K[49]*P[72] - K[65]*P[73] - K[81]*P[74] - K[97]*P[75] + P[67]*tmp[8];
	P_new[79] = -K[1]*P[78] - K[33]*P[80] - K[49]*P[84] - K[65]*P[85] - K[81]*P[86] - K[97]*P[87] + P[79]*tmp[8];
	P_new[92] = -K[1]*P[91] - K[33]*P[93] - K[49]*P[97] - K[65]*P[98] - K[81]*P[99] - K[97]*P[100] + P[92]*tmp[8];
	P_new[106] = -K[1]*P[105] - K[33]*P[107] - K[49]*P[111] - K[65]*P[112] - K[81]*P[113] - K[97]*P[114] + P[106]*tmp[8];
	P_new[121] = -K[1]*P[120] - K[33]*P[122] - K[49]*P[126] - K[65]*P[127] - K[81]*P[128] - K[97]*P[129] + P[121]*tmp[8];
	P_new[5] = -K[18]*P[4] - K[2]*P[3] - K[50]*P[23] - K[66]*P[30] - K[82]*P[38] - K[98]*P[47] + P[5]*tmp[9];
	P_new[8] = -K[18]*P[7] - K[2]*P[6] - K[50]*P[24] - K[66]*P[31] - K[82]*P[39] - K[98]*P[48] + P[8]*tmp[9];
	P_new[12] = -K[18]*P[11] - K[2]*P[10] - K[50]*P[25] - K[66]*P[32] - K[82]*P[40] - K[98]*P[49] + P[12]*tmp[9];
	P_new[17] = -K[18]*P[16] - K[2]*P[15] - K[50]*P[26] - K[66]*P[33] - K[82]*P[41] - K[98]*P[50] + P[17]*tmp[9];
	P_new[23] = -K[18]*P[22] - K[2]*P[21] - K[50]*P[27] - K[66]*P[34] - K[82]*P[42] - K[98]*P[51] + P[23]*tmp[9];
	P_new[30] = -K[18]*P[29] - K[2]*P[28] - K[50]*P[34] - K[66]*P[35] - K[82]*P[43] - K[98]*P[52] + P[30]*tmp[9];
	P_new[38] = -K[18]*P[37] - K[2]*P[36] - K[50]*P[42] - K[66]*P[43] - K[82]*P[44] - K[98]*P[53] + P[38]*tmp[9];
	P_new[47] = -K[18]*P[46] - K[2]*P[45] - K[50]*P[51] - K[66]*P[52] - K[82]*P[53] - K[98]*P[54] + P[47]*tmp[9];
	P_new[57] = -K[18]*P[56] - K[2]*P[55] - K[50]*P[61] - K[66]*P[62] - K[82]*P[63] - K[98]*P[64] + P[57]*tmp[9];
	P_new[68] = -K[18]*P[67] - K[2]*P[66] - K[50]*P[72] - K[66]*P[73] - K[82]*P[74] - K[98]*P[75] + P[68]*tmp[9];
	P_new[80] = -K[18]*P[79] - K[2]*P[78] - K[50]*P[84] - K[66]*P[85] - K[82]*P[86] - K[98]*P[87] + P[80]*tmp[9];
	P_new[93] = -K[18]*P[92] - K[2]*P[91] - K[50]*P[97] - K[66]*P[98] - K[82]*P[99] - K[98]*P[100] + P[93]*tmp[9];
	P_new[107] = -K[18]*P[106] - K[2]*P[105] - K[50]*P[111] - K[66]*P[112] - K[82]*P[113] - K[98]*P[114] + P[107]*tmp[9];
	P_new[122] = -K[18]*P[121] - K[2]*P[120] - K[50]*P[126] - K[66]*P[127] - K[82]*P[128] - K[98]*P[129] + P[122]*tmp[9];
	P_new[9] = -K[19]*P[7] - K[35]*P[8] - K[3]*P[6] - K[51]*P[24] - K[67]*P[31] - K[83]*P[39] - K[99]*P[48] + P[9];
	P_new[13] = -K[19]*P[11] - K[35]*P[12] - K[3]*P[10] - K[51]*P[25] - K[67]*P[32] - K[83]*P[40] - K[99]*P[49] + P[13];
	P_new[18] = -K[19]*P[16] - K[35]*P[17] - K[3]*P[15] - K[51]*P[26] - K[67]*P[33] - K[83]*P[41] - K[99]*P[50] + P[18];
	P_new[24] = -K[19]*P[22] - K[35]*P[23] - K[3]*P[21] - K[51]*P[27] - K[67]*P[34] - K[83]*P[42] - K[99]*P[51] + P[24];
	P_new[31] = -K[19]*P[29] - K[35]*P[30] - K[3]*P[28] - K[51]*P[34] - K[67]*P[35] - K[83]*P[43] - K[99]*P[52] + P[31];
	P_new[39] = -K[19]*P[37] - K[35]*P[38] - K[3]*P[36] - K[51]*P[42] - K[67]*P[43] - K[83]*P[44] - K[99]*P[53] + P[39];
	P_new[48] = -K[19]*P[46] - K[35]*P[47] - K[3]*P[45] - K[51]*P[51] - K[67]*P[52] - K[83]*P[53] - K[99]*P[54] + P[48];
	P_new[58] = -K[19]*P[56] - K[35]*P[57] - K[3]*P[55] - K[51]*P[61] - K[67]*P[62] - K[83]*P[63] - K[99]*P[64] + P[58];
	P_new[69] = -K[19]*P[67] - K[35]*P[68] - K[3]*P[66] - K[51]*P[72] - K[67]*P[73] - K[83]*P[74] - K[99]*P[75] + P[69];
	P_new[81] = -K[19]*P[79] - K[35]*P[80] - K[3]*P[78] - K[51]*P[84] - K[67]*P[85] - K[83]*P[86] - K[99]*P[87] + P[81];
	P_new[94] = -K[19]*P[92] - K[35]*P[93] - K[3]*P[91] - K[51]*P[97] - K[67]*P[98] - K[83]*P[99] - K[99]*P[100] + P[94];
	P_new[108] = -K[19]*P[106] - K[35]*P[107] - K[3]*P[105] - K[51]*P[111] - K[67]*P[112] - K[83]*P[113] - K[99]*P[114] + P[108];
	P_new[123] = -K[19]*P[121] - K[35]*P[122] - K[3]*P[120] - K[51]*P[126] - K[67]*P[127] - K[83]*P[128] - K[99]*P[129] + P[123];
	P_new[14] = -K[100]*P[49] - K[20]*P[11] - K[36]*P[12] - K[4]*P[10] - K[52]*P[25] - K[68]*P[32] - K[84]*P[40] + P[14];
	P_new[19] = -K[100]*P[50] - K[20]*P[16] - K[36]*P[17] - K[4]*P[15] - K[52]*P[26] - K[68]*P[33] - K[84]*P[41] + P[19];
	P_new[25] = -K[100]*P[51] - K[20]*P[22] - K[36]*P[23] - K[4]*P[21] - K[52]*P[27] - K[68]*P[34] - K[84]*P[42] + P[25];
	P_new[32] = -K[100]*P[52] - K[20]*P[29] - K[36]*P[30] - K[4]*P[28] - K[52]*P[34] - K[68]*P[35] - K[84]*P[43] + P[32];
	P_new[40] = -K[100]*P[53] - K[20]*P[37] - K[36]*P[38] - K[4]*P[36] - K[52]*P[42] - K[68]*P[43] - K[84]*P[44] + P[40];
	P_new[49] = -K[100]*P[54] - K[20]*P[46] - K[36]*P[47] - K[4]*P[45] - K[52]*P[51] - K[68]*P[52] - K[84]*P[53] + P[49];
	P_new[59] = -K[100]*P[64] - K[20]*P[56] - K[36]*P[57] - K[4]*P[55] - K[52]*P[61] - K[68]*P[62] - K[84]*P[63] + P[59];
	P_new[70] = -K[100]*P[75] - K[20]*P[67] - K[36]*P[68] - K[4]*P[66] - K[52]*P[72] - K[68]*P[73] - K[84]*P[74] + P[70];
	P_new[82] = -K[100]*P[87] - K[20]*P[79] - K[36]*P[80] - K[4]*P[78] - K[52]*P[84] - K[68]*P[85] - K[84]*P[86] + P[82];
	P_new[95] = -K[100]*P[100] - K[20]*P[92] - K[36]*P[93] - K[4]*P[91] - K[52]*P[97] - K[68]*P[98] - K[84]*P[99] + P[95];
	P_new[109] = -K[100]*P[114] - K[20]*P[106] - K[36]*P[107] - K[4]*P[105] - K[52]*P[111] - K[68]*P[112] - K[84]*P[113] + P[109];
	P_new[124] = -K[100]*P[129] - K[20]*P[121] - K[36]*P[122] - K[4]*P[120] - K[52]*P[126] - K[68]*P[127] - K[84]*P[128] + P[124];
	P_new[20] = -K[101]*P[50] - K[21]*P[16] - K[37]*P[17] - K[53]*P[26] - K[5]*P[15] - K[69]*P[33] - K[85]*P[41] + P[20];
	P_new[26] = -K[101]*P[51] - K[21]*P[22] - K[37]*P[23] - K[53]*P[27] - K[5]*P[21] - K[69]*P[34] - K[85]*P[42] + P[26];
	P_new[33] = -K[101]*P[52] - K[21]*P[29] - K[37]*P[30] - K[53]*P[34] - K[5]*P[28] - K[69]*P[35] - K[85]*P[43] + P[33];
	P_new[41] = -K[101]*P[53] - K[21]*P[37] - K[37]*P[38] - K[53]*P[42] - K[5]*P[36] - K[69]*P[43] - K[85]*P[44] + P[41];
	P_new[50] = -K[101]*P[54] - K[21]*P[46] - K[37]*P[47] - K[53]*P[51] - K[5]*P[45] - K[69]*P[52] - K[85]*P[53] + P[50];
	P_new[60] = -K[101]*P[64] - K[21]*P[56] - K[37]*P[57] - K[53]*P[61] - K[5]*P[55] - K[69]*P[62] - K[85]*P[63] + P[60];
	P_new[71] = -K[101]*P[75] - K[21]*P[67] - K[37]*P[68] - K[53]*P[72] - K[5]*P[66] - K[69]*P[73] - K[85]*P[74] + P[71];
	P_new[83] = -K[101]*P[87] - K[21]*P[79] - K[37]*P[80] - K[53]*P[84] - K[5]*P[78] - K[69]*P[85] - K[85]*P[86] + P[83];
	P_new[96] = -K[101]*P[100] - K[21]*P[92] - K[37]*P[93] - K[53]*P[97] - K[5]*P[91] - K[69]*P[98] - K[85]*P[99] + P[96];
	P_new[110] = -K[101]*P[114] - K[21]*P[106] - K[37]*P[107] - K[53]*P[111] - K[5]*P[105] - K[69]*P[112] - K[85]*P[113] + P[110];
	P_new[125] = -K[101]*P[129] - K[21]*P[121] - K[37]*P[122] - K[53]*P[126] - K[5]*P[120] - K[69]*P[127] - K[85]*P[128] + P[125];
	P_new[27] = -K[102]*P[51] - K[22]*P[22] - K[38]*P[23] - K[6]*P[21] - K[70]*P[34] - K[86]*P[42] + P[27]*tmp[10];
	P_new[34] = -K[102]*P[52] - K[22]*P[29] - K[38]*P[30] - K[6]*P[28] - K[70]*P[35] - K[86]*P[43] + P[34]*tmp[10];
	P_new[42] = -K[102]*P[53] - K[22]*P[37] - K[38]*P[38] - K[6]*P[36] - K[70]*P[43] - K[86]*P[44] + P[42]*tmp[10];
	P_new[51] = -K[102]*P[54] - K[22]*P[46] - K[38]*P[47] - K[6]*P[45] - K[70]*P[52] - K[86]*P[53] + P[51]*tmp[10];
	P_new[61] = -K[102]*P[64] - K[22]*P[56] - K[38]*P[57] - K[6]*P[55] - K[70]*P[62] - K[86]*P[63] + P[61]*tmp[10];
	P_new[72] = -K[102]*P[75] - K[22]*P[67] - K[38]*P[68] - K[6]*P[66] - K[70]*P[73] - K[86]*P[74] + P[72]*tmp[10];
	P_new[84] = -K[102]*P[87] - K[22]*P[79] - K[38]*P[80] - K[6]*P[78] - K[70]*P[85] - K[86]*P[86] + P[84]*tmp[10];
	P_new[97] = -K[102]*P[100] - K[22]*P[92] - K[38]*P[93] - K[6]*P[91] - K[70]*P[98] - K[86]*P[99] + P[97]*tmp[10];
	P_new[111] = -K[102]*P[114] - K[22]*P[106] - K[38]*P[107] - K[6]*P[105] - K[70]*P[112] - K[86]*P[113] + P[111]*tmp[10];
	P_new[126] = -K[102]*P[129] - K[22]*P[121] - K[38]*P[122] - K[6]*P[120] - K[70]*P[127] - K[86]*P[128] + P[126]*tmp[10];
	P_new[35] = -K[103]*P[52] - K[23]*P[29] - K[39]*P[30] - K[55]*P[34] - K[7]*P[28] - K[87]*P[43] + P[35]*tmp[11];
	P_new[43] = -K[103]*P[53] - K[23]*P[37] - K[39]*P[38] - K[55]*P[42] - K[7]*P[36] - K[87]*P[44] + P[43]*tmp[11];
	P_new[52] = -K[103]*P[54] - K[23]*P[46] - K[39]*P[47] - K[55]*P[51] - K[7]*P[45] - K[87]*P[53] + P[52]*tmp[11];
	P_new[62] = -K[103]*P[64] - K[23]*P[56] - K[39]*P[57] - K[55]*P[61] - K[7]*P[55] - K[87]*P[63] + P[62]*tmp[11];
	P_new[73] = -K[103]*P[75] - K[23]*P[67] - K[39]*P[68] - K[55]*P[72] - K[7]*P[66] - K[87]*P[74] + P[73]*tmp[11];
	P_new[85] = -K[103]*P[87] - K[23]*P[79] - K[39]*P[80] - K[55]*P[84] - K[7]*P[78] - K[87]*P[86] + P[85]*tmp[11];
	P_new[98] = -K[103]*P[100] - K[23]*P[92] - K[39]*P[93] - K[55]*P[97] - K[7]*P[91] - K[87]*P[99] + P[98]*tmp[11];
	P_new[112] = -K[103]*P[114] - K[23]*P[106] - K[39]*P[107] - K[55]*P[111] - K[7]*P[105] - K[87]*P[113] + P[112]*tmp[11];
	P_new[127] = -K[103]*P[129] - K[23]*P[121] - K[39]*P[122] - K[55]*P[126] - K[7]*P[120] - K[87]*P[128] + P[127]*tmp[11];
	P_new[44] = -K[104]*P[53] - K[24]*P[37] - K[40]*P[38] - K[56]*P[42] - K[72]*P[43] - K[8]*P[36] + P[44]*tmp[12];
	P_new[53] = -K[104]*P[54] - K[24]*P[46] - K[40]*P[47] - K[56]*P[51] - K[72]*P[52] - K[8]*P[45] + P[53]*tmp[12];
	P_new[63] = -K[104]*P[64] - K[24]*P[56] - K[40]*P[57] - K[56]*P[61] - K[72]*P[62] - K[8]*P[55] + P[63]*tmp[12];
	P_new[74] = -K[104]*P[75] - K[24]*P[67] - K[40]*P[68] - K[56]*P[72] - K[72]*P[73] - K[8]*P[66] + P[74]*tmp[12];
	P_new[86] = -K[104]*P[87] - K[24]*P[79] - K[40]*P[80] - K[56]*P[84] - K[72]*P[85] - K[8]*P[78] + P[86]*tmp[12];
	P_new[99] = -K[104]*P[100] - K[24]*P[92] - K[40]*P[93] - K[56]*P[97] - K[72]*P[98] - K[8]*P[91] + P[99]*tmp[12];
	P_new[113] = -K[104]*P[114] - K[24]*P[106] - K[40]*P[107] - K[56]*P[111] - K[72]*P[112] - K[8]*P[105] + P[113]*tmp[12];
	P_new[128] = -K[104]*P[129] - K[24]*P[121] - K[40]*P[122] - K[56]*P[126] - K[72]*P[127] - K[8]*P[120] + P[128]*tmp[12];
	P_new[54] = -K[25]*P[46] - K[41]*P[47] - K[57]*P[51] - K[73]*P[52] - K[89]*P[53] - K[9]*P[45] + P[54]*tmp[13];
	P_new[64] = -K[25]*P[56] - K[41]*P[57] - K[57]*P[61] - K[73]*P[62] - K[89]*P[63] - K[9]*P[55] + P[64]*tmp[13];
	P_new[75] = -K[25]*P[67] - K[41]*P[68] - K[57]*P[72] - K[73]*P[73] - K[89]*P[74] - K[9]*P[66] + P[75]*tmp[13];
	P_new[87] = -K[25]*P[79] - K[41]*P[80] - K[57]*P[84] - K[73]*P[85] - K[89]*P[86] - K[9]*P[78] + P[87]*tmp[13];
	P_new[100] = -K[25]*P[92] - K[41]*P[93] - K[57]*P[97] - K[73]*P[98] - K[89]*P[99] - K[9]*P[91] + P[100]*tmp[13];
	P_new[114] = -K[25]*P[106] - K[41]*P[107] - K[57]*P[111] - K[73]*P[112] - K[89]*P[113] - K[9]*P[105] + P[114]*tmp[13];
	P_new[129] = -K[25]*P[121] - K[41]*P[122] - K[57]*P[126] - K[73]*P[127] - K[89]*P[128] - K[9]*P[120] + P[129]*tmp[13];
	P_new[65] = -K[106]*P[64] - K[10]*P[55] - K[26]*P[56] - K[42]*P[57] - K[58]*P[61] - K[74]*P[62] - K[90]*P[63] + P[65];
	P_new[76] = -K[106]*P[75] - K[10]*P[66] - K[26]*P[67] - K[42]*P[68] - K[58]*P[72] - K[74]*P[73] - K[90]*P[74] + P[76];
	P_new[88] = -K[106]*P[87] - K[10]*P[78] - K[26]*P[79] - K[42]*P[80] - K[58]*P[84] - K[74]*P[85] - K[90]*P[86] + P[88];
	P_new[101] = -K[106]*P[100] - K[10]*P[91] - K[26]*P[92] - K[42]*P[93] - K[58]*P[97] - K[74]*P[98] - K[90]*P[99] + P[101];
	P_new[115] = -K[106]*P[114] - K[10]*P[105] - K[26]*P[106] - K[42]*P[107] - K[58]*P[111] - K[74]*P[112] - K[90]*P[113] + P[115];
	P_new[130] = -K[106]*P[129] - K[10]*P[120] - K[26]*P[121] - K[42]*P[122] - K[58]*P[126] - K[74]*P[127] - K[90]*P[128] + P[130];
	P_new[77] = -K[107]*P[75] - K[11]*P[66] - K[27]*P[67] - K[43]*P[68] - K[59]*P[72] - K[75]*P[73] - K[91]*P[74] + P[77];
	P_new[89] = -K[107]*P[87] - K[11]*P[78] - K[27]*P[79] - K[43]*P[80] - K[59]*P[84] - K[75]*P[85] - K[91]*P[86] + P[89];
	P_new[102] = -K[107]*P[100] - K[11]*P[91] - K[27]*P[92] - K[43]*P[93] - K[59]*P[97] - K[75]*P[98] - K[91]*P[99] + P[102];
	P_new[116] = -K[107]*P[114] - K[11]*P[105] - K[27]*P[106] - K[43]*P[107] - K[59]*P[111] - K[75]*P[112] - K[91]*P[113] + P[116];
	P_new[131] = -K[107]*P[129] - K[11]*P[120] - K[27]*P[121] - K[43]*P[122] - K[59]*P[126] - K[75]*P[127] - K[91]*P[128] + P[131];
	P_new[90] = -K[108]*P[87] - K[12]*P[78] - K[28]*P[79] - K[44]*P[80] - K[60]*P[84] - K[76]*P[85] - K[92]*P[86] + P[90];
	P_new[103] = -K[108]*P[100] - K[12]*P[91] - K[28]*P[92] - K[44]*P[93] - K[60]*P[97] - K[76]*P[98] - K[92]*P[99] + P[103];
	P_new[117] = -K[108]*P[114] - K[12]*P[105] - K[28]*P[106] - K[44]*P[107] - K[60]*P[111] - K[76]*P[112] - K[92]*P[113] + P[117];
	P_new[132] = -K[108]*P[129] - K[12]*P[120] - K[28]*P[121] - K[44]*P[122] - K[60]*P[126] - K[76]*P[127] - K[92]*P[128] + P[132];
	P_new[104] = -K[109]*P[100] - K[13]*P[91] - K[29]*P[92] - K[45]*P[93] - K[61]*P[97] - K[77]*P[98] - K[93]*P[99] + P[104];
	P_new[118] = -K[109]*P[114] - K[13]*P[105] - K[29]*P[106] - K[45]*P[107] - K[61]*P[111] - K[77]*P[112] - K[93]*P[113] + P[118];
	P_new[133] = -K[109]*P[129] - K[13]*P[120] - K[29]*P[121] - K[45]*P[122] - K[61]*P[126] - K[77]*P[127] - K[93]*P[128] + P[133];
	P_new[119] = -K[110]*P[114] - K[14]*P[105] - K[30]*P[106] - K[46]*P[107] - K[62]*P[111] - K[78]*P[112] - K[94]*P[113] + P[119];
	P_new[134] = -K[110]*P[129] - K[14]*P[120] - K[30]*P[121] - K[46]*P[122] - K[62]*P[126] - K[78]*P[127] - K[94]*P[128] + P[134];
	P_new[135] = -K[111]*P[129] - K[15]*P[120] - K[31]*P[121] - K[47]*P[122] - K[63]*P[126] - K[79]*P[127] - K[95]*P[128] + P[135];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    normalize_quaternion(X+6);

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}
