
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated in "Generate Kalman Filter C Code.ipynb" from https://github.com/tudelft/kalman_filter   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef EKF_CALC_H
#define EKF_CALC_H

#include <stdint.h>

#ifdef __cplusplus
namespace orin_ekf {
#endif

#define N_STATES 22
#define N_INPUTS 6
#define N_PROC_NOISES 18

// getters
float* ekf_get_X(void);         // get state vector
float* ekf_get_P(void);         // get covariance matrix (lower diagonal)
float* ekf_get_P_diag(void);

#define ekf_P_index(i,j) ((i>=j) ? ekf_get_P()[i*(i+1)/2+j] : ekf_get_P()[j*(j+1)/2+i])
#define ekf_increment_P_diag(i,v) { ekf_get_P()[i*(i+1)/2+i] += v; }
#define ekf_X_index(i) ekf_get_X()[i]

// setters
void ekf_set_Q(float Q[N_INPUTS]);                    // set process noise covariance matrix diagonal
void ekf_set_X(float X0[N_STATES]);                   // set state vector
void ekf_set_P_diag(float P_diag[N_STATES]);          // set covariance matrix diagonal

// prediction function
void ekf_predict(float U[N_INPUTS], float dt);
// integrate
void ekf_integrate(float X_[N_STATES], float U[N_INPUTS], float dt);

// update functions (for different measurement models)
// pos measurement model:
#define N_MEASUREMENTS_POS 3
void ekf_set_R_pos(float R_diag[N_MEASUREMENTS_POS]); // set measurement noise covariance matrix diagonal
void ekf_update_pos(float Z[N_MEASUREMENTS_POS]);

// pos_quat measurement model:
#define N_MEASUREMENTS_POS_QUAT 7
void ekf_set_R_pos_quat(float R_diag[N_MEASUREMENTS_POS_QUAT]); // set measurement noise covariance matrix diagonal
void ekf_update_pos_quat(float Z[N_MEASUREMENTS_POS_QUAT]);

// points_1 measurement model:
#define N_MEASUREMENTS_POINTS_1 2
void ekf_set_R_points_1(float R_diag[N_MEASUREMENTS_POINTS_1]); // set measurement noise covariance matrix diagonal
void ekf_update_points_1(float Z[N_MEASUREMENTS_POINTS_1], float param[7]);


#ifdef __cplusplus
} // namespace orin_ekf
#endif

#endif // EKF_CALC_H
