
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated in "Generate Kalman Filter C Code.ipynb" from https://github.com/tudelft/kalman_filter   //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#include "ekf_calc.h"
#include <math.h>
#include <stdio.h>
#include "common/maths.h"
#include <stdbool.h>

bool ekf_use_quat = false;

float ekf_Q[N_PROC_NOISES];         // Kalman filter process noise covariance matrix (diagonal)
float ekf_R[N_MEASUREMENTS];   // Kalman filter measurement noise covariance matrix (diagonal)

// state
float ekf_X[N_STATES];
float ekf_X_new[N_STATES];

// covariance matrix (upper diagonal) P[i,j] = P_upper_diagonal[i*(i+1)/2+j] (if i>=j)
float ekf_P_upper_diagonal[N_STATES*(N_STATES+1)/2];
float ekf_P_upper_diagonal_new[N_STATES*(N_STATES+1)/2];

// gain matrix calculations
float ekf_S_full[N_MEASUREMENTS*N_MEASUREMENTS];
float ekf_S_chol[N_MEASUREMENTS*N_MEASUREMENTS];
float ekf_S_iDiag[N_MEASUREMENTS];
float ekf_HP[N_STATES*N_MEASUREMENTS];
float ekf_K[N_STATES*N_MEASUREMENTS];

// temporary variables
float tmp[371];

// pointers
float *X = ekf_X;
float *X_new = ekf_X_new;

float *P = ekf_P_upper_diagonal;
float *P_new = ekf_P_upper_diagonal_new;

float *S = ekf_S_full;
float *HP = ekf_HP;
float *K = ekf_K;

// renaming
float *Q = ekf_Q;
float *R = ekf_R;

// pointer for swapping
float *swap_ptr;

float* ekf_get_X(void) {
    return X;
}

float* ekf_get_P(void) {
    return P;
}

void ekf_set_Q(float Q[N_INPUTS]) {
    for (int i=0; i<N_PROC_NOISES; i++) {
        ekf_Q[i] = Q[i];
    }
}

void ekf_set_R(float R[N_MEASUREMENTS]) {
    for (int i=0; i<N_MEASUREMENTS; i++) {
        ekf_R[i] = R[i];
    }
}

void ekf_set_X(float X0[N_STATES]) {
    for (int i=0; i<N_STATES; i++) {
        X[i] = X0[i];
    }
}

void ekf_set_P_diag(float P_diag[N_STATES]) {
    // set P to zeros
    for (int i=0; i<N_STATES*(N_STATES+1)/2; i++) {
        P[i] = 0.;
    }
    // set diagonal
    for (int i=0; i<N_STATES; i++) {
        P[i*(i+1)/2+i] = P_diag[i];
    }
}

void normalize_quaternion(float* q) {
    float norm = q[0]*q[0] + q[1]*q[1] + q[2]*q[2] + q[3]*q[3];
    if (norm > 1e-4f) {
        float inorm = 1.f / sqrtf(norm);
        q[0] *= inorm;
        q[1] *= inorm;
        q[2] *= inorm;
        q[3] *= inorm;
    }
}

void ekf_predict(float U[N_INPUTS], float dt) {
    // PREDICTION STEP X_new, P_new = ...
    tmp[0] = powf(X[6], 2);
	tmp[1] = powf(X[7], 2);
	tmp[2] = powf(X[8], 2);
	tmp[3] = powf(X[9], 2);
	tmp[4] = tmp[0] + tmp[1] + tmp[2] + tmp[3];
	tmp[5] = powf(tmp[4], -1.0/2.0);
	tmp[6] = U[0] - X[10];
	tmp[7] = tmp[5]*tmp[6];
	tmp[8] = U[2] - X[12];
	tmp[9] = tmp[5]*tmp[8];
	tmp[10] = U[1] - X[11];
	tmp[11] = tmp[10]*tmp[5];
	tmp[12] = X[6]*tmp[7] + X[8]*tmp[9] - X[9]*tmp[11];
	tmp[13] = tmp[12]*tmp[5];
	tmp[14] = X[6]*tmp[9] + X[7]*tmp[11] - X[8]*tmp[7];
	tmp[15] = tmp[14]*tmp[5];
	tmp[16] = X[6]*tmp[11] - X[7]*tmp[9] + X[9]*tmp[7];
	tmp[17] = tmp[16]*tmp[5];
	tmp[18] = -X[7]*tmp[7] - X[8]*tmp[11] - X[9]*tmp[9];
	tmp[19] = tmp[18]*tmp[5];
	tmp[20] = -tmp[12];
	tmp[21] = tmp[20]*tmp[5];
	tmp[22] = 0.5*U[3] - 0.5*X[13];
	tmp[23] = U[4] - X[14];
	tmp[24] = 0.5*X[8];
	tmp[25] = U[5] - X[15];
	tmp[26] = 0.5*X[9];
	tmp[27] = 0.5*X[6];
	tmp[28] = 0.5*X[7];
	tmp[29] = P[6] + P[9]*dt;
	tmp[30] = P[13]*dt;
	tmp[31] = P[10] + tmp[30];
	tmp[32] = P[18]*dt;
	tmp[33] = P[15] + tmp[32];
	tmp[34] = powf(tmp[4], -3.0/2.0);
	tmp[35] = X[6]*tmp[34];
	tmp[36] = X[9]*tmp[35];
	tmp[37] = tmp[16]*tmp[36];
	tmp[38] = X[8]*tmp[35];
	tmp[39] = tmp[14]*tmp[38];
	tmp[40] = tmp[0]*tmp[34];
	tmp[41] = X[7]*tmp[35];
	tmp[42] = tmp[41]*tmp[6];
	tmp[43] = tmp[10]*tmp[35];
	tmp[44] = X[8]*tmp[43];
	tmp[45] = tmp[36]*tmp[8];
	tmp[46] = tmp[42] + tmp[44] + tmp[45];
	tmp[47] = X[7]*tmp[5];
	tmp[48] = -tmp[7];
	tmp[49] = tmp[38]*tmp[8];
	tmp[50] = X[9]*tmp[43];
	tmp[51] = tmp[40]*tmp[6] + tmp[48] + tmp[49] - tmp[50];
	tmp[52] = -tmp[51];
	tmp[53] = X[6]*tmp[5];
	tmp[54] = -tmp[9];
	tmp[55] = X[7]*tmp[43];
	tmp[56] = tmp[38]*tmp[6];
	tmp[57] = -tmp[40]*tmp[8] - tmp[54] - tmp[55] + tmp[56];
	tmp[58] = X[8]*tmp[5];
	tmp[59] = -tmp[11];
	tmp[60] = tmp[36]*tmp[6];
	tmp[61] = tmp[41]*tmp[8];
	tmp[62] = -tmp[10]*tmp[40] - tmp[59] - tmp[60] + tmp[61];
	tmp[63] = X[9]*tmp[5];
	tmp[64] = -tmp[12]*tmp[40] + tmp[13] + tmp[18]*tmp[41] + tmp[37] - tmp[39] - tmp[46]*tmp[47] + tmp[52]*tmp[53] + tmp[57]*tmp[58] - tmp[62]*tmp[63];
	tmp[65] = P[24]*dt;
	tmp[66] = P[21] + tmp[65];
	tmp[67] = dt*tmp[66];
	tmp[68] = X[7]*tmp[34];
	tmp[69] = X[8]*tmp[68];
	tmp[70] = tmp[14]*tmp[69];
	tmp[71] = X[9]*tmp[68];
	tmp[72] = tmp[16]*tmp[71];
	tmp[73] = tmp[69]*tmp[8];
	tmp[74] = tmp[10]*tmp[68];
	tmp[75] = X[9]*tmp[74];
	tmp[76] = tmp[42] + tmp[73] - tmp[75];
	tmp[77] = -tmp[76];
	tmp[78] = X[8]*tmp[74];
	tmp[79] = tmp[1]*tmp[34];
	tmp[80] = tmp[48] + tmp[6]*tmp[79] + tmp[71]*tmp[8] + tmp[78];
	tmp[81] = X[7]*X[8]*tmp[34]*tmp[6] - tmp[10]*tmp[79] - tmp[59] - tmp[61];
	tmp[82] = tmp[6]*tmp[71];
	tmp[83] = tmp[1]*tmp[34]*tmp[8] - tmp[55] - tmp[82] - tmp[9];
	tmp[84] = X[6]*tmp[5]*tmp[77] + X[8]*tmp[5]*tmp[81] - tmp[12]*tmp[41] + tmp[18]*tmp[1]*tmp[34] - tmp[19] - tmp[47]*tmp[80] - tmp[63]*tmp[83] - tmp[70] + tmp[72];
	tmp[85] = P[31]*dt;
	tmp[86] = P[28] + tmp[85];
	tmp[87] = dt*tmp[86];
	tmp[88] = X[8]*X[9];
	tmp[89] = tmp[34]*tmp[88];
	tmp[90] = tmp[12]*tmp[38];
	tmp[91] = tmp[2]*tmp[34];
	tmp[92] = tmp[6]*tmp[89];
	tmp[93] = -tmp[44] + tmp[73] - tmp[92];
	tmp[94] = -X[8]*X[9]*tmp[10]*tmp[34] + tmp[54] + tmp[56] + tmp[8]*tmp[91];
	tmp[95] = -tmp[94];
	tmp[96] = tmp[89]*tmp[8];
	tmp[97] = tmp[10]*tmp[91] + tmp[59] + tmp[69]*tmp[6] + tmp[96];
	tmp[98] = tmp[2]*tmp[34]*tmp[6] - tmp[49] - tmp[78] - tmp[7];
	tmp[99] = -tmp[14]*tmp[91] + tmp[15] + tmp[16]*tmp[89] + tmp[18]*tmp[69] - tmp[47]*tmp[97] + tmp[53]*tmp[95] + tmp[58]*tmp[98] - tmp[63]*tmp[93] - tmp[90];
	tmp[100] = P[39]*dt;
	tmp[101] = P[36] + tmp[100];
	tmp[102] = dt*tmp[101];
	tmp[103] = -tmp[45] - tmp[75] + tmp[92];
	tmp[104] = tmp[34]*tmp[3];
	tmp[105] = tmp[104]*tmp[8] + tmp[10]*tmp[89] + tmp[54] + tmp[82];
	tmp[106] = X[7]*X[9]*tmp[34]*tmp[8] - tmp[104]*tmp[6] - tmp[48] - tmp[50];
	tmp[107] = -tmp[10]*tmp[34]*tmp[3] + tmp[11] + tmp[60] + tmp[96];
	tmp[108] = -tmp[107];
	tmp[109] = X[6]*tmp[108]*tmp[5] + X[7]*X[9]*tmp[18]*tmp[34] + X[8]*tmp[103]*tmp[5] - tmp[105]*tmp[47] - tmp[106]*tmp[63] - tmp[12]*tmp[36] - tmp[14]*tmp[89] + tmp[16]*tmp[34]*tmp[3] - tmp[17];
	tmp[110] = P[48]*dt;
	tmp[111] = P[45] + tmp[110];
	tmp[112] = dt*tmp[111];
	tmp[113] = 1.0/tmp[4];
	tmp[114] = tmp[113]*tmp[1];
	tmp[115] = tmp[113]*tmp[2];
	tmp[116] = -tmp[115];
	tmp[117] = tmp[0]*tmp[113];
	tmp[118] = tmp[113]*tmp[3];
	tmp[119] = tmp[117] - tmp[118];
	tmp[120] = -tmp[114] - tmp[116] - tmp[119];
	tmp[121] = P[58]*dt;
	tmp[122] = P[55] + tmp[121];
	tmp[123] = dt*tmp[122];
	tmp[124] = 2*tmp[113];
	tmp[125] = X[6]*tmp[124];
	tmp[126] = X[9]*tmp[125];
	tmp[127] = X[7]*X[8];
	tmp[128] = tmp[124]*tmp[127];
	tmp[129] = tmp[126] - tmp[128];
	tmp[130] = P[69]*dt;
	tmp[131] = P[66] + tmp[130];
	tmp[132] = dt*tmp[131];
	tmp[133] = X[8]*tmp[125];
	tmp[134] = X[7]*X[9];
	tmp[135] = tmp[124]*tmp[134];
	tmp[136] = -tmp[133] - tmp[135];
	tmp[137] = P[81]*dt;
	tmp[138] = P[78] + tmp[137];
	tmp[139] = dt*tmp[138];
	tmp[140] = tmp[14]*tmp[41];
	tmp[141] = tmp[140] - tmp[16]*tmp[40] + tmp[17] + tmp[18]*tmp[38] + tmp[20]*tmp[36] - tmp[46]*tmp[58] - tmp[47]*tmp[57] - tmp[51]*tmp[63] + tmp[53]*tmp[62];
	tmp[142] = tmp[16]*tmp[41];
	tmp[143] = X[6]*tmp[5]*tmp[83] + X[7]*X[8]*tmp[18]*tmp[34] + X[7]*X[9]*tmp[20]*tmp[34] - tmp[142] + tmp[14]*tmp[1]*tmp[34] - tmp[15] - tmp[47]*tmp[81] - tmp[58]*tmp[80] - tmp[63]*tmp[76];
	tmp[144] = X[6]*tmp[5]*tmp[93] + X[8]*X[9]*tmp[20]*tmp[34] - tmp[16]*tmp[38] + tmp[18]*tmp[2]*tmp[34] - tmp[19] - tmp[47]*tmp[98] - tmp[58]*tmp[97] - tmp[63]*tmp[94] + tmp[70];
	tmp[145] = -X[8]*X[9]*tmp[18]*tmp[34];
	tmp[146] = X[6]*tmp[106]*tmp[5] + X[7]*X[9]*tmp[14]*tmp[34] - tmp[103]*tmp[47] - tmp[105]*tmp[58] - tmp[107]*tmp[63] - tmp[145] + tmp[20]*tmp[34]*tmp[3] - tmp[21] - tmp[37];
	tmp[147] = -tmp[126] - tmp[128];
	tmp[148] = -tmp[114];
	tmp[149] = -tmp[115] - tmp[119] - tmp[148];
	tmp[150] = X[7]*tmp[125];
	tmp[151] = tmp[124]*tmp[88];
	tmp[152] = tmp[150] - tmp[151];
	tmp[153] = -tmp[142] - tmp[14]*tmp[40] + tmp[15] + tmp[18]*tmp[36] - tmp[46]*tmp[63] + tmp[47]*tmp[62] - tmp[52]*tmp[58] + tmp[53]*tmp[57] + tmp[90];
	tmp[154] = tmp[12]*tmp[69] - tmp[140] - tmp[16]*tmp[79] + tmp[17] + tmp[18]*tmp[71] + tmp[47]*tmp[83] + tmp[53]*tmp[81] - tmp[58]*tmp[77] - tmp[63]*tmp[80];
	tmp[155] = X[6]*tmp[5]*tmp[98] + X[7]*tmp[5]*tmp[93] + tmp[12]*tmp[2]*tmp[34] - tmp[13] - tmp[145] - tmp[16]*tmp[69] - tmp[39] - tmp[58]*tmp[95] - tmp[63]*tmp[97];
	tmp[156] = X[6]*tmp[103]*tmp[5] + X[7]*tmp[106]*tmp[5] + X[8]*X[9]*tmp[12]*tmp[34] - tmp[105]*tmp[63] - tmp[108]*tmp[58] - tmp[14]*tmp[36] + tmp[18]*tmp[34]*tmp[3] - tmp[19] - tmp[72];
	tmp[157] = tmp[133] - tmp[135];
	tmp[158] = -tmp[150] - tmp[151];
	tmp[159] = -tmp[116] - tmp[117] - tmp[118] - tmp[148];
	tmp[160] = 0.5*U[3] - 0.5*X[13];
	tmp[161] = -tmp[160];
	tmp[162] = 0.5*U[4] - 0.5*X[14];
	tmp[163] = -tmp[162];
	tmp[164] = 0.5*U[5] - 0.5*X[15];
	tmp[165] = -tmp[164];
	tmp[166] = P[91] + P[94]*dt;
	tmp[167] = dt*tmp[166];
	tmp[168] = P[105] + P[108]*dt;
	tmp[169] = dt*tmp[168];
	tmp[170] = P[120] + P[123]*dt;
	tmp[171] = dt*tmp[170];
	tmp[172] = P[11] + P[14]*dt;
	tmp[173] = P[19]*dt;
	tmp[174] = P[16] + tmp[173];
	tmp[175] = P[70]*dt;
	tmp[176] = P[67] + tmp[175];
	tmp[177] = dt*tmp[176];
	tmp[178] = P[82]*dt;
	tmp[179] = P[79] + tmp[178];
	tmp[180] = dt*tmp[179];
	tmp[181] = P[59]*dt;
	tmp[182] = P[56] + tmp[181];
	tmp[183] = dt*tmp[182];
	tmp[184] = P[25]*dt;
	tmp[185] = P[22] + tmp[184];
	tmp[186] = dt*tmp[185];
	tmp[187] = P[40]*dt;
	tmp[188] = P[37] + tmp[187];
	tmp[189] = dt*tmp[188];
	tmp[190] = P[49]*dt;
	tmp[191] = P[46] + tmp[190];
	tmp[192] = dt*tmp[191];
	tmp[193] = P[32]*dt;
	tmp[194] = P[29] + tmp[193];
	tmp[195] = dt*tmp[194];
	tmp[196] = P[92] + P[95]*dt;
	tmp[197] = dt*tmp[196];
	tmp[198] = P[106] + P[109]*dt;
	tmp[199] = dt*tmp[198];
	tmp[200] = P[121] + P[124]*dt;
	tmp[201] = dt*tmp[200];
	tmp[202] = P[17] + P[20]*dt;
	tmp[203] = P[71]*dt;
	tmp[204] = P[68] + tmp[203];
	tmp[205] = dt*tmp[204];
	tmp[206] = P[83]*dt;
	tmp[207] = P[80] + tmp[206];
	tmp[208] = dt*tmp[207];
	tmp[209] = P[60]*dt;
	tmp[210] = P[57] + tmp[209];
	tmp[211] = dt*tmp[210];
	tmp[212] = P[26]*dt;
	tmp[213] = P[23] + tmp[212];
	tmp[214] = dt*tmp[213];
	tmp[215] = P[41]*dt;
	tmp[216] = P[38] + tmp[215];
	tmp[217] = dt*tmp[216];
	tmp[218] = P[50]*dt;
	tmp[219] = P[47] + tmp[218];
	tmp[220] = dt*tmp[219];
	tmp[221] = P[33]*dt;
	tmp[222] = P[30] + tmp[221];
	tmp[223] = dt*tmp[222];
	tmp[224] = P[93] + P[96]*dt;
	tmp[225] = dt*tmp[224];
	tmp[226] = P[107] + P[110]*dt;
	tmp[227] = dt*tmp[226];
	tmp[228] = P[122] + P[125]*dt;
	tmp[229] = dt*tmp[228];
	tmp[230] = powf(dt, 2);
	tmp[231] = Q[1]*tmp[230];
	tmp[232] = Q[2]*tmp[230];
	tmp[233] = Q[0]*tmp[230];
	tmp[234] = dt*tmp[129];
	tmp[235] = dt*tmp[136];
	tmp[236] = dt*tmp[120];
	tmp[237] = dt*tmp[64];
	tmp[238] = dt*tmp[99];
	tmp[239] = dt*tmp[109];
	tmp[240] = dt*tmp[84];
	tmp[241] = P[81] + P[84]*tmp[237] + P[85]*tmp[240] + P[86]*tmp[238] + P[87]*tmp[239] + P[88]*tmp[236] + P[89]*tmp[234] + P[90]*tmp[235];
	tmp[242] = P[69] + P[72]*tmp[237] + P[73]*tmp[240] + P[74]*tmp[238] + P[75]*tmp[239] + P[76]*tmp[236] + P[77]*tmp[234] + P[89]*tmp[235];
	tmp[243] = P[58] + P[61]*tmp[237] + P[62]*tmp[240] + P[63]*tmp[238] + P[64]*tmp[239] + P[65]*tmp[236] + P[76]*tmp[234] + P[88]*tmp[235];
	tmp[244] = P[24] + P[27]*tmp[237] + P[34]*tmp[240] + P[42]*tmp[238] + P[51]*tmp[239] + P[61]*tmp[236] + P[72]*tmp[234] + P[84]*tmp[235];
	tmp[245] = P[39] + P[42]*tmp[237] + P[43]*tmp[240] + P[44]*tmp[238] + P[53]*tmp[239] + P[63]*tmp[236] + P[74]*tmp[234] + P[86]*tmp[235];
	tmp[246] = P[48] + P[51]*tmp[237] + P[52]*tmp[240] + P[53]*tmp[238] + P[54]*tmp[239] + P[64]*tmp[236] + P[75]*tmp[234] + P[87]*tmp[235];
	tmp[247] = P[31] + P[34]*tmp[237] + P[35]*tmp[240] + P[43]*tmp[238] + P[52]*tmp[239] + P[62]*tmp[236] + P[73]*tmp[234] + P[85]*tmp[235];
	tmp[248] = tmp[136]*tmp[232];
	tmp[249] = tmp[120]*tmp[233];
	tmp[250] = tmp[129]*tmp[231];
	tmp[251] = dt*tmp[241];
	tmp[252] = dt*tmp[243];
	tmp[253] = dt*tmp[242];
	tmp[254] = dt*tmp[244];
	tmp[255] = dt*tmp[247];
	tmp[256] = dt*tmp[246];
	tmp[257] = dt*tmp[245];
	tmp[258] = P[100]*tmp[239] + P[101]*tmp[236] + P[102]*tmp[234] + P[103]*tmp[235] + P[94] + P[97]*tmp[237] + P[98]*tmp[240] + P[99]*tmp[238];
	tmp[259] = dt*tmp[258];
	tmp[260] = P[108] + P[111]*tmp[237] + P[112]*tmp[240] + P[113]*tmp[238] + P[114]*tmp[239] + P[115]*tmp[236] + P[116]*tmp[234] + P[117]*tmp[235];
	tmp[261] = dt*tmp[260];
	tmp[262] = P[123] + P[126]*tmp[237] + P[127]*tmp[240] + P[128]*tmp[238] + P[129]*tmp[239] + P[130]*tmp[236] + P[131]*tmp[234] + P[132]*tmp[235];
	tmp[263] = dt*tmp[262];
	tmp[264] = dt*tmp[147];
	tmp[265] = dt*tmp[152];
	tmp[266] = dt*tmp[149];
	tmp[267] = dt*tmp[141];
	tmp[268] = dt*tmp[143];
	tmp[269] = dt*tmp[146];
	tmp[270] = dt*tmp[144];
	tmp[271] = P[82] + P[84]*tmp[267] + P[85]*tmp[268] + P[86]*tmp[270] + P[87]*tmp[269] + P[88]*tmp[264] + P[89]*tmp[266] + P[90]*tmp[265];
	tmp[272] = P[59] + P[61]*tmp[267] + P[62]*tmp[268] + P[63]*tmp[270] + P[64]*tmp[269] + P[65]*tmp[264] + P[76]*tmp[266] + P[88]*tmp[265];
	tmp[273] = P[70] + P[72]*tmp[267] + P[73]*tmp[268] + P[74]*tmp[270] + P[75]*tmp[269] + P[76]*tmp[264] + P[77]*tmp[266] + P[89]*tmp[265];
	tmp[274] = P[25] + P[27]*tmp[267] + P[34]*tmp[268] + P[42]*tmp[270] + P[51]*tmp[269] + P[61]*tmp[264] + P[72]*tmp[266] + P[84]*tmp[265];
	tmp[275] = P[32] + P[34]*tmp[267] + P[35]*tmp[268] + P[43]*tmp[270] + P[52]*tmp[269] + P[62]*tmp[264] + P[73]*tmp[266] + P[85]*tmp[265];
	tmp[276] = P[49] + P[51]*tmp[267] + P[52]*tmp[268] + P[53]*tmp[270] + P[54]*tmp[269] + P[64]*tmp[264] + P[75]*tmp[266] + P[87]*tmp[265];
	tmp[277] = P[40] + P[42]*tmp[267] + P[43]*tmp[268] + P[44]*tmp[270] + P[53]*tmp[269] + P[63]*tmp[264] + P[74]*tmp[266] + P[86]*tmp[265];
	tmp[278] = dt*tmp[158];
	tmp[279] = dt*tmp[157];
	tmp[280] = dt*tmp[159];
	tmp[281] = dt*tmp[274];
	tmp[282] = dt*tmp[275];
	tmp[283] = dt*tmp[277];
	tmp[284] = dt*tmp[276];
	tmp[285] = P[100]*tmp[269] + P[101]*tmp[264] + P[102]*tmp[266] + P[103]*tmp[265] + P[95] + P[97]*tmp[267] + P[98]*tmp[268] + P[99]*tmp[270];
	tmp[286] = dt*tmp[285];
	tmp[287] = P[109] + P[111]*tmp[267] + P[112]*tmp[268] + P[113]*tmp[270] + P[114]*tmp[269] + P[115]*tmp[264] + P[116]*tmp[266] + P[117]*tmp[265];
	tmp[288] = dt*tmp[287];
	tmp[289] = P[124] + P[126]*tmp[267] + P[127]*tmp[268] + P[128]*tmp[270] + P[129]*tmp[269] + P[130]*tmp[264] + P[131]*tmp[266] + P[132]*tmp[265];
	tmp[290] = dt*tmp[289];
	tmp[291] = dt*tmp[153];
	tmp[292] = dt*tmp[154];
	tmp[293] = dt*tmp[155];
	tmp[294] = dt*tmp[156];
	tmp[295] = P[71] + P[72]*tmp[291] + P[73]*tmp[292] + P[74]*tmp[293] + P[75]*tmp[294] + P[76]*tmp[279] + P[77]*tmp[278] + P[89]*tmp[280];
	tmp[296] = P[60] + P[61]*tmp[291] + P[62]*tmp[292] + P[63]*tmp[293] + P[64]*tmp[294] + P[65]*tmp[279] + P[76]*tmp[278] + P[88]*tmp[280];
	tmp[297] = P[83] + P[84]*tmp[291] + P[85]*tmp[292] + P[86]*tmp[293] + P[87]*tmp[294] + P[88]*tmp[279] + P[89]*tmp[278] + P[90]*tmp[280];
	tmp[298] = P[26] + P[27]*tmp[291] + P[34]*tmp[292] + P[42]*tmp[293] + P[51]*tmp[294] + P[61]*tmp[279] + P[72]*tmp[278] + P[84]*tmp[280];
	tmp[299] = P[33] + P[34]*tmp[291] + P[35]*tmp[292] + P[43]*tmp[293] + P[52]*tmp[294] + P[62]*tmp[279] + P[73]*tmp[278] + P[85]*tmp[280];
	tmp[300] = P[41] + P[42]*tmp[291] + P[43]*tmp[292] + P[44]*tmp[293] + P[53]*tmp[294] + P[63]*tmp[279] + P[74]*tmp[278] + P[86]*tmp[280];
	tmp[301] = P[50] + P[51]*tmp[291] + P[52]*tmp[292] + P[53]*tmp[293] + P[54]*tmp[294] + P[64]*tmp[279] + P[75]*tmp[278] + P[87]*tmp[280];
	tmp[302] = dt*tmp[299];
	tmp[303] = dt*tmp[300];
	tmp[304] = dt*tmp[301];
	tmp[305] = P[100]*tmp[294] + P[101]*tmp[279] + P[102]*tmp[278] + P[103]*tmp[280] + P[96] + P[97]*tmp[291] + P[98]*tmp[292] + P[99]*tmp[293];
	tmp[306] = dt*tmp[305];
	tmp[307] = P[110] + P[111]*tmp[291] + P[112]*tmp[292] + P[113]*tmp[293] + P[114]*tmp[294] + P[115]*tmp[279] + P[116]*tmp[278] + P[117]*tmp[280];
	tmp[308] = dt*tmp[307];
	tmp[309] = P[125] + P[126]*tmp[291] + P[127]*tmp[292] + P[128]*tmp[293] + P[129]*tmp[294] + P[130]*tmp[279] + P[131]*tmp[278] + P[132]*tmp[280];
	tmp[310] = dt*tmp[309];
	tmp[311] = dt*tmp[298];
	tmp[312] = dt*tmp[24];
	tmp[313] = dt*tmp[26];
	tmp[314] = dt*tmp[28];
	tmp[315] = dt*tmp[161];
	tmp[316] = dt*tmp[163];
	tmp[317] = dt*tmp[165];
	tmp[318] = P[52]*tmp[317];
	tmp[319] = P[112]*tmp[312] + P[127]*tmp[313] + P[34] + P[35]*tmp[315] + P[43]*tmp[316] + P[98]*tmp[314] + tmp[318];
	tmp[320] = P[43]*tmp[315];
	tmp[321] = P[113]*tmp[312] + P[128]*tmp[313] + P[42] + P[44]*tmp[316] + P[53]*tmp[317] + P[99]*tmp[314] + tmp[320];
	tmp[322] = P[53]*tmp[316];
	tmp[323] = P[100]*tmp[314] + P[114]*tmp[312] + P[129]*tmp[313] + P[51] + P[52]*tmp[315] + P[54]*tmp[317] + tmp[322];
	tmp[324] = 0.25*tmp[230];
	tmp[325] = Q[3]*tmp[324];
	tmp[326] = Q[4]*tmp[324];
	tmp[327] = Q[5]*tmp[324];
	tmp[328] = P[118]*tmp[312];
	tmp[329] = P[133]*tmp[313];
	tmp[330] = P[100]*tmp[317] + P[104]*tmp[314] + P[97] + P[98]*tmp[315] + P[99]*tmp[316] + tmp[328] + tmp[329];
	tmp[331] = P[118]*tmp[314];
	tmp[332] = P[134]*tmp[313];
	tmp[333] = P[111] + P[112]*tmp[315] + P[113]*tmp[316] + P[114]*tmp[317] + P[119]*tmp[312] + tmp[331] + tmp[332];
	tmp[334] = P[133]*tmp[314];
	tmp[335] = P[134]*tmp[312];
	tmp[336] = P[126] + P[127]*tmp[315] + P[128]*tmp[316] + P[129]*tmp[317] + P[135]*tmp[313] + tmp[334] + tmp[335];
	tmp[337] = P[111]*tmp[312] + P[126]*tmp[313] + P[27] + P[34]*tmp[315] + P[42]*tmp[316] + P[51]*tmp[317] + P[97]*tmp[314];
	tmp[338] = dt*tmp[160];
	tmp[339] = dt*tmp[164];
	tmp[340] = dt*tmp[27];
	tmp[341] = X[6]*tmp[325];
	tmp[342] = dt*tmp[162];
	tmp[343] = X[6]*tmp[326];
	tmp[344] = X[6]*tmp[327];
	tmp[345] = P[42]*tmp[339];
	tmp[346] = P[111]*tmp[313] - P[126]*tmp[312] + P[27]*tmp[338] + P[34] + P[51]*tmp[316] - P[97]*tmp[340] + tmp[345];
	tmp[347] = P[113]*tmp[313] - P[128]*tmp[312] + P[42]*tmp[338] + P[43] + P[44]*tmp[339] - P[99]*tmp[340] + tmp[322];
	tmp[348] = P[51]*tmp[338];
	tmp[349] = -P[100]*tmp[340] + P[114]*tmp[313] - P[129]*tmp[312] + P[52] + P[53]*tmp[339] + P[54]*tmp[316] + tmp[348];
	tmp[350] = -P[118]*tmp[340];
	tmp[351] = P[111]*tmp[338] + P[112] + P[113]*tmp[339] + P[114]*tmp[316] + P[119]*tmp[313] - tmp[335] + tmp[350];
	tmp[352] = P[118]*tmp[313];
	tmp[353] = P[133]*tmp[312];
	tmp[354] = P[100]*tmp[316] - P[104]*tmp[340] + P[97]*tmp[338] + P[98] + P[99]*tmp[339] + tmp[352] - tmp[353];
	tmp[355] = -P[133]*tmp[340];
	tmp[356] = P[126]*tmp[338] + P[127] + P[128]*tmp[339] + P[129]*tmp[316] - P[135]*tmp[312] + tmp[332] + tmp[355];
	tmp[357] = P[112]*tmp[313] - P[127]*tmp[312] + P[34]*tmp[338] + P[35] + P[43]*tmp[339] + P[52]*tmp[316] - P[98]*tmp[340];
	tmp[358] = -P[100]*tmp[313] - P[114]*tmp[340] + P[129]*tmp[314] + P[51]*tmp[342] + P[53] + P[54]*tmp[338] + tmp[318];
	tmp[359] = -P[111]*tmp[340] + P[126]*tmp[314] + P[27]*tmp[342] + P[34]*tmp[317] + P[42] - P[97]*tmp[313] + tmp[348];
	tmp[360] = P[34]*tmp[342];
	tmp[361] = -P[112]*tmp[340] + P[127]*tmp[314] + P[35]*tmp[317] + P[43] + P[52]*tmp[338] - P[98]*tmp[313] + tmp[360];
	tmp[362] = -P[134]*tmp[340];
	tmp[363] = P[126]*tmp[342] + P[127]*tmp[317] + P[128] + P[129]*tmp[338] + P[135]*tmp[314] - tmp[329] + tmp[362];
	tmp[364] = P[134]*tmp[314];
	tmp[365] = P[111]*tmp[342] + P[112]*tmp[317] + P[113] + P[114]*tmp[338] - P[119]*tmp[340] - tmp[352] + tmp[364];
	tmp[366] = P[100]*tmp[338] - P[104]*tmp[313] + P[97]*tmp[342] + P[98]*tmp[317] + P[99] + tmp[334] + tmp[350];
	tmp[367] = -P[113]*tmp[340] + P[128]*tmp[314] + P[42]*tmp[342] + P[43]*tmp[317] + P[44] + P[53]*tmp[338] - P[99]*tmp[313];
	tmp[368] = P[126]*tmp[339] + P[127]*tmp[342] + P[128]*tmp[315] + P[129] - P[135]*tmp[340] + tmp[353] - tmp[364];
	tmp[369] = P[111]*tmp[339] + P[112]*tmp[342] + P[113]*tmp[315] + P[114] - P[119]*tmp[314] + tmp[328] + tmp[362];
	tmp[370] = P[100] + P[104]*tmp[312] + P[97]*tmp[339] + P[98]*tmp[342] + P[99]*tmp[315] - tmp[331] + tmp[355];
	X_new[0] = X[0] + X[3]*dt;
	X_new[1] = X[1] + X[4]*dt;
	X_new[2] = X[2] + X[5]*dt;
	X_new[3] = X[3] + dt*(X[6]*tmp[13] - X[7]*tmp[19] + X[8]*tmp[15] - X[9]*tmp[17]);
	X_new[4] = X[4] + dt*(X[6]*tmp[16]*tmp[5] - X[7]*tmp[15] - X[8]*tmp[19] - X[9]*tmp[21]);
	X_new[5] = X[5] + dt*(X[6]*tmp[15] + X[7]*tmp[17] - X[8]*tmp[13] - X[9]*tmp[19] + 9.8100000000000005);
	X_new[6] = X[6] + dt*(-X[7]*tmp[22] - tmp[23]*tmp[24] - tmp[25]*tmp[26]);
	X_new[7] = X[7] + dt*(X[6]*tmp[22] - tmp[23]*tmp[26] + tmp[24]*tmp[25]);
	X_new[8] = X[8] + dt*(X[9]*tmp[22] + tmp[23]*tmp[27] - tmp[25]*tmp[28]);
	X_new[9] = X[9] + dt*(-X[8]*tmp[22] + tmp[23]*tmp[28] + tmp[25]*tmp[27]);
	X_new[10] = X[10];
	X_new[11] = X[11];
	X_new[12] = X[12];
	X_new[13] = X[13];
	X_new[14] = X[14];
	X_new[15] = X[15];
	P_new[0] = P[0] + P[6]*dt + dt*tmp[29];
	P_new[1] = P[1] + P[7]*dt + dt*tmp[31];
	P_new[3] = P[3] + P[8]*dt + dt*tmp[33];
	P_new[6] = tmp[102]*tmp[99] + tmp[109]*tmp[112] + tmp[120]*tmp[123] + tmp[129]*tmp[132] + tmp[136]*tmp[139] + tmp[29] + tmp[64]*tmp[67] + tmp[84]*tmp[87];
	P_new[10] = tmp[102]*tmp[144] + tmp[112]*tmp[146] + tmp[123]*tmp[147] + tmp[132]*tmp[149] + tmp[139]*tmp[152] + tmp[141]*tmp[67] + tmp[143]*tmp[87] + tmp[31];
	P_new[15] = tmp[102]*tmp[155] + tmp[112]*tmp[156] + tmp[123]*tmp[157] + tmp[132]*tmp[158] + tmp[139]*tmp[159] + tmp[153]*tmp[67] + tmp[154]*tmp[87] + tmp[33];
	P_new[21] = tmp[102]*tmp[163] + tmp[112]*tmp[165] + tmp[161]*tmp[87] + tmp[167]*tmp[28] + tmp[169]*tmp[24] + tmp[171]*tmp[26] + tmp[66];
	P_new[28] = tmp[102]*tmp[164] + tmp[112]*tmp[163] + tmp[160]*tmp[67] - tmp[167]*tmp[27] + tmp[169]*tmp[26] - tmp[171]*tmp[24] + tmp[86];
	P_new[36] = tmp[101] + tmp[112]*tmp[160] + tmp[162]*tmp[67] + tmp[165]*tmp[87] - tmp[167]*tmp[26] - tmp[169]*tmp[27] + tmp[171]*tmp[28];
	P_new[45] = tmp[102]*tmp[161] + tmp[111] + tmp[162]*tmp[87] + tmp[164]*tmp[67] + tmp[167]*tmp[24] - tmp[169]*tmp[28] - tmp[171]*tmp[27];
	P_new[55] = tmp[122];
	P_new[66] = tmp[131];
	P_new[78] = tmp[138];
	P_new[91] = tmp[166];
	P_new[105] = tmp[168];
	P_new[120] = tmp[170];
	P_new[2] = P[11]*dt + P[2] + dt*tmp[172];
	P_new[4] = P[12]*dt + P[4] + dt*tmp[174];
	P_new[7] = P[7] + tmp[109]*tmp[192] + tmp[120]*tmp[183] + tmp[129]*tmp[177] + tmp[136]*tmp[180] + tmp[186]*tmp[64] + tmp[189]*tmp[99] + tmp[195]*tmp[84] + tmp[30];
	P_new[11] = tmp[141]*tmp[186] + tmp[143]*tmp[195] + tmp[144]*tmp[189] + tmp[146]*tmp[192] + tmp[147]*tmp[183] + tmp[149]*tmp[177] + tmp[152]*tmp[180] + tmp[172];
	P_new[16] = tmp[153]*tmp[186] + tmp[154]*tmp[195] + tmp[155]*tmp[189] + tmp[156]*tmp[192] + tmp[157]*tmp[183] + tmp[158]*tmp[177] + tmp[159]*tmp[180] + tmp[174];
	P_new[22] = tmp[161]*tmp[195] + tmp[163]*tmp[189] + tmp[165]*tmp[192] + tmp[185] + tmp[197]*tmp[28] + tmp[199]*tmp[24] + tmp[201]*tmp[26];
	P_new[29] = tmp[160]*tmp[186] + tmp[163]*tmp[192] + tmp[164]*tmp[189] + tmp[194] - tmp[197]*tmp[27] + tmp[199]*tmp[26] - tmp[201]*tmp[24];
	P_new[37] = tmp[160]*tmp[192] + tmp[162]*tmp[186] + tmp[165]*tmp[195] + tmp[188] - tmp[197]*tmp[26] - tmp[199]*tmp[27] + tmp[201]*tmp[28];
	P_new[46] = tmp[161]*tmp[189] + tmp[162]*tmp[195] + tmp[164]*tmp[186] + tmp[191] + tmp[197]*tmp[24] - tmp[199]*tmp[28] - tmp[201]*tmp[27];
	P_new[56] = tmp[182];
	P_new[67] = tmp[176];
	P_new[79] = tmp[179];
	P_new[92] = tmp[196];
	P_new[106] = tmp[198];
	P_new[121] = tmp[200];
	P_new[5] = P[17]*dt + P[5] + dt*tmp[202];
	P_new[8] = P[8] + tmp[109]*tmp[220] + tmp[120]*tmp[211] + tmp[129]*tmp[205] + tmp[136]*tmp[208] + tmp[214]*tmp[64] + tmp[217]*tmp[99] + tmp[223]*tmp[84] + tmp[32];
	P_new[12] = P[12] + tmp[141]*tmp[214] + tmp[143]*tmp[223] + tmp[144]*tmp[217] + tmp[146]*tmp[220] + tmp[147]*tmp[211] + tmp[149]*tmp[205] + tmp[152]*tmp[208] + tmp[173];
	P_new[17] = tmp[153]*tmp[214] + tmp[154]*tmp[223] + tmp[155]*tmp[217] + tmp[156]*tmp[220] + tmp[157]*tmp[211] + tmp[158]*tmp[205] + tmp[159]*tmp[208] + tmp[202];
	P_new[23] = tmp[161]*tmp[223] + tmp[163]*tmp[217] + tmp[165]*tmp[220] + tmp[213] + tmp[225]*tmp[28] + tmp[227]*tmp[24] + tmp[229]*tmp[26];
	P_new[30] = tmp[160]*tmp[214] + tmp[163]*tmp[220] + tmp[164]*tmp[217] + tmp[222] - tmp[225]*tmp[27] + tmp[227]*tmp[26] - tmp[229]*tmp[24];
	P_new[38] = tmp[160]*tmp[220] + tmp[162]*tmp[214] + tmp[165]*tmp[223] + tmp[216] - tmp[225]*tmp[26] - tmp[227]*tmp[27] + tmp[229]*tmp[28];
	P_new[47] = tmp[161]*tmp[217] + tmp[162]*tmp[223] + tmp[164]*tmp[214] + tmp[219] + tmp[225]*tmp[24] - tmp[227]*tmp[28] - tmp[229]*tmp[27];
	P_new[57] = tmp[210];
	P_new[68] = tmp[204];
	P_new[80] = tmp[207];
	P_new[93] = tmp[224];
	P_new[107] = tmp[226];
	P_new[122] = tmp[228];
	P_new[9] = P[9] + tmp[100]*tmp[99] + tmp[109]*tmp[110] + powf(tmp[120], 2)*tmp[233] + tmp[120]*tmp[121] + powf(tmp[129], 2)*tmp[231] + tmp[129]*tmp[130] + powf(tmp[136], 2)*tmp[232] + tmp[136]*tmp[137] + tmp[234]*tmp[242] + tmp[235]*tmp[241] + tmp[236]*tmp[243] + tmp[237]*tmp[244] + tmp[238]*tmp[245] + tmp[239]*tmp[246] + tmp[240]*tmp[247] + tmp[64]*tmp[65] + tmp[84]*tmp[85];
	P_new[13] = P[13] + tmp[109]*tmp[190] + tmp[120]*tmp[181] + tmp[129]*tmp[175] + tmp[136]*tmp[178] + tmp[141]*tmp[254] + tmp[143]*tmp[255] + tmp[144]*tmp[257] + tmp[146]*tmp[256] + tmp[147]*tmp[249] + tmp[147]*tmp[252] + tmp[149]*tmp[250] + tmp[149]*tmp[253] + tmp[152]*tmp[248] + tmp[152]*tmp[251] + tmp[184]*tmp[64] + tmp[187]*tmp[99] + tmp[193]*tmp[84];
	P_new[18] = P[18] + tmp[109]*tmp[218] + tmp[120]*tmp[209] + tmp[129]*tmp[203] + tmp[136]*tmp[206] + tmp[153]*tmp[254] + tmp[154]*tmp[255] + tmp[155]*tmp[257] + tmp[156]*tmp[256] + tmp[157]*tmp[249] + tmp[157]*tmp[252] + tmp[158]*tmp[250] + tmp[158]*tmp[253] + tmp[159]*tmp[248] + tmp[159]*tmp[251] + tmp[212]*tmp[64] + tmp[215]*tmp[99] + tmp[221]*tmp[84];
	P_new[24] = tmp[161]*tmp[255] + tmp[163]*tmp[257] + tmp[165]*tmp[256] + tmp[244] + tmp[24]*tmp[261] + tmp[259]*tmp[28] + tmp[263]*tmp[26];
	P_new[31] = tmp[160]*tmp[254] + tmp[163]*tmp[256] + tmp[164]*tmp[257] + tmp[247] - tmp[24]*tmp[263] - tmp[259]*tmp[27] + tmp[261]*tmp[26];
	P_new[39] = tmp[160]*tmp[256] + tmp[162]*tmp[254] + tmp[165]*tmp[255] + tmp[245] - tmp[259]*tmp[26] - tmp[261]*tmp[27] + tmp[263]*tmp[28];
	P_new[48] = tmp[161]*tmp[257] + tmp[162]*tmp[255] + tmp[164]*tmp[254] + tmp[246] + tmp[24]*tmp[259] - tmp[261]*tmp[28] - tmp[263]*tmp[27];
	P_new[58] = tmp[243];
	P_new[69] = tmp[242];
	P_new[81] = tmp[241];
	P_new[94] = tmp[258];
	P_new[108] = tmp[260];
	P_new[123] = tmp[262];
	P_new[14] = P[14] + tmp[141]*tmp[184] + tmp[143]*tmp[193] + tmp[144]*tmp[187] + tmp[146]*tmp[190] + powf(tmp[147], 2)*tmp[233] + tmp[147]*tmp[181] + powf(tmp[149], 2)*tmp[231] + tmp[149]*tmp[175] + powf(tmp[152], 2)*tmp[232] + tmp[152]*tmp[178] + tmp[264]*tmp[272] + tmp[265]*tmp[271] + tmp[266]*tmp[273] + tmp[267]*tmp[274] + tmp[268]*tmp[275] + tmp[269]*tmp[276] + tmp[270]*tmp[277];
	P_new[19] = P[19] + tmp[141]*tmp[212] + tmp[143]*tmp[221] + tmp[144]*tmp[215] + tmp[146]*tmp[218] + tmp[147]*tmp[157]*tmp[233] + tmp[147]*tmp[209] + tmp[149]*tmp[158]*tmp[231] + tmp[149]*tmp[203] + tmp[152]*tmp[159]*tmp[232] + tmp[152]*tmp[206] + tmp[153]*tmp[281] + tmp[154]*tmp[282] + tmp[155]*tmp[283] + tmp[156]*tmp[284] + tmp[271]*tmp[280] + tmp[272]*tmp[279] + tmp[273]*tmp[278];
	P_new[25] = tmp[161]*tmp[282] + tmp[163]*tmp[283] + tmp[165]*tmp[284] + tmp[24]*tmp[288] + tmp[26]*tmp[290] + tmp[274] + tmp[286]*tmp[28];
	P_new[32] = tmp[160]*tmp[281] + tmp[163]*tmp[284] + tmp[164]*tmp[283] - tmp[24]*tmp[290] + tmp[26]*tmp[288] + tmp[275] - tmp[27]*tmp[286];
	P_new[40] = tmp[160]*tmp[284] + tmp[162]*tmp[281] + tmp[165]*tmp[282] - tmp[26]*tmp[286] + tmp[277] - tmp[27]*tmp[288] + tmp[28]*tmp[290];
	P_new[49] = tmp[161]*tmp[283] + tmp[162]*tmp[282] + tmp[164]*tmp[281] + tmp[24]*tmp[286] + tmp[276] - tmp[27]*tmp[290] - tmp[288]*tmp[28];
	P_new[59] = tmp[272];
	P_new[70] = tmp[273];
	P_new[82] = tmp[271];
	P_new[95] = tmp[285];
	P_new[109] = tmp[287];
	P_new[124] = tmp[289];
	P_new[20] = P[20] + tmp[153]*tmp[212] + tmp[154]*tmp[221] + tmp[155]*tmp[215] + tmp[156]*tmp[218] + powf(tmp[157], 2)*tmp[233] + tmp[157]*tmp[209] + powf(tmp[158], 2)*tmp[231] + tmp[158]*tmp[203] + powf(tmp[159], 2)*tmp[232] + tmp[159]*tmp[206] + tmp[278]*tmp[295] + tmp[279]*tmp[296] + tmp[280]*tmp[297] + tmp[291]*tmp[298] + tmp[292]*tmp[299] + tmp[293]*tmp[300] + tmp[294]*tmp[301];
	P_new[26] = tmp[161]*tmp[302] + tmp[163]*tmp[303] + tmp[165]*tmp[304] + tmp[24]*tmp[308] + tmp[26]*tmp[310] + tmp[28]*tmp[306] + tmp[298];
	P_new[33] = tmp[160]*tmp[311] + tmp[163]*tmp[304] + tmp[164]*tmp[303] - tmp[24]*tmp[310] + tmp[26]*tmp[308] - tmp[27]*tmp[306] + tmp[299];
	P_new[41] = tmp[160]*tmp[304] + tmp[162]*tmp[311] + tmp[165]*tmp[302] - tmp[26]*tmp[306] - tmp[27]*tmp[308] + tmp[28]*tmp[310] + tmp[300];
	P_new[50] = tmp[161]*tmp[303] + tmp[162]*tmp[302] + tmp[164]*tmp[311] + tmp[24]*tmp[306] - tmp[27]*tmp[310] - tmp[28]*tmp[308] + tmp[301];
	P_new[60] = tmp[296];
	P_new[71] = tmp[295];
	P_new[83] = tmp[297];
	P_new[96] = tmp[305];
	P_new[110] = tmp[307];
	P_new[125] = tmp[309];
	P_new[27] = tmp[1]*tmp[325] + tmp[2]*tmp[326] + tmp[312]*tmp[333] + tmp[313]*tmp[336] + tmp[314]*tmp[330] + tmp[315]*tmp[319] + tmp[316]*tmp[321] + tmp[317]*tmp[323] + tmp[327]*tmp[3] + tmp[337];
	P_new[34] = -X[7]*tmp[341] - tmp[312]*tmp[336] + tmp[313]*tmp[333] + tmp[316]*tmp[323] + tmp[319] + tmp[321]*tmp[339] + tmp[326]*tmp[88] - tmp[327]*tmp[88] - tmp[330]*tmp[340] + tmp[337]*tmp[338];
	P_new[42] = -X[8]*tmp[343] - tmp[134]*tmp[325] + tmp[134]*tmp[327] - tmp[313]*tmp[330] + tmp[314]*tmp[336] + tmp[317]*tmp[319] + tmp[321] + tmp[323]*tmp[338] - tmp[333]*tmp[340] + tmp[337]*tmp[342];
	P_new[51] = -X[9]*tmp[344] + tmp[127]*tmp[325] - tmp[127]*tmp[326] + tmp[312]*tmp[330] - tmp[314]*tmp[333] + tmp[315]*tmp[321] + tmp[319]*tmp[342] + tmp[323] - tmp[336]*tmp[340] + tmp[337]*tmp[339];
	P_new[61] = P[101]*tmp[314] + P[115]*tmp[312] + P[130]*tmp[313] + P[61] + P[62]*tmp[315] + P[63]*tmp[316] + P[64]*tmp[317];
	P_new[72] = P[102]*tmp[314] + P[116]*tmp[312] + P[131]*tmp[313] + P[72] + P[73]*tmp[315] + P[74]*tmp[316] + P[75]*tmp[317];
	P_new[84] = P[103]*tmp[314] + P[117]*tmp[312] + P[132]*tmp[313] + P[84] + P[85]*tmp[315] + P[86]*tmp[316] + P[87]*tmp[317];
	P_new[97] = tmp[330];
	P_new[111] = tmp[333];
	P_new[126] = tmp[336];
	P_new[35] = tmp[0]*tmp[325] + tmp[2]*tmp[327] - tmp[312]*tmp[356] + tmp[313]*tmp[351] + tmp[316]*tmp[349] + tmp[326]*tmp[3] + tmp[338]*tmp[346] + tmp[339]*tmp[347] - tmp[340]*tmp[354] + tmp[357];
	P_new[43] = X[9]*tmp[341] - X[9]*tmp[343] - tmp[127]*tmp[327] - tmp[313]*tmp[354] + tmp[314]*tmp[356] + tmp[317]*tmp[357] + tmp[338]*tmp[349] - tmp[340]*tmp[351] + tmp[342]*tmp[346] + tmp[347];
	P_new[52] = -X[8]*tmp[341] + X[8]*tmp[344] - tmp[134]*tmp[326] + tmp[312]*tmp[354] - tmp[314]*tmp[351] + tmp[315]*tmp[347] + tmp[339]*tmp[346] - tmp[340]*tmp[356] + tmp[342]*tmp[357] + tmp[349];
	P_new[62] = -P[101]*tmp[340] + P[115]*tmp[313] - P[130]*tmp[312] + P[61]*tmp[338] + P[62] + P[63]*tmp[339] + P[64]*tmp[316];
	P_new[73] = -P[102]*tmp[340] + P[116]*tmp[313] - P[131]*tmp[312] + P[72]*tmp[338] + P[73] + P[74]*tmp[339] + P[75]*tmp[316];
	P_new[85] = -P[103]*tmp[340] + P[117]*tmp[313] - P[132]*tmp[312] + P[84]*tmp[338] + P[85] + P[86]*tmp[339] + P[87]*tmp[316];
	P_new[98] = tmp[354];
	P_new[112] = tmp[351];
	P_new[127] = tmp[356];
	P_new[44] = tmp[0]*tmp[326] + tmp[1]*tmp[327] - tmp[313]*tmp[366] + tmp[314]*tmp[363] + tmp[317]*tmp[361] + tmp[325]*tmp[3] + tmp[338]*tmp[358] - tmp[340]*tmp[365] + tmp[342]*tmp[359] + tmp[367];
	P_new[53] = X[7]*tmp[343] - X[7]*tmp[344] + tmp[312]*tmp[366] - tmp[314]*tmp[365] + tmp[315]*tmp[367] - tmp[325]*tmp[88] + tmp[339]*tmp[359] - tmp[340]*tmp[363] + tmp[342]*tmp[361] + tmp[358];
	P_new[63] = -P[101]*tmp[313] - P[115]*tmp[340] + P[130]*tmp[314] + P[61]*tmp[342] + P[62]*tmp[317] + P[63] + P[64]*tmp[338];
	P_new[74] = -P[102]*tmp[313] - P[116]*tmp[340] + P[131]*tmp[314] + P[72]*tmp[342] + P[73]*tmp[317] + P[74] + P[75]*tmp[338];
	P_new[86] = -P[103]*tmp[313] - P[117]*tmp[340] + P[132]*tmp[314] + P[84]*tmp[342] + P[85]*tmp[317] + P[86] + P[87]*tmp[338];
	P_new[99] = tmp[366];
	P_new[113] = tmp[365];
	P_new[128] = tmp[363];
	P_new[54] = P[100]*tmp[312] - P[114]*tmp[314] - P[129]*tmp[340] + P[51]*tmp[339] + P[52]*tmp[342] + P[53]*tmp[315] + P[54] + tmp[0]*tmp[327] + tmp[1]*tmp[326] + tmp[2]*tmp[325] + tmp[312]*tmp[370] - tmp[314]*tmp[369] + tmp[315]*(-P[113]*tmp[314] - P[128]*tmp[340] + P[43]*tmp[342] + P[44]*tmp[315] + P[53] + P[99]*tmp[312] + tmp[345]) + tmp[339]*(-P[111]*tmp[314] - P[126]*tmp[340] + P[27]*tmp[339] + P[42]*tmp[315] + P[51] + P[97]*tmp[312] + tmp[360]) - tmp[340]*tmp[368] + tmp[342]*(-P[112]*tmp[314] - P[127]*tmp[340] + P[34]*tmp[339] + P[35]*tmp[342] + P[52] + P[98]*tmp[312] + tmp[320]);
	P_new[64] = P[101]*tmp[312] - P[115]*tmp[314] - P[130]*tmp[340] + P[61]*tmp[339] + P[62]*tmp[342] + P[63]*tmp[315] + P[64];
	P_new[75] = P[102]*tmp[312] - P[116]*tmp[314] - P[131]*tmp[340] + P[72]*tmp[339] + P[73]*tmp[342] + P[74]*tmp[315] + P[75];
	P_new[87] = P[103]*tmp[312] - P[117]*tmp[314] - P[132]*tmp[340] + P[84]*tmp[339] + P[85]*tmp[342] + P[86]*tmp[315] + P[87];
	P_new[100] = tmp[370];
	P_new[114] = tmp[369];
	P_new[129] = tmp[368];
	P_new[65] = P[65] + Q[6]*tmp[230];
	P_new[76] = P[76];
	P_new[88] = P[88];
	P_new[101] = P[101];
	P_new[115] = P[115];
	P_new[130] = P[130];
	P_new[77] = P[77] + Q[7]*tmp[230];
	P_new[89] = P[89];
	P_new[102] = P[102];
	P_new[116] = P[116];
	P_new[131] = P[131];
	P_new[90] = P[90] + Q[8]*tmp[230];
	P_new[103] = P[103];
	P_new[117] = P[117];
	P_new[132] = P[132];
	P_new[104] = P[104] + Q[9]*tmp[230];
	P_new[118] = P[118];
	P_new[133] = P[133];
	P_new[119] = P[119] + Q[10]*tmp[230];
	P_new[134] = P[134];
	P_new[135] = P[135] + Q[11]*tmp[230];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    normalize_quaternion(X+6);

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_update(float Z[N_MEASUREMENTS]) {
    // prepare gain calculation
    tmp[0] = P[21]*ekf_use_quat;
	tmp[1] = P[28]*ekf_use_quat;
	tmp[2] = P[36]*ekf_use_quat;
	tmp[3] = P[45]*ekf_use_quat;
	tmp[4] = P[22]*ekf_use_quat;
	tmp[5] = P[29]*ekf_use_quat;
	tmp[6] = P[37]*ekf_use_quat;
	tmp[7] = P[46]*ekf_use_quat;
	tmp[8] = P[23]*ekf_use_quat;
	tmp[9] = P[30]*ekf_use_quat;
	tmp[10] = P[38]*ekf_use_quat;
	tmp[11] = P[47]*ekf_use_quat;
	tmp[12] = powf(ekf_use_quat, 2);
	tmp[13] = P[34]*tmp[12];
	tmp[14] = P[42]*tmp[12];
	tmp[15] = P[51]*tmp[12];
	tmp[16] = P[43]*tmp[12];
	tmp[17] = P[52]*tmp[12];
	tmp[18] = P[53]*tmp[12];
	tmp[19] = P[34]*ekf_use_quat;
	tmp[20] = P[42]*ekf_use_quat;
	tmp[21] = P[51]*ekf_use_quat;
	tmp[22] = P[43]*ekf_use_quat;
	tmp[23] = P[52]*ekf_use_quat;
	tmp[24] = P[53]*ekf_use_quat;
	S[0] = P[0] + R[0];
	S[7] = P[1];
	S[14] = P[3];
	S[21] = tmp[0];
	S[28] = tmp[1];
	S[35] = tmp[2];
	S[42] = tmp[3];
	S[1] = P[1];
	S[8] = P[2] + R[1];
	S[15] = P[4];
	S[22] = tmp[4];
	S[29] = tmp[5];
	S[36] = tmp[6];
	S[43] = tmp[7];
	S[2] = P[3];
	S[9] = P[4];
	S[16] = P[5] + R[2];
	S[23] = tmp[8];
	S[30] = tmp[9];
	S[37] = tmp[10];
	S[44] = tmp[11];
	S[3] = tmp[0];
	S[10] = tmp[4];
	S[17] = tmp[8];
	S[24] = P[27]*tmp[12] + R[3];
	S[31] = tmp[13];
	S[38] = tmp[14];
	S[45] = tmp[15];
	S[4] = tmp[1];
	S[11] = tmp[5];
	S[18] = tmp[9];
	S[25] = tmp[13];
	S[32] = P[35]*tmp[12] + R[4];
	S[39] = tmp[16];
	S[46] = tmp[17];
	S[5] = tmp[2];
	S[12] = tmp[6];
	S[19] = tmp[10];
	S[26] = tmp[14];
	S[33] = tmp[16];
	S[40] = P[44]*tmp[12] + R[5];
	S[47] = tmp[18];
	S[6] = tmp[3];
	S[13] = tmp[7];
	S[20] = tmp[11];
	S[27] = tmp[15];
	S[34] = tmp[17];
	S[41] = tmp[18];
	S[48] = P[54]*tmp[12] + R[6];
	HP[0] = P[0];
	HP[1] = P[1];
	HP[2] = P[3];
	HP[3] = tmp[0];
	HP[4] = tmp[1];
	HP[5] = tmp[2];
	HP[6] = tmp[3];
	HP[7] = P[1];
	HP[8] = P[2];
	HP[9] = P[4];
	HP[10] = tmp[4];
	HP[11] = tmp[5];
	HP[12] = tmp[6];
	HP[13] = tmp[7];
	HP[14] = P[3];
	HP[15] = P[4];
	HP[16] = P[5];
	HP[17] = tmp[8];
	HP[18] = tmp[9];
	HP[19] = tmp[10];
	HP[20] = tmp[11];
	HP[21] = P[6];
	HP[22] = P[7];
	HP[23] = P[8];
	HP[24] = P[24]*ekf_use_quat;
	HP[25] = P[31]*ekf_use_quat;
	HP[26] = P[39]*ekf_use_quat;
	HP[27] = P[48]*ekf_use_quat;
	HP[28] = P[10];
	HP[29] = P[11];
	HP[30] = P[12];
	HP[31] = P[25]*ekf_use_quat;
	HP[32] = P[32]*ekf_use_quat;
	HP[33] = P[40]*ekf_use_quat;
	HP[34] = P[49]*ekf_use_quat;
	HP[35] = P[15];
	HP[36] = P[16];
	HP[37] = P[17];
	HP[38] = P[26]*ekf_use_quat;
	HP[39] = P[33]*ekf_use_quat;
	HP[40] = P[41]*ekf_use_quat;
	HP[41] = P[50]*ekf_use_quat;
	HP[42] = P[21];
	HP[43] = P[22];
	HP[44] = P[23];
	HP[45] = P[27]*ekf_use_quat;
	HP[46] = tmp[19];
	HP[47] = tmp[20];
	HP[48] = tmp[21];
	HP[49] = P[28];
	HP[50] = P[29];
	HP[51] = P[30];
	HP[52] = tmp[19];
	HP[53] = P[35]*ekf_use_quat;
	HP[54] = tmp[22];
	HP[55] = tmp[23];
	HP[56] = P[36];
	HP[57] = P[37];
	HP[58] = P[38];
	HP[59] = tmp[20];
	HP[60] = tmp[22];
	HP[61] = P[44]*ekf_use_quat;
	HP[62] = tmp[24];
	HP[63] = P[45];
	HP[64] = P[46];
	HP[65] = P[47];
	HP[66] = tmp[21];
	HP[67] = tmp[23];
	HP[68] = tmp[24];
	HP[69] = P[54]*ekf_use_quat;
	HP[70] = P[55];
	HP[71] = P[56];
	HP[72] = P[57];
	HP[73] = P[61]*ekf_use_quat;
	HP[74] = P[62]*ekf_use_quat;
	HP[75] = P[63]*ekf_use_quat;
	HP[76] = P[64]*ekf_use_quat;
	HP[77] = P[66];
	HP[78] = P[67];
	HP[79] = P[68];
	HP[80] = P[72]*ekf_use_quat;
	HP[81] = P[73]*ekf_use_quat;
	HP[82] = P[74]*ekf_use_quat;
	HP[83] = P[75]*ekf_use_quat;
	HP[84] = P[78];
	HP[85] = P[79];
	HP[86] = P[80];
	HP[87] = P[84]*ekf_use_quat;
	HP[88] = P[85]*ekf_use_quat;
	HP[89] = P[86]*ekf_use_quat;
	HP[90] = P[87]*ekf_use_quat;
	HP[91] = P[91];
	HP[92] = P[92];
	HP[93] = P[93];
	HP[94] = P[97]*ekf_use_quat;
	HP[95] = P[98]*ekf_use_quat;
	HP[96] = P[99]*ekf_use_quat;
	HP[97] = P[100]*ekf_use_quat;
	HP[98] = P[105];
	HP[99] = P[106];
	HP[100] = P[107];
	HP[101] = P[111]*ekf_use_quat;
	HP[102] = P[112]*ekf_use_quat;
	HP[103] = P[113]*ekf_use_quat;
	HP[104] = P[114]*ekf_use_quat;
	HP[105] = P[120];
	HP[106] = P[121];
	HP[107] = P[122];
	HP[108] = P[126]*ekf_use_quat;
	HP[109] = P[127]*ekf_use_quat;
	HP[110] = P[128]*ekf_use_quat;
	HP[111] = P[129]*ekf_use_quat;

    // we have symmetric S and PHT in col major.
    // Solve K as K^T = invS * H*P, as we have columns of HP. We solve columns of K^T, which are actually rows of K
    if (!ekf_use_quat) {
        // 3 state kalman update, yay
        float S_small[3*3];
        for (int i = 0; i < 3; i++) {
            for (int j = 0; j < 3; j++) {
                S_small[i + j*3] = S[i + j*N_MEASUREMENTS];
            }
        }
        float k_row[3];
        float S_small_chol[3*3];
        chol(S_small_chol, S_small, ekf_S_iDiag, 3);
        for (int i = 0; i < N_STATES; i++) {
            chol_solve(S_small_chol, ekf_S_iDiag, 3, (HP+(i*N_MEASUREMENTS)), k_row);
            for (int j = 0; j < 3; j++) {
                K[i + j*N_STATES] = k_row[j];
            }
            for (int j = 3; j < N_MEASUREMENTS; j++) {
                K[i + j*N_STATES] = 0.f;
            }
        }
    } else {
        // full state kalman update, meh
        chol(ekf_S_chol, S, ekf_S_iDiag, N_MEASUREMENTS);
        for (int i = 0; i < N_STATES; i++) {
            float k_row[N_MEASUREMENTS];
            chol_solve(ekf_S_chol, ekf_S_iDiag, N_MEASUREMENTS, (HP+(i*N_MEASUREMENTS)), k_row);
            for (int j = 0; j < N_MEASUREMENTS; j++) {
                K[i + j*N_STATES] = k_row[j];
            }
        }
    }

    float qerror2 = 0.f;
    for (int i = 0; i < 4; i++) {
        qerror2 += (Z[3+i] - X[6+i])*(Z[3+i] - X[6+i]);
    }

    if (qerror2 > 2.f) {
        // quaternion error is too big, negating the measured quaternion will
        // give better convergence
        for (int i = 0; i < 4; i++) {
            Z[3+i] = -Z[3+i];
        }
    }

    // UPDATE STEP X_new, P_new = ...
    tmp[0] = -X[0] + Z[0];
	tmp[1] = -X[1] + Z[1];
	tmp[2] = -X[2] + Z[2];
	tmp[3] = -X[6]*ekf_use_quat + Z[3];
	tmp[4] = -X[7]*ekf_use_quat + Z[4];
	tmp[5] = -X[8]*ekf_use_quat + Z[5];
	tmp[6] = -X[9]*ekf_use_quat + Z[6];
	tmp[7] = K[48]*ekf_use_quat;
	tmp[8] = K[64]*ekf_use_quat;
	tmp[9] = K[80]*ekf_use_quat;
	tmp[10] = K[96]*ekf_use_quat;
	tmp[11] = 1 - K[0];
	tmp[12] = K[49]*ekf_use_quat;
	tmp[13] = K[65]*ekf_use_quat;
	tmp[14] = K[81]*ekf_use_quat;
	tmp[15] = K[97]*ekf_use_quat;
	tmp[16] = 1 - K[17];
	tmp[17] = K[50]*ekf_use_quat;
	tmp[18] = K[66]*ekf_use_quat;
	tmp[19] = K[82]*ekf_use_quat;
	tmp[20] = K[98]*ekf_use_quat;
	tmp[21] = 1 - K[34];
	tmp[22] = K[51]*ekf_use_quat;
	tmp[23] = K[67]*ekf_use_quat;
	tmp[24] = K[83]*ekf_use_quat;
	tmp[25] = K[99]*ekf_use_quat;
	tmp[26] = K[100]*ekf_use_quat;
	tmp[27] = K[52]*ekf_use_quat;
	tmp[28] = K[68]*ekf_use_quat;
	tmp[29] = K[84]*ekf_use_quat;
	tmp[30] = K[101]*ekf_use_quat;
	tmp[31] = K[53]*ekf_use_quat;
	tmp[32] = K[69]*ekf_use_quat;
	tmp[33] = K[85]*ekf_use_quat;
	tmp[34] = K[102]*ekf_use_quat;
	tmp[35] = K[70]*ekf_use_quat;
	tmp[36] = K[86]*ekf_use_quat;
	tmp[37] = -K[54]*ekf_use_quat + 1;
	tmp[38] = K[103]*ekf_use_quat;
	tmp[39] = K[55]*ekf_use_quat;
	tmp[40] = K[87]*ekf_use_quat;
	tmp[41] = -K[71]*ekf_use_quat + 1;
	tmp[42] = K[104]*ekf_use_quat;
	tmp[43] = K[56]*ekf_use_quat;
	tmp[44] = K[72]*ekf_use_quat;
	tmp[45] = -K[88]*ekf_use_quat + 1;
	tmp[46] = K[57]*ekf_use_quat;
	tmp[47] = K[73]*ekf_use_quat;
	tmp[48] = K[89]*ekf_use_quat;
	tmp[49] = -K[105]*ekf_use_quat + 1;
	tmp[50] = K[106]*ekf_use_quat;
	tmp[51] = K[58]*ekf_use_quat;
	tmp[52] = K[74]*ekf_use_quat;
	tmp[53] = K[90]*ekf_use_quat;
	tmp[54] = K[107]*ekf_use_quat;
	tmp[55] = K[59]*ekf_use_quat;
	tmp[56] = K[75]*ekf_use_quat;
	tmp[57] = K[91]*ekf_use_quat;
	tmp[58] = K[108]*ekf_use_quat;
	tmp[59] = K[60]*ekf_use_quat;
	tmp[60] = K[76]*ekf_use_quat;
	tmp[61] = K[92]*ekf_use_quat;
	tmp[62] = K[109]*ekf_use_quat;
	tmp[63] = K[61]*ekf_use_quat;
	tmp[64] = K[77]*ekf_use_quat;
	tmp[65] = K[93]*ekf_use_quat;
	tmp[66] = K[110]*ekf_use_quat;
	tmp[67] = K[62]*ekf_use_quat;
	tmp[68] = K[78]*ekf_use_quat;
	tmp[69] = K[94]*ekf_use_quat;
	X_new[0] = K[0]*tmp[0] + K[16]*tmp[1] + K[32]*tmp[2] + K[48]*tmp[3] + K[64]*tmp[4] + K[80]*tmp[5] + K[96]*tmp[6] + X[0];
	X_new[1] = K[17]*tmp[1] + K[1]*tmp[0] + K[33]*tmp[2] + K[49]*tmp[3] + K[65]*tmp[4] + K[81]*tmp[5] + K[97]*tmp[6] + X[1];
	X_new[2] = K[18]*tmp[1] + K[2]*tmp[0] + K[34]*tmp[2] + K[50]*tmp[3] + K[66]*tmp[4] + K[82]*tmp[5] + K[98]*tmp[6] + X[2];
	X_new[3] = K[19]*tmp[1] + K[35]*tmp[2] + K[3]*tmp[0] + K[51]*tmp[3] + K[67]*tmp[4] + K[83]*tmp[5] + K[99]*tmp[6] + X[3];
	X_new[4] = K[100]*tmp[6] + K[20]*tmp[1] + K[36]*tmp[2] + K[4]*tmp[0] + K[52]*tmp[3] + K[68]*tmp[4] + K[84]*tmp[5] + X[4];
	X_new[5] = K[101]*tmp[6] + K[21]*tmp[1] + K[37]*tmp[2] + K[53]*tmp[3] + K[5]*tmp[0] + K[69]*tmp[4] + K[85]*tmp[5] + X[5];
	X_new[6] = K[102]*tmp[6] + K[22]*tmp[1] + K[38]*tmp[2] + K[54]*tmp[3] + K[6]*tmp[0] + K[70]*tmp[4] + K[86]*tmp[5] + X[6];
	X_new[7] = K[103]*tmp[6] + K[23]*tmp[1] + K[39]*tmp[2] + K[55]*tmp[3] + K[71]*tmp[4] + K[7]*tmp[0] + K[87]*tmp[5] + X[7];
	X_new[8] = K[104]*tmp[6] + K[24]*tmp[1] + K[40]*tmp[2] + K[56]*tmp[3] + K[72]*tmp[4] + K[88]*tmp[5] + K[8]*tmp[0] + X[8];
	X_new[9] = K[105]*tmp[6] + K[25]*tmp[1] + K[41]*tmp[2] + K[57]*tmp[3] + K[73]*tmp[4] + K[89]*tmp[5] + K[9]*tmp[0] + X[9];
	X_new[10] = K[106]*tmp[6] + K[10]*tmp[0] + K[26]*tmp[1] + K[42]*tmp[2] + K[58]*tmp[3] + K[74]*tmp[4] + K[90]*tmp[5] + X[10];
	X_new[11] = K[107]*tmp[6] + K[11]*tmp[0] + K[27]*tmp[1] + K[43]*tmp[2] + K[59]*tmp[3] + K[75]*tmp[4] + K[91]*tmp[5] + X[11];
	X_new[12] = K[108]*tmp[6] + K[12]*tmp[0] + K[28]*tmp[1] + K[44]*tmp[2] + K[60]*tmp[3] + K[76]*tmp[4] + K[92]*tmp[5] + X[12];
	X_new[13] = K[109]*tmp[6] + K[13]*tmp[0] + K[29]*tmp[1] + K[45]*tmp[2] + K[61]*tmp[3] + K[77]*tmp[4] + K[93]*tmp[5] + X[13];
	X_new[14] = K[110]*tmp[6] + K[14]*tmp[0] + K[30]*tmp[1] + K[46]*tmp[2] + K[62]*tmp[3] + K[78]*tmp[4] + K[94]*tmp[5] + X[14];
	X_new[15] = K[111]*tmp[6] + K[15]*tmp[0] + K[31]*tmp[1] + K[47]*tmp[2] + K[63]*tmp[3] + K[79]*tmp[4] + K[95]*tmp[5] + X[15];
	P_new[0] = -K[16]*P[1] - K[32]*P[3] + P[0]*tmp[11] - P[21]*tmp[7] - P[28]*tmp[8] - P[36]*tmp[9] - P[45]*tmp[10];
	P_new[1] = -K[16]*P[2] - K[32]*P[4] + P[1]*tmp[11] - P[22]*tmp[7] - P[29]*tmp[8] - P[37]*tmp[9] - P[46]*tmp[10];
	P_new[3] = -K[16]*P[4] - K[32]*P[5] - P[23]*tmp[7] - P[30]*tmp[8] - P[38]*tmp[9] + P[3]*tmp[11] - P[47]*tmp[10];
	P_new[6] = -K[16]*P[7] - K[32]*P[8] - P[24]*tmp[7] - P[31]*tmp[8] - P[39]*tmp[9] - P[48]*tmp[10] + P[6]*tmp[11];
	P_new[10] = -K[16]*P[11] - K[32]*P[12] + P[10]*tmp[11] - P[25]*tmp[7] - P[32]*tmp[8] - P[40]*tmp[9] - P[49]*tmp[10];
	P_new[15] = -K[16]*P[16] - K[32]*P[17] + P[15]*tmp[11] - P[26]*tmp[7] - P[33]*tmp[8] - P[41]*tmp[9] - P[50]*tmp[10];
	P_new[21] = -K[16]*P[22] - K[32]*P[23] + P[21]*tmp[11] - P[27]*tmp[7] - P[34]*tmp[8] - P[42]*tmp[9] - P[51]*tmp[10];
	P_new[28] = -K[16]*P[29] - K[32]*P[30] + P[28]*tmp[11] - P[34]*tmp[7] - P[35]*tmp[8] - P[43]*tmp[9] - P[52]*tmp[10];
	P_new[36] = -K[16]*P[37] - K[32]*P[38] + P[36]*tmp[11] - P[42]*tmp[7] - P[43]*tmp[8] - P[44]*tmp[9] - P[53]*tmp[10];
	P_new[45] = -K[16]*P[46] - K[32]*P[47] + P[45]*tmp[11] - P[51]*tmp[7] - P[52]*tmp[8] - P[53]*tmp[9] - P[54]*tmp[10];
	P_new[55] = -K[16]*P[56] - K[32]*P[57] + P[55]*tmp[11] - P[61]*tmp[7] - P[62]*tmp[8] - P[63]*tmp[9] - P[64]*tmp[10];
	P_new[66] = -K[16]*P[67] - K[32]*P[68] + P[66]*tmp[11] - P[72]*tmp[7] - P[73]*tmp[8] - P[74]*tmp[9] - P[75]*tmp[10];
	P_new[78] = -K[16]*P[79] - K[32]*P[80] + P[78]*tmp[11] - P[84]*tmp[7] - P[85]*tmp[8] - P[86]*tmp[9] - P[87]*tmp[10];
	P_new[91] = -K[16]*P[92] - K[32]*P[93] - P[100]*tmp[10] + P[91]*tmp[11] - P[97]*tmp[7] - P[98]*tmp[8] - P[99]*tmp[9];
	P_new[105] = -K[16]*P[106] - K[32]*P[107] + P[105]*tmp[11] - P[111]*tmp[7] - P[112]*tmp[8] - P[113]*tmp[9] - P[114]*tmp[10];
	P_new[120] = -K[16]*P[121] - K[32]*P[122] + P[120]*tmp[11] - P[126]*tmp[7] - P[127]*tmp[8] - P[128]*tmp[9] - P[129]*tmp[10];
	P_new[2] = -K[1]*P[1] - K[33]*P[4] - P[22]*tmp[12] - P[29]*tmp[13] + P[2]*tmp[16] - P[37]*tmp[14] - P[46]*tmp[15];
	P_new[4] = -K[1]*P[3] - K[33]*P[5] - P[23]*tmp[12] - P[30]*tmp[13] - P[38]*tmp[14] - P[47]*tmp[15] + P[4]*tmp[16];
	P_new[7] = -K[1]*P[6] - K[33]*P[8] - P[24]*tmp[12] - P[31]*tmp[13] - P[39]*tmp[14] - P[48]*tmp[15] + P[7]*tmp[16];
	P_new[11] = -K[1]*P[10] - K[33]*P[12] + P[11]*tmp[16] - P[25]*tmp[12] - P[32]*tmp[13] - P[40]*tmp[14] - P[49]*tmp[15];
	P_new[16] = -K[1]*P[15] - K[33]*P[17] + P[16]*tmp[16] - P[26]*tmp[12] - P[33]*tmp[13] - P[41]*tmp[14] - P[50]*tmp[15];
	P_new[22] = -K[1]*P[21] - K[33]*P[23] + P[22]*tmp[16] - P[27]*tmp[12] - P[34]*tmp[13] - P[42]*tmp[14] - P[51]*tmp[15];
	P_new[29] = -K[1]*P[28] - K[33]*P[30] + P[29]*tmp[16] - P[34]*tmp[12] - P[35]*tmp[13] - P[43]*tmp[14] - P[52]*tmp[15];
	P_new[37] = -K[1]*P[36] - K[33]*P[38] + P[37]*tmp[16] - P[42]*tmp[12] - P[43]*tmp[13] - P[44]*tmp[14] - P[53]*tmp[15];
	P_new[46] = -K[1]*P[45] - K[33]*P[47] + P[46]*tmp[16] - P[51]*tmp[12] - P[52]*tmp[13] - P[53]*tmp[14] - P[54]*tmp[15];
	P_new[56] = -K[1]*P[55] - K[33]*P[57] + P[56]*tmp[16] - P[61]*tmp[12] - P[62]*tmp[13] - P[63]*tmp[14] - P[64]*tmp[15];
	P_new[67] = -K[1]*P[66] - K[33]*P[68] + P[67]*tmp[16] - P[72]*tmp[12] - P[73]*tmp[13] - P[74]*tmp[14] - P[75]*tmp[15];
	P_new[79] = -K[1]*P[78] - K[33]*P[80] + P[79]*tmp[16] - P[84]*tmp[12] - P[85]*tmp[13] - P[86]*tmp[14] - P[87]*tmp[15];
	P_new[92] = -K[1]*P[91] - K[33]*P[93] - P[100]*tmp[15] + P[92]*tmp[16] - P[97]*tmp[12] - P[98]*tmp[13] - P[99]*tmp[14];
	P_new[106] = -K[1]*P[105] - K[33]*P[107] + P[106]*tmp[16] - P[111]*tmp[12] - P[112]*tmp[13] - P[113]*tmp[14] - P[114]*tmp[15];
	P_new[121] = -K[1]*P[120] - K[33]*P[122] + P[121]*tmp[16] - P[126]*tmp[12] - P[127]*tmp[13] - P[128]*tmp[14] - P[129]*tmp[15];
	P_new[5] = -K[18]*P[4] - K[2]*P[3] - P[23]*tmp[17] - P[30]*tmp[18] - P[38]*tmp[19] - P[47]*tmp[20] + P[5]*tmp[21];
	P_new[8] = -K[18]*P[7] - K[2]*P[6] - P[24]*tmp[17] - P[31]*tmp[18] - P[39]*tmp[19] - P[48]*tmp[20] + P[8]*tmp[21];
	P_new[12] = -K[18]*P[11] - K[2]*P[10] + P[12]*tmp[21] - P[25]*tmp[17] - P[32]*tmp[18] - P[40]*tmp[19] - P[49]*tmp[20];
	P_new[17] = -K[18]*P[16] - K[2]*P[15] + P[17]*tmp[21] - P[26]*tmp[17] - P[33]*tmp[18] - P[41]*tmp[19] - P[50]*tmp[20];
	P_new[23] = -K[18]*P[22] - K[2]*P[21] + P[23]*tmp[21] - P[27]*tmp[17] - P[34]*tmp[18] - P[42]*tmp[19] - P[51]*tmp[20];
	P_new[30] = -K[18]*P[29] - K[2]*P[28] + P[30]*tmp[21] - P[34]*tmp[17] - P[35]*tmp[18] - P[43]*tmp[19] - P[52]*tmp[20];
	P_new[38] = -K[18]*P[37] - K[2]*P[36] + P[38]*tmp[21] - P[42]*tmp[17] - P[43]*tmp[18] - P[44]*tmp[19] - P[53]*tmp[20];
	P_new[47] = -K[18]*P[46] - K[2]*P[45] + P[47]*tmp[21] - P[51]*tmp[17] - P[52]*tmp[18] - P[53]*tmp[19] - P[54]*tmp[20];
	P_new[57] = -K[18]*P[56] - K[2]*P[55] + P[57]*tmp[21] - P[61]*tmp[17] - P[62]*tmp[18] - P[63]*tmp[19] - P[64]*tmp[20];
	P_new[68] = -K[18]*P[67] - K[2]*P[66] + P[68]*tmp[21] - P[72]*tmp[17] - P[73]*tmp[18] - P[74]*tmp[19] - P[75]*tmp[20];
	P_new[80] = -K[18]*P[79] - K[2]*P[78] + P[80]*tmp[21] - P[84]*tmp[17] - P[85]*tmp[18] - P[86]*tmp[19] - P[87]*tmp[20];
	P_new[93] = -K[18]*P[92] - K[2]*P[91] - P[100]*tmp[20] + P[93]*tmp[21] - P[97]*tmp[17] - P[98]*tmp[18] - P[99]*tmp[19];
	P_new[107] = -K[18]*P[106] - K[2]*P[105] + P[107]*tmp[21] - P[111]*tmp[17] - P[112]*tmp[18] - P[113]*tmp[19] - P[114]*tmp[20];
	P_new[122] = -K[18]*P[121] - K[2]*P[120] + P[122]*tmp[21] - P[126]*tmp[17] - P[127]*tmp[18] - P[128]*tmp[19] - P[129]*tmp[20];
	P_new[9] = -K[19]*P[7] - K[35]*P[8] - K[3]*P[6] - P[24]*tmp[22] - P[31]*tmp[23] - P[39]*tmp[24] - P[48]*tmp[25] + P[9];
	P_new[13] = -K[19]*P[11] - K[35]*P[12] - K[3]*P[10] + P[13] - P[25]*tmp[22] - P[32]*tmp[23] - P[40]*tmp[24] - P[49]*tmp[25];
	P_new[18] = -K[19]*P[16] - K[35]*P[17] - K[3]*P[15] + P[18] - P[26]*tmp[22] - P[33]*tmp[23] - P[41]*tmp[24] - P[50]*tmp[25];
	P_new[24] = -K[19]*P[22] - K[35]*P[23] - K[3]*P[21] + P[24] - P[27]*tmp[22] - P[34]*tmp[23] - P[42]*tmp[24] - P[51]*tmp[25];
	P_new[31] = -K[19]*P[29] - K[35]*P[30] - K[3]*P[28] + P[31] - P[34]*tmp[22] - P[35]*tmp[23] - P[43]*tmp[24] - P[52]*tmp[25];
	P_new[39] = -K[19]*P[37] - K[35]*P[38] - K[3]*P[36] + P[39] - P[42]*tmp[22] - P[43]*tmp[23] - P[44]*tmp[24] - P[53]*tmp[25];
	P_new[48] = -K[19]*P[46] - K[35]*P[47] - K[3]*P[45] + P[48] - P[51]*tmp[22] - P[52]*tmp[23] - P[53]*tmp[24] - P[54]*tmp[25];
	P_new[58] = -K[19]*P[56] - K[35]*P[57] - K[3]*P[55] + P[58] - P[61]*tmp[22] - P[62]*tmp[23] - P[63]*tmp[24] - P[64]*tmp[25];
	P_new[69] = -K[19]*P[67] - K[35]*P[68] - K[3]*P[66] + P[69] - P[72]*tmp[22] - P[73]*tmp[23] - P[74]*tmp[24] - P[75]*tmp[25];
	P_new[81] = -K[19]*P[79] - K[35]*P[80] - K[3]*P[78] + P[81] - P[84]*tmp[22] - P[85]*tmp[23] - P[86]*tmp[24] - P[87]*tmp[25];
	P_new[94] = -K[19]*P[92] - K[35]*P[93] - K[3]*P[91] - P[100]*tmp[25] + P[94] - P[97]*tmp[22] - P[98]*tmp[23] - P[99]*tmp[24];
	P_new[108] = -K[19]*P[106] - K[35]*P[107] - K[3]*P[105] + P[108] - P[111]*tmp[22] - P[112]*tmp[23] - P[113]*tmp[24] - P[114]*tmp[25];
	P_new[123] = -K[19]*P[121] - K[35]*P[122] - K[3]*P[120] + P[123] - P[126]*tmp[22] - P[127]*tmp[23] - P[128]*tmp[24] - P[129]*tmp[25];
	P_new[14] = -K[20]*P[11] - K[36]*P[12] - K[4]*P[10] + P[14] - P[25]*tmp[27] - P[32]*tmp[28] - P[40]*tmp[29] - P[49]*tmp[26];
	P_new[19] = -K[20]*P[16] - K[36]*P[17] - K[4]*P[15] + P[19] - P[26]*tmp[27] - P[33]*tmp[28] - P[41]*tmp[29] - P[50]*tmp[26];
	P_new[25] = -K[20]*P[22] - K[36]*P[23] - K[4]*P[21] + P[25] - P[27]*tmp[27] - P[34]*tmp[28] - P[42]*tmp[29] - P[51]*tmp[26];
	P_new[32] = -K[20]*P[29] - K[36]*P[30] - K[4]*P[28] + P[32] - P[34]*tmp[27] - P[35]*tmp[28] - P[43]*tmp[29] - P[52]*tmp[26];
	P_new[40] = -K[20]*P[37] - K[36]*P[38] - K[4]*P[36] + P[40] - P[42]*tmp[27] - P[43]*tmp[28] - P[44]*tmp[29] - P[53]*tmp[26];
	P_new[49] = -K[20]*P[46] - K[36]*P[47] - K[4]*P[45] + P[49] - P[51]*tmp[27] - P[52]*tmp[28] - P[53]*tmp[29] - P[54]*tmp[26];
	P_new[59] = -K[20]*P[56] - K[36]*P[57] - K[4]*P[55] + P[59] - P[61]*tmp[27] - P[62]*tmp[28] - P[63]*tmp[29] - P[64]*tmp[26];
	P_new[70] = -K[20]*P[67] - K[36]*P[68] - K[4]*P[66] + P[70] - P[72]*tmp[27] - P[73]*tmp[28] - P[74]*tmp[29] - P[75]*tmp[26];
	P_new[82] = -K[20]*P[79] - K[36]*P[80] - K[4]*P[78] + P[82] - P[84]*tmp[27] - P[85]*tmp[28] - P[86]*tmp[29] - P[87]*tmp[26];
	P_new[95] = -K[20]*P[92] - K[36]*P[93] - K[4]*P[91] - P[100]*tmp[26] + P[95] - P[97]*tmp[27] - P[98]*tmp[28] - P[99]*tmp[29];
	P_new[109] = -K[20]*P[106] - K[36]*P[107] - K[4]*P[105] + P[109] - P[111]*tmp[27] - P[112]*tmp[28] - P[113]*tmp[29] - P[114]*tmp[26];
	P_new[124] = -K[20]*P[121] - K[36]*P[122] - K[4]*P[120] + P[124] - P[126]*tmp[27] - P[127]*tmp[28] - P[128]*tmp[29] - P[129]*tmp[26];
	P_new[20] = -K[21]*P[16] - K[37]*P[17] - K[5]*P[15] + P[20] - P[26]*tmp[31] - P[33]*tmp[32] - P[41]*tmp[33] - P[50]*tmp[30];
	P_new[26] = -K[21]*P[22] - K[37]*P[23] - K[5]*P[21] + P[26] - P[27]*tmp[31] - P[34]*tmp[32] - P[42]*tmp[33] - P[51]*tmp[30];
	P_new[33] = -K[21]*P[29] - K[37]*P[30] - K[5]*P[28] + P[33] - P[34]*tmp[31] - P[35]*tmp[32] - P[43]*tmp[33] - P[52]*tmp[30];
	P_new[41] = -K[21]*P[37] - K[37]*P[38] - K[5]*P[36] + P[41] - P[42]*tmp[31] - P[43]*tmp[32] - P[44]*tmp[33] - P[53]*tmp[30];
	P_new[50] = -K[21]*P[46] - K[37]*P[47] - K[5]*P[45] + P[50] - P[51]*tmp[31] - P[52]*tmp[32] - P[53]*tmp[33] - P[54]*tmp[30];
	P_new[60] = -K[21]*P[56] - K[37]*P[57] - K[5]*P[55] + P[60] - P[61]*tmp[31] - P[62]*tmp[32] - P[63]*tmp[33] - P[64]*tmp[30];
	P_new[71] = -K[21]*P[67] - K[37]*P[68] - K[5]*P[66] + P[71] - P[72]*tmp[31] - P[73]*tmp[32] - P[74]*tmp[33] - P[75]*tmp[30];
	P_new[83] = -K[21]*P[79] - K[37]*P[80] - K[5]*P[78] + P[83] - P[84]*tmp[31] - P[85]*tmp[32] - P[86]*tmp[33] - P[87]*tmp[30];
	P_new[96] = -K[21]*P[92] - K[37]*P[93] - K[5]*P[91] - P[100]*tmp[30] + P[96] - P[97]*tmp[31] - P[98]*tmp[32] - P[99]*tmp[33];
	P_new[110] = -K[21]*P[106] - K[37]*P[107] - K[5]*P[105] + P[110] - P[111]*tmp[31] - P[112]*tmp[32] - P[113]*tmp[33] - P[114]*tmp[30];
	P_new[125] = -K[21]*P[121] - K[37]*P[122] - K[5]*P[120] + P[125] - P[126]*tmp[31] - P[127]*tmp[32] - P[128]*tmp[33] - P[129]*tmp[30];
	P_new[27] = -K[22]*P[22] - K[38]*P[23] - K[6]*P[21] + P[27]*tmp[37] - P[34]*tmp[35] - P[42]*tmp[36] - P[51]*tmp[34];
	P_new[34] = -K[22]*P[29] - K[38]*P[30] - K[6]*P[28] + P[34]*tmp[37] - P[35]*tmp[35] - P[43]*tmp[36] - P[52]*tmp[34];
	P_new[42] = -K[22]*P[37] - K[38]*P[38] - K[6]*P[36] + P[42]*tmp[37] - P[43]*tmp[35] - P[44]*tmp[36] - P[53]*tmp[34];
	P_new[51] = -K[22]*P[46] - K[38]*P[47] - K[6]*P[45] + P[51]*tmp[37] - P[52]*tmp[35] - P[53]*tmp[36] - P[54]*tmp[34];
	P_new[61] = -K[22]*P[56] - K[38]*P[57] - K[6]*P[55] + P[61]*tmp[37] - P[62]*tmp[35] - P[63]*tmp[36] - P[64]*tmp[34];
	P_new[72] = -K[22]*P[67] - K[38]*P[68] - K[6]*P[66] + P[72]*tmp[37] - P[73]*tmp[35] - P[74]*tmp[36] - P[75]*tmp[34];
	P_new[84] = -K[22]*P[79] - K[38]*P[80] - K[6]*P[78] + P[84]*tmp[37] - P[85]*tmp[35] - P[86]*tmp[36] - P[87]*tmp[34];
	P_new[97] = -K[22]*P[92] - K[38]*P[93] - K[6]*P[91] - P[100]*tmp[34] + P[97]*tmp[37] - P[98]*tmp[35] - P[99]*tmp[36];
	P_new[111] = -K[22]*P[106] - K[38]*P[107] - K[6]*P[105] + P[111]*tmp[37] - P[112]*tmp[35] - P[113]*tmp[36] - P[114]*tmp[34];
	P_new[126] = -K[22]*P[121] - K[38]*P[122] - K[6]*P[120] + P[126]*tmp[37] - P[127]*tmp[35] - P[128]*tmp[36] - P[129]*tmp[34];
	P_new[35] = -K[23]*P[29] - K[39]*P[30] - K[7]*P[28] - P[34]*tmp[39] + P[35]*tmp[41] - P[43]*tmp[40] - P[52]*tmp[38];
	P_new[43] = -K[23]*P[37] - K[39]*P[38] - K[7]*P[36] - P[42]*tmp[39] + P[43]*tmp[41] - P[44]*tmp[40] - P[53]*tmp[38];
	P_new[52] = -K[23]*P[46] - K[39]*P[47] - K[7]*P[45] - P[51]*tmp[39] + P[52]*tmp[41] - P[53]*tmp[40] - P[54]*tmp[38];
	P_new[62] = -K[23]*P[56] - K[39]*P[57] - K[7]*P[55] - P[61]*tmp[39] + P[62]*tmp[41] - P[63]*tmp[40] - P[64]*tmp[38];
	P_new[73] = -K[23]*P[67] - K[39]*P[68] - K[7]*P[66] - P[72]*tmp[39] + P[73]*tmp[41] - P[74]*tmp[40] - P[75]*tmp[38];
	P_new[85] = -K[23]*P[79] - K[39]*P[80] - K[7]*P[78] - P[84]*tmp[39] + P[85]*tmp[41] - P[86]*tmp[40] - P[87]*tmp[38];
	P_new[98] = -K[23]*P[92] - K[39]*P[93] - K[7]*P[91] - P[100]*tmp[38] - P[97]*tmp[39] + P[98]*tmp[41] - P[99]*tmp[40];
	P_new[112] = -K[23]*P[106] - K[39]*P[107] - K[7]*P[105] - P[111]*tmp[39] + P[112]*tmp[41] - P[113]*tmp[40] - P[114]*tmp[38];
	P_new[127] = -K[23]*P[121] - K[39]*P[122] - K[7]*P[120] - P[126]*tmp[39] + P[127]*tmp[41] - P[128]*tmp[40] - P[129]*tmp[38];
	P_new[44] = -K[24]*P[37] - K[40]*P[38] - K[8]*P[36] - P[42]*tmp[43] - P[43]*tmp[44] + P[44]*tmp[45] - P[53]*tmp[42];
	P_new[53] = -K[24]*P[46] - K[40]*P[47] - K[8]*P[45] - P[51]*tmp[43] - P[52]*tmp[44] + P[53]*tmp[45] - P[54]*tmp[42];
	P_new[63] = -K[24]*P[56] - K[40]*P[57] - K[8]*P[55] - P[61]*tmp[43] - P[62]*tmp[44] + P[63]*tmp[45] - P[64]*tmp[42];
	P_new[74] = -K[24]*P[67] - K[40]*P[68] - K[8]*P[66] - P[72]*tmp[43] - P[73]*tmp[44] + P[74]*tmp[45] - P[75]*tmp[42];
	P_new[86] = -K[24]*P[79] - K[40]*P[80] - K[8]*P[78] - P[84]*tmp[43] - P[85]*tmp[44] + P[86]*tmp[45] - P[87]*tmp[42];
	P_new[99] = -K[24]*P[92] - K[40]*P[93] - K[8]*P[91] - P[100]*tmp[42] - P[97]*tmp[43] - P[98]*tmp[44] + P[99]*tmp[45];
	P_new[113] = -K[24]*P[106] - K[40]*P[107] - K[8]*P[105] - P[111]*tmp[43] - P[112]*tmp[44] + P[113]*tmp[45] - P[114]*tmp[42];
	P_new[128] = -K[24]*P[121] - K[40]*P[122] - K[8]*P[120] - P[126]*tmp[43] - P[127]*tmp[44] + P[128]*tmp[45] - P[129]*tmp[42];
	P_new[54] = -K[25]*P[46] - K[41]*P[47] - K[9]*P[45] - P[51]*tmp[46] - P[52]*tmp[47] - P[53]*tmp[48] + P[54]*tmp[49];
	P_new[64] = -K[25]*P[56] - K[41]*P[57] - K[9]*P[55] - P[61]*tmp[46] - P[62]*tmp[47] - P[63]*tmp[48] + P[64]*tmp[49];
	P_new[75] = -K[25]*P[67] - K[41]*P[68] - K[9]*P[66] - P[72]*tmp[46] - P[73]*tmp[47] - P[74]*tmp[48] + P[75]*tmp[49];
	P_new[87] = -K[25]*P[79] - K[41]*P[80] - K[9]*P[78] - P[84]*tmp[46] - P[85]*tmp[47] - P[86]*tmp[48] + P[87]*tmp[49];
	P_new[100] = -K[25]*P[92] - K[41]*P[93] - K[9]*P[91] + P[100]*tmp[49] - P[97]*tmp[46] - P[98]*tmp[47] - P[99]*tmp[48];
	P_new[114] = -K[25]*P[106] - K[41]*P[107] - K[9]*P[105] - P[111]*tmp[46] - P[112]*tmp[47] - P[113]*tmp[48] + P[114]*tmp[49];
	P_new[129] = -K[25]*P[121] - K[41]*P[122] - K[9]*P[120] - P[126]*tmp[46] - P[127]*tmp[47] - P[128]*tmp[48] + P[129]*tmp[49];
	P_new[65] = -K[10]*P[55] - K[26]*P[56] - K[42]*P[57] - P[61]*tmp[51] - P[62]*tmp[52] - P[63]*tmp[53] - P[64]*tmp[50] + P[65];
	P_new[76] = -K[10]*P[66] - K[26]*P[67] - K[42]*P[68] - P[72]*tmp[51] - P[73]*tmp[52] - P[74]*tmp[53] - P[75]*tmp[50] + P[76];
	P_new[88] = -K[10]*P[78] - K[26]*P[79] - K[42]*P[80] - P[84]*tmp[51] - P[85]*tmp[52] - P[86]*tmp[53] - P[87]*tmp[50] + P[88];
	P_new[101] = -K[10]*P[91] - K[26]*P[92] - K[42]*P[93] - P[100]*tmp[50] + P[101] - P[97]*tmp[51] - P[98]*tmp[52] - P[99]*tmp[53];
	P_new[115] = -K[10]*P[105] - K[26]*P[106] - K[42]*P[107] - P[111]*tmp[51] - P[112]*tmp[52] - P[113]*tmp[53] - P[114]*tmp[50] + P[115];
	P_new[130] = -K[10]*P[120] - K[26]*P[121] - K[42]*P[122] - P[126]*tmp[51] - P[127]*tmp[52] - P[128]*tmp[53] - P[129]*tmp[50] + P[130];
	P_new[77] = -K[11]*P[66] - K[27]*P[67] - K[43]*P[68] - P[72]*tmp[55] - P[73]*tmp[56] - P[74]*tmp[57] - P[75]*tmp[54] + P[77];
	P_new[89] = -K[11]*P[78] - K[27]*P[79] - K[43]*P[80] - P[84]*tmp[55] - P[85]*tmp[56] - P[86]*tmp[57] - P[87]*tmp[54] + P[89];
	P_new[102] = -K[11]*P[91] - K[27]*P[92] - K[43]*P[93] - P[100]*tmp[54] + P[102] - P[97]*tmp[55] - P[98]*tmp[56] - P[99]*tmp[57];
	P_new[116] = -K[11]*P[105] - K[27]*P[106] - K[43]*P[107] - P[111]*tmp[55] - P[112]*tmp[56] - P[113]*tmp[57] - P[114]*tmp[54] + P[116];
	P_new[131] = -K[11]*P[120] - K[27]*P[121] - K[43]*P[122] - P[126]*tmp[55] - P[127]*tmp[56] - P[128]*tmp[57] - P[129]*tmp[54] + P[131];
	P_new[90] = -K[12]*P[78] - K[28]*P[79] - K[44]*P[80] - P[84]*tmp[59] - P[85]*tmp[60] - P[86]*tmp[61] - P[87]*tmp[58] + P[90];
	P_new[103] = -K[12]*P[91] - K[28]*P[92] - K[44]*P[93] - P[100]*tmp[58] + P[103] - P[97]*tmp[59] - P[98]*tmp[60] - P[99]*tmp[61];
	P_new[117] = -K[12]*P[105] - K[28]*P[106] - K[44]*P[107] - P[111]*tmp[59] - P[112]*tmp[60] - P[113]*tmp[61] - P[114]*tmp[58] + P[117];
	P_new[132] = -K[12]*P[120] - K[28]*P[121] - K[44]*P[122] - P[126]*tmp[59] - P[127]*tmp[60] - P[128]*tmp[61] - P[129]*tmp[58] + P[132];
	P_new[104] = -K[13]*P[91] - K[29]*P[92] - K[45]*P[93] - P[100]*tmp[62] + P[104] - P[97]*tmp[63] - P[98]*tmp[64] - P[99]*tmp[65];
	P_new[118] = -K[13]*P[105] - K[29]*P[106] - K[45]*P[107] - P[111]*tmp[63] - P[112]*tmp[64] - P[113]*tmp[65] - P[114]*tmp[62] + P[118];
	P_new[133] = -K[13]*P[120] - K[29]*P[121] - K[45]*P[122] - P[126]*tmp[63] - P[127]*tmp[64] - P[128]*tmp[65] - P[129]*tmp[62] + P[133];
	P_new[119] = -K[14]*P[105] - K[30]*P[106] - K[46]*P[107] - P[111]*tmp[67] - P[112]*tmp[68] - P[113]*tmp[69] - P[114]*tmp[66] + P[119];
	P_new[134] = -K[14]*P[120] - K[30]*P[121] - K[46]*P[122] - P[126]*tmp[67] - P[127]*tmp[68] - P[128]*tmp[69] - P[129]*tmp[66] + P[134];
	P_new[135] = -K[111]*P[129]*ekf_use_quat - K[15]*P[120] - K[31]*P[121] - K[47]*P[122] - K[63]*P[126]*ekf_use_quat - K[79]*P[127]*ekf_use_quat - K[95]*P[128]*ekf_use_quat + P[135];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    normalize_quaternion(X+6);

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}
