
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated in "Generate Kalman Filter C Code.ipynb" from https://github.com/tudelft/ekf_c_code_generation
// Git: rotwing_landing@71f4c514 (dirty)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef EKF_CALC_H
#define EKF_CALC_H

#include <stdint.h>
#include "math/pprz_algebra_float.h"
#include "state.h"
#include "generated/airframe.h"

#define N_STATES 9
#define N_INPUTS 3
#define N_MEASUREMENTS_ARUCO 9
#define N_MEASUREMENTS_SIXDOF 9
#define N_MEASUREMENTS_RELBEACON 9
#define N_MEASUREMENTS_RELBEACON 9
#define N_MEASUREMENTS_GPS 9

// Sensor extrinsics must be defined in the airframe file:
// REMOTE_SENSING_ARUCO_BODY_OFFSET_X, REMOTE_SENSING_ARUCO_BODY_OFFSET_Y, REMOTE_SENSING_ARUCO_BODY_OFFSET_Z
// REMOTE_SENSING_ARUCO_PHI, REMOTE_SENSING_ARUCO_THETA, REMOTE_SENSING_ARUCO_PSI
// REMOTE_SENSING_FALCON_BODY_OFFSET_X, REMOTE_SENSING_FALCON_BODY_OFFSET_Y, REMOTE_SENSING_FALCON_BODY_OFFSET_Z
// REMOTE_SENSING_FALCON_PHI, REMOTE_SENSING_FALCON_THETA, REMOTE_SENSING_FALCON_PSI

// getters
float* ekf_get_X();     // get state vector
float* ekf_get_P();     // get covariance matrix (lower diagonal)
float* ekf_get_last_HX_aruco(void);      // get last aruco linearized measurement projection H*X
float* ekf_get_last_HX_sixdof(void);     // get last sixdof linearized measurement projection H*X
float* ekf_get_last_HX_relbeacon(void);  // get last relbeacon linearized measurement projection H*X
float* ekf_get_last_HX_gps(void);        // get last gps linearized measurement projection H*X

#define ekf_P_index(i,j) ((i>=j) ? ekf_get_P()[i*(i+1)/2+j] : ekf_get_P()[j*(j+1)/2+i])
#define ekf_X_index(i) ekf_get_X()[i]

// setters
void ekf_set_Q(float Q[N_STATES]);                          // set process noise covariance matrix diagonal
void ekf_set_R_aruco(float R[N_MEASUREMENTS_ARUCO]);        // set measurement noise covariance matrix diagonal (Aruco)
void ekf_set_R_sixdof(float R[N_MEASUREMENTS_SIXDOF]);      // set measurement noise covariance matrix diagonal (SixDOF)
void ekf_set_R_relbeacon(float R[N_MEASUREMENTS_RELBEACON]); // set measurement noise covariance matrix diagonal (Relbeacon)
void ekf_set_R_gps(float R[N_MEASUREMENTS_GPS]);            // set measurement noise covariance matrix diagonal (GPS)
void ekf_set_X(float X0[N_STATES]);                         // set state vector
void ekf_set_P_diag(float P_diag[N_STATES]);                // set covariance matrix diagonal
void ekf_set_P(float P0[N_STATES*(N_STATES+1)/2]);          // set covariance matrix (lower diagonal)

// prediction and update functions
void ekf_predict(float U[N_INPUTS], float dt);
void ekf_update_aruco(struct FloatVect3 aruco_pos);
void ekf_update_sixdof(struct FloatVect3 sixdof_pos, struct FloatQuat sixdof_quat);
void ekf_update_sixdof_pos_var(struct FloatVect3 sixdof_pos_var);
void ekf_update_relbeacon(struct FloatVect3 relbeacon_pos);
void ekf_update_gps(struct FloatVect3 rtk_pos, struct FloatVect3 rtk_speed);
void ekf_clip_covariance();

#endif // EKF_CALC_H
