
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// This file is automatically generated in "Generate Kalman Filter C Code.ipynb" from https://github.com/tudelft/ekf_c_code_generation
// Git: rotwing_landing@71f4c514 (dirty)
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

#ifndef REMOTE_SENSING_ARUCO_BODY_OFFSET_X
#error "REMOTE_SENSING_ARUCO_BODY_OFFSET_X must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_ARUCO_BODY_OFFSET_Y
#error "REMOTE_SENSING_ARUCO_BODY_OFFSET_Y must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_ARUCO_BODY_OFFSET_Z
#error "REMOTE_SENSING_ARUCO_BODY_OFFSET_Z must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_ARUCO_PHI
#error "REMOTE_SENSING_ARUCO_PHI must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_ARUCO_THETA
#error "REMOTE_SENSING_ARUCO_THETA must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_ARUCO_PSI
#error "REMOTE_SENSING_ARUCO_PSI must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_BODY_OFFSET_X
#error "REMOTE_SENSING_FALCON_BODY_OFFSET_X must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_BODY_OFFSET_Y
#error "REMOTE_SENSING_FALCON_BODY_OFFSET_Y must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_BODY_OFFSET_Z
#error "REMOTE_SENSING_FALCON_BODY_OFFSET_Z must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_PHI
#error "REMOTE_SENSING_FALCON_PHI must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_THETA
#error "REMOTE_SENSING_FALCON_THETA must be defined in the airframe file for Remote Sensing EKF"
#endif

#ifndef REMOTE_SENSING_FALCON_PSI
#error "REMOTE_SENSING_FALCON_PSI must be defined in the airframe file for Remote Sensing EKF"
#endif

// Check covariance clipping configuration
#ifdef REMOTE_SENSING_EKF_CLIP_P
#if REMOTE_SENSING_EKF_CLIP_P
#ifndef REMOTE_SENSING_EKF_P_MIN
#error "REMOTE_SENSING_EKF_P_MIN must be defined when REMOTE_SENSING_EKF_CLIP_P is enabled"
#endif
#ifndef REMOTE_SENSING_EKF_P_MAX
#error "REMOTE_SENSING_EKF_P_MAX must be defined when REMOTE_SENSING_EKF_CLIP_P is enabled"
#endif
#endif
#endif

#include "remote_sensing_ekf.h"
#include <math.h>

float ekf_Q[N_STATES];                              // Kalman filter process noise covariance matrix (diagonal)
float ekf_R_aruco[N_MEASUREMENTS_ARUCO];            // Kalman filter measurement noise covariance matrix (diagonal) - Aruco
float ekf_R_sixdof[N_MEASUREMENTS_SIXDOF];          // Kalman filter measurement noise covariance matrix (diagonal) - SixDOF
float ekf_R_relbeacon[N_MEASUREMENTS_RELBEACON];    // Kalman filter measurement noise covariance matrix (diagonal) - Relbeacon
float ekf_R_gps[N_MEASUREMENTS_GPS];                // Kalman filter measurement noise covariance matrix (diagonal) - GPS
float ekf_last_HX_aruco[N_MEASUREMENTS_ARUCO];      // Last linearized measurement projection H*X (Aruco)
float ekf_last_HX_sixdof[N_MEASUREMENTS_SIXDOF];    // Last linearized measurement projection H*X (SixDOF)
float ekf_last_HX_relbeacon[N_MEASUREMENTS_RELBEACON]; // Last linearized measurement projection H*X (Relbeacon)
float ekf_last_HX_gps[N_MEASUREMENTS_GPS];          // Last linearized measurement projection H*X (GPS)

// state
float ekf_X[N_STATES];
float ekf_X_new[N_STATES];

// covariance matrix (lower diagonal) P[i,j] = P_lower_diagonal[i*(i+1)/2+j] (if i>=j)
float ekf_P_lower_diagonal[N_STATES*(N_STATES+1)/2];
float ekf_P_lower_diagonal_new[N_STATES*(N_STATES+1)/2];

// temporary variables
float tmp[1000];

// pointers
float *X = ekf_X;
float *X_new = ekf_X_new;

float *P = ekf_P_lower_diagonal;
float *P_new = ekf_P_lower_diagonal_new;

// pointers for measurement noise (will be updated based on active sensor)
float *R;

// pointer for swapping
float *swap_ptr;

float* ekf_get_X() {
    return X;
}

float* ekf_get_P() {
    return P;
}

float* ekf_get_last_HX_aruco(void) {
	return ekf_last_HX_aruco;
}

float* ekf_get_last_HX_sixdof(void) {
	return ekf_last_HX_sixdof;
}

float* ekf_get_last_HX_relbeacon(void) {
	return ekf_last_HX_relbeacon;
}

float* ekf_get_last_HX_gps(void) {
	return ekf_last_HX_gps;
}

void ekf_set_Q(float Q[N_INPUTS]) {
    for (int i=0; i < N_INPUTS; i++) {
        ekf_Q[i] = Q[i];
    }
}

void ekf_set_R_aruco(float R_in[N_MEASUREMENTS_ARUCO]) {
    for (int i=0; i < N_MEASUREMENTS_ARUCO; i++) {
        ekf_R_aruco[i] = R_in[i];
    }
}

void ekf_set_R_sixdof(float R_in[N_MEASUREMENTS_SIXDOF]) {
    for (int i=0; i < N_MEASUREMENTS_SIXDOF; i++) {
        ekf_R_sixdof[i] = R_in[i];
    }
}

void ekf_set_R_relbeacon(float R_in[N_MEASUREMENTS_RELBEACON]) {
    for (int i=0; i < N_MEASUREMENTS_RELBEACON; i++) {
        ekf_R_relbeacon[i] = R_in[i];
    }
}

void ekf_set_R_gps(float R_in[N_MEASUREMENTS_GPS]) {
    for (int i=0; i < N_MEASUREMENTS_GPS; i++) {
        ekf_R_gps[i] = R_in[i];
    }
}

void ekf_set_X(float X0[N_STATES]) {
    for (int i=0; i < N_STATES; i++) {
        X[i] = X0[i];
    }
}

void ekf_set_P_diag(float P_diag[N_STATES]) {
    // set P to zeros
    for (int i=0; i < N_STATES*(N_STATES+1)/2; i++) {
        P[i] = 0.;
    }
    // set diagonal
    for (int i=0; i<N_STATES; i++) {
        P[i*(i+1)/2+i] = P_diag[i];
    }
}

void ekf_set_P(float P0[N_STATES*(N_STATES+1)/2]) {
    for (int i=0; i < N_STATES*(N_STATES+1)/2; i++) {
        P[i] = P0[i];
    }
}

void ekf_predict(float U[N_INPUTS], float dt) {
    // PREDICTION STEP X_new, P_new = ...
    tmp[0] = (1.0/2.0)*powf(dt, 2);
	tmp[1] = P[6] + P[9]*dt;
	tmp[2] = P[13]*dt;
	tmp[3] = P[7] + tmp[2];
	tmp[4] = P[11] + P[14]*dt;
	tmp[5] = P[18]*dt;
	tmp[6] = P[8] + tmp[5];
	tmp[7] = P[19]*dt;
	tmp[8] = P[12] + tmp[7];
	tmp[9] = P[17] + P[20]*dt;
	X_new[0] = U[0]*tmp[0] + X[0] + X[3]*dt;
	X_new[1] = U[1]*tmp[0] + X[1] + X[4]*dt;
	X_new[2] = U[2]*tmp[0] + X[2] + X[5]*dt;
	X_new[3] = U[0]*dt + X[3];
	X_new[4] = U[1]*dt + X[4];
	X_new[5] = U[2]*dt + X[5];
	X_new[6] = X[6];
	X_new[7] = X[7];
	X_new[8] = X[8];
	P_new[0] = P[0] + P[6]*dt + dt*tmp[1] + ekf_Q[0];
	P_new[1] = P[10]*dt + P[1] + dt*tmp[3];
	P_new[2] = P[11]*dt + P[2] + dt*tmp[4] + ekf_Q[1];
	P_new[3] = P[15]*dt + P[3] + dt*tmp[6];
	P_new[4] = P[16]*dt + P[4] + dt*tmp[8];
	P_new[5] = P[17]*dt + P[5] + dt*tmp[9] + ekf_Q[2];
	P_new[6] = tmp[1];
	P_new[7] = tmp[3];
	P_new[8] = tmp[6];
	P_new[9] = P[9] + ekf_Q[3];
	P_new[10] = P[10] + tmp[2];
	P_new[11] = tmp[4];
	P_new[12] = tmp[8];
	P_new[13] = P[13];
	P_new[14] = P[14] + ekf_Q[4];
	P_new[15] = P[15] + tmp[5];
	P_new[16] = P[16] + tmp[7];
	P_new[17] = tmp[9];
	P_new[18] = P[18];
	P_new[19] = P[19];
	P_new[20] = P[20] + ekf_Q[5];
	P_new[21] = P[21] + P[24]*dt;
	P_new[22] = P[22] + P[25]*dt;
	P_new[23] = P[23] + P[26]*dt;
	P_new[24] = P[24];
	P_new[25] = P[25];
	P_new[26] = P[26];
	P_new[27] = P[27] + ekf_Q[6];
	P_new[28] = P[28] + P[31]*dt;
	P_new[29] = P[29] + P[32]*dt;
	P_new[30] = P[30] + P[33]*dt;
	P_new[31] = P[31];
	P_new[32] = P[32];
	P_new[33] = P[33];
	P_new[34] = P[34];
	P_new[35] = P[35] + ekf_Q[7];
	P_new[36] = P[36] + P[39]*dt;
	P_new[37] = P[37] + P[40]*dt;
	P_new[38] = P[38] + P[41]*dt;
	P_new[39] = P[39];
	P_new[40] = P[40];
	P_new[41] = P[41];
	P_new[42] = P[42];
	P_new[43] = P[43];
	P_new[44] = P[44] + ekf_Q[8];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_update_aruco(struct FloatVect3 aruco_pos) {
    
    // Prepare measurement vector from measurements
	float Z[N_MEASUREMENTS_ARUCO];
	float *HX = ekf_last_HX_aruco;
    Z[0] = aruco_pos.x;
    Z[1] = aruco_pos.y;
    Z[2] = aruco_pos.z;
    
    // Set R pointer to Aruco measurement noise
    R = ekf_R_aruco;
    // Read UAV attitude from state estimation interface
    const struct FloatEulers *ned_to_body = stateGetNedToBodyEulers_f();
    const float uav_phi = ned_to_body->phi;
    const float uav_theta = ned_to_body->theta;
    const float uav_psi = ned_to_body->psi;
    // UPDATE STEP X_new, P_new = ...
    tmp[0] = cosf(uav_phi);
	tmp[1] = cosf(uav_theta);
	tmp[2] = tmp[0]*tmp[1];
	tmp[3] = cosf(REMOTE_SENSING_ARUCO_PHI);
	tmp[4] = cosf(REMOTE_SENSING_ARUCO_THETA);
	tmp[5] = tmp[3]*tmp[4];
	tmp[6] = sinf(REMOTE_SENSING_ARUCO_THETA);
	tmp[7] = sinf(uav_phi);
	tmp[8] = sinf(uav_psi);
	tmp[9] = tmp[7]*tmp[8];
	tmp[10] = sinf(uav_theta);
	tmp[11] = cosf(uav_psi);
	tmp[12] = tmp[0]*tmp[11];
	tmp[13] = tmp[10]*tmp[12] + tmp[9];
	tmp[14] = tmp[11]*tmp[7];
	tmp[15] = tmp[0]*tmp[10]*tmp[8] - tmp[14];
	tmp[16] = sinf(REMOTE_SENSING_ARUCO_PHI);
	tmp[17] = tmp[16]*tmp[4];
	tmp[18] = -tmp[13]*tmp[6] + tmp[15]*tmp[17] + tmp[2]*tmp[5];
	tmp[19] = sinf(REMOTE_SENSING_ARUCO_PSI);
	tmp[20] = tmp[13]*tmp[4];
	tmp[21] = cosf(REMOTE_SENSING_ARUCO_PSI);
	tmp[22] = tmp[16]*tmp[21];
	tmp[23] = tmp[19]*tmp[3]*tmp[6] - tmp[22];
	tmp[24] = tmp[21]*tmp[3];
	tmp[25] = tmp[16]*tmp[19];
	tmp[26] = tmp[24] + tmp[25]*tmp[6];
	tmp[27] = tmp[15]*tmp[26] + tmp[19]*tmp[20] + tmp[23]*tmp[2];
	tmp[28] = tmp[24]*tmp[6] + tmp[25];
	tmp[29] = -tmp[19]*tmp[3] + tmp[22]*tmp[6];
	tmp[30] = tmp[15]*tmp[29] + tmp[20]*tmp[21] + tmp[28]*tmp[2];
	tmp[31] = P[0]*tmp[18] + P[1]*tmp[27] + P[3]*tmp[30];
	tmp[32] = P[1]*tmp[18] + P[2]*tmp[27] + P[4]*tmp[30];
	tmp[33] = P[3]*tmp[18] + P[4]*tmp[27] + P[5]*tmp[30];
	tmp[34] = R[0] + tmp[18]*tmp[31] + tmp[27]*tmp[32] + tmp[30]*tmp[33];
	tmp[35] = 1.0/tmp[34];
	tmp[36] = tmp[11]*tmp[1];
	tmp[37] = -tmp[10]*tmp[5] + tmp[16]*tmp[1]*tmp[4]*tmp[8] - tmp[36]*tmp[6];
	tmp[38] = tmp[36]*tmp[4];
	tmp[39] = tmp[1]*tmp[8];
	tmp[40] = -tmp[10]*tmp[23] + tmp[19]*tmp[38] + tmp[26]*tmp[39];
	tmp[41] = -tmp[10]*tmp[28] + tmp[21]*tmp[38] + tmp[29]*tmp[39];
	tmp[42] = P[0]*tmp[37] + P[1]*tmp[40] + P[3]*tmp[41];
	tmp[43] = P[1]*tmp[37] + P[2]*tmp[40] + P[4]*tmp[41];
	tmp[44] = P[3]*tmp[37] + P[4]*tmp[40] + P[5]*tmp[41];
	tmp[45] = tmp[18]*tmp[42] + tmp[27]*tmp[43] + tmp[30]*tmp[44];
	tmp[46] = tmp[35]*tmp[45];
	tmp[47] = tmp[1]*tmp[7];
	tmp[48] = -tmp[0]*tmp[8] + tmp[10]*tmp[14];
	tmp[49] = tmp[10]*tmp[9] + tmp[12];
	tmp[50] = tmp[17]*tmp[49] + tmp[47]*tmp[5] - tmp[48]*tmp[6];
	tmp[51] = tmp[48]*tmp[4];
	tmp[52] = tmp[19]*tmp[51] + tmp[23]*tmp[47] + tmp[26]*tmp[49];
	tmp[53] = tmp[21]*tmp[51] + tmp[28]*tmp[47] + tmp[29]*tmp[49];
	tmp[54] = P[0]*tmp[50] + P[1]*tmp[52] + P[3]*tmp[53];
	tmp[55] = P[1]*tmp[50] + P[2]*tmp[52] + P[4]*tmp[53];
	tmp[56] = P[3]*tmp[50] + P[4]*tmp[52] + P[5]*tmp[53];
	tmp[57] = tmp[18]*tmp[54] + tmp[27]*tmp[55] + tmp[30]*tmp[56];
	tmp[58] = tmp[35]*tmp[57];
	tmp[59] = -tmp[31]*tmp[58] + tmp[54];
	tmp[60] = R[1] - tmp[35]*powf(tmp[57], 2) + tmp[50]*tmp[54] + tmp[52]*tmp[55] + tmp[53]*tmp[56];
	tmp[61] = 1.0/tmp[60];
	tmp[62] = tmp[42]*tmp[50] + tmp[43]*tmp[52] + tmp[44]*tmp[53] - tmp[45]*tmp[58];
	tmp[63] = tmp[61]*tmp[62];
	tmp[64] = -tmp[31]*tmp[46] + tmp[42] - tmp[59]*tmp[63];
	tmp[65] = 1.0/(R[2] - tmp[35]*powf(tmp[45], 2) + tmp[37]*tmp[42] + tmp[40]*tmp[43] + tmp[41]*tmp[44] - tmp[61]*powf(tmp[62], 2));
	tmp[66] = tmp[65]*(REMOTE_SENSING_ARUCO_BODY_OFFSET_X*tmp[10] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Y*tmp[39] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Z*tmp[36] - X[0]*tmp[37] - X[1]*tmp[40] - X[2]*tmp[41] + Z[2]);
	tmp[67] = powf(tmp[60], -1.0/2.0);
	tmp[68] = tmp[64]*tmp[65];
	tmp[69] = tmp[62]*tmp[67];
	tmp[70] = tmp[59]*tmp[67] - tmp[68]*tmp[69];
	tmp[71] = tmp[67]*(-REMOTE_SENSING_ARUCO_BODY_OFFSET_X*tmp[47] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Y*tmp[49] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Z*tmp[48] - X[0]*tmp[50] - X[1]*tmp[52] - X[2]*tmp[53] + Z[1]);
	tmp[72] = powf(tmp[34], -1.0/2.0);
	tmp[73] = tmp[45]*tmp[72];
	tmp[74] = tmp[67]*tmp[70];
	tmp[75] = tmp[57]*tmp[72];
	tmp[76] = tmp[31]*tmp[72] - tmp[68]*tmp[73] - tmp[74]*tmp[75];
	tmp[77] = tmp[72]*(-REMOTE_SENSING_ARUCO_BODY_OFFSET_X*tmp[2] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Y*tmp[15] - REMOTE_SENSING_ARUCO_BODY_OFFSET_Z*tmp[13] - X[0]*tmp[18] - X[1]*tmp[27] - X[2]*tmp[30] + Z[0]);
	tmp[78] = -tmp[32]*tmp[58] + tmp[55];
	tmp[79] = -tmp[32]*tmp[46] + tmp[43] - tmp[63]*tmp[78];
	tmp[80] = tmp[65]*tmp[79];
	tmp[81] = tmp[67]*tmp[78] - tmp[69]*tmp[80];
	tmp[82] = tmp[67]*tmp[81];
	tmp[83] = tmp[32]*tmp[72] - tmp[73]*tmp[80] - tmp[75]*tmp[82];
	tmp[84] = -tmp[33]*tmp[58] + tmp[56];
	tmp[85] = -tmp[33]*tmp[46] + tmp[44] - tmp[63]*tmp[84];
	tmp[86] = tmp[65]*tmp[85];
	tmp[87] = tmp[67]*tmp[84] - tmp[69]*tmp[86];
	tmp[88] = tmp[67]*tmp[87];
	tmp[89] = tmp[33]*tmp[72] - tmp[73]*tmp[86] - tmp[75]*tmp[88];
	tmp[90] = P[6]*tmp[18] + P[7]*tmp[27] + P[8]*tmp[30];
	tmp[91] = P[6]*tmp[50] + P[7]*tmp[52] + P[8]*tmp[53] - tmp[58]*tmp[90];
	tmp[92] = P[6]*tmp[37] + P[7]*tmp[40] + P[8]*tmp[41] - tmp[46]*tmp[90] - tmp[63]*tmp[91];
	tmp[93] = tmp[65]*tmp[92];
	tmp[94] = tmp[67]*tmp[91] - tmp[69]*tmp[93];
	tmp[95] = tmp[67]*tmp[94];
	tmp[96] = tmp[72]*tmp[90] - tmp[73]*tmp[93] - tmp[75]*tmp[95];
	tmp[97] = P[10]*tmp[18] + P[11]*tmp[27] + P[12]*tmp[30];
	tmp[98] = P[10]*tmp[50] + P[11]*tmp[52] + P[12]*tmp[53] - tmp[58]*tmp[97];
	tmp[99] = P[10]*tmp[37] + P[11]*tmp[40] + P[12]*tmp[41] - tmp[46]*tmp[97] - tmp[63]*tmp[98];
	tmp[100] = tmp[65]*tmp[99];
	tmp[101] = -tmp[100]*tmp[69] + tmp[67]*tmp[98];
	tmp[102] = tmp[101]*tmp[67];
	tmp[103] = -tmp[100]*tmp[73] - tmp[102]*tmp[75] + tmp[72]*tmp[97];
	tmp[104] = P[15]*tmp[18] + P[16]*tmp[27] + P[17]*tmp[30];
	tmp[105] = P[15]*tmp[50] + P[16]*tmp[52] + P[17]*tmp[53] - tmp[104]*tmp[58];
	tmp[106] = P[15]*tmp[37] + P[16]*tmp[40] + P[17]*tmp[41] - tmp[104]*tmp[46] - tmp[105]*tmp[63];
	tmp[107] = tmp[106]*tmp[65];
	tmp[108] = tmp[105]*tmp[67] - tmp[107]*tmp[69];
	tmp[109] = tmp[108]*tmp[67];
	tmp[110] = tmp[104]*tmp[72] - tmp[107]*tmp[73] - tmp[109]*tmp[75];
	tmp[111] = P[21]*tmp[18] + P[22]*tmp[27] + P[23]*tmp[30];
	tmp[112] = P[21]*tmp[50] + P[22]*tmp[52] + P[23]*tmp[53] - tmp[111]*tmp[58];
	tmp[113] = P[21]*tmp[37] + P[22]*tmp[40] + P[23]*tmp[41] - tmp[111]*tmp[46] - tmp[112]*tmp[63];
	tmp[114] = tmp[113]*tmp[65];
	tmp[115] = tmp[112]*tmp[67] - tmp[114]*tmp[69];
	tmp[116] = tmp[115]*tmp[67];
	tmp[117] = tmp[111]*tmp[72] - tmp[114]*tmp[73] - tmp[116]*tmp[75];
	tmp[118] = P[28]*tmp[18] + P[29]*tmp[27] + P[30]*tmp[30];
	tmp[119] = P[28]*tmp[50] + P[29]*tmp[52] + P[30]*tmp[53] - tmp[118]*tmp[58];
	tmp[120] = P[28]*tmp[37] + P[29]*tmp[40] + P[30]*tmp[41] - tmp[118]*tmp[46] - tmp[119]*tmp[63];
	tmp[121] = tmp[120]*tmp[65];
	tmp[122] = tmp[119]*tmp[67] - tmp[121]*tmp[69];
	tmp[123] = tmp[122]*tmp[67];
	tmp[124] = tmp[118]*tmp[72] - tmp[121]*tmp[73] - tmp[123]*tmp[75];
	tmp[125] = P[36]*tmp[18] + P[37]*tmp[27] + P[38]*tmp[30];
	tmp[126] = P[36]*tmp[50] + P[37]*tmp[52] + P[38]*tmp[53] - tmp[125]*tmp[58];
	tmp[127] = P[36]*tmp[37] + P[37]*tmp[40] + P[38]*tmp[41] - tmp[125]*tmp[46] - tmp[126]*tmp[63];
	tmp[128] = tmp[127]*tmp[65];
	tmp[129] = tmp[126]*tmp[67] - tmp[128]*tmp[69];
	tmp[130] = tmp[129]*tmp[67];
	tmp[131] = tmp[125]*tmp[72] - tmp[128]*tmp[73] - tmp[130]*tmp[75];
	tmp[132] = tmp[72]*tmp[76];
	tmp[133] = tmp[72]*tmp[83];
	tmp[134] = -tmp[133]*tmp[18] - tmp[37]*tmp[80] - tmp[50]*tmp[82];
	tmp[135] = -tmp[133]*tmp[30] - tmp[41]*tmp[80] - tmp[53]*tmp[82];
	tmp[136] = -tmp[133]*tmp[27] - tmp[40]*tmp[80] - tmp[52]*tmp[82] + 1;
	tmp[137] = tmp[72]*tmp[89];
	tmp[138] = -tmp[137]*tmp[18] - tmp[37]*tmp[86] - tmp[50]*tmp[88];
	tmp[139] = -tmp[137]*tmp[27] - tmp[40]*tmp[86] - tmp[52]*tmp[88];
	tmp[140] = -tmp[137]*tmp[30] - tmp[41]*tmp[86] - tmp[53]*tmp[88] + 1;
	tmp[141] = tmp[72]*tmp[96];
	tmp[142] = -tmp[141]*tmp[18] - tmp[37]*tmp[93] - tmp[50]*tmp[95];
	tmp[143] = -tmp[141]*tmp[27] - tmp[40]*tmp[93] - tmp[52]*tmp[95];
	tmp[144] = -tmp[141]*tmp[30] - tmp[41]*tmp[93] - tmp[53]*tmp[95];
	tmp[145] = tmp[103]*tmp[72];
	tmp[146] = -tmp[100]*tmp[37] - tmp[102]*tmp[50] - tmp[145]*tmp[18];
	tmp[147] = -tmp[100]*tmp[40] - tmp[102]*tmp[52] - tmp[145]*tmp[27];
	tmp[148] = -tmp[100]*tmp[41] - tmp[102]*tmp[53] - tmp[145]*tmp[30];
	tmp[149] = tmp[110]*tmp[72];
	tmp[150] = -tmp[107]*tmp[37] - tmp[109]*tmp[50] - tmp[149]*tmp[18];
	tmp[151] = -tmp[107]*tmp[40] - tmp[109]*tmp[52] - tmp[149]*tmp[27];
	tmp[152] = -tmp[107]*tmp[41] - tmp[109]*tmp[53] - tmp[149]*tmp[30];
	tmp[153] = tmp[117]*tmp[72];
	tmp[154] = -tmp[114]*tmp[37] - tmp[116]*tmp[50] - tmp[153]*tmp[18];
	tmp[155] = -tmp[114]*tmp[40] - tmp[116]*tmp[52] - tmp[153]*tmp[27];
	tmp[156] = -tmp[114]*tmp[41] - tmp[116]*tmp[53] - tmp[153]*tmp[30];
	tmp[157] = tmp[124]*tmp[72];
	tmp[158] = -tmp[121]*tmp[37] - tmp[123]*tmp[50] - tmp[157]*tmp[18];
	tmp[159] = -tmp[121]*tmp[40] - tmp[123]*tmp[52] - tmp[157]*tmp[27];
	tmp[160] = -tmp[121]*tmp[41] - tmp[123]*tmp[53] - tmp[157]*tmp[30];
	tmp[161] = tmp[131]*tmp[72];
	tmp[162] = -tmp[128]*tmp[37] - tmp[130]*tmp[50] - tmp[161]*tmp[18];
	tmp[163] = -tmp[128]*tmp[40] - tmp[130]*tmp[52] - tmp[161]*tmp[27];
	tmp[164] = -tmp[128]*tmp[41] - tmp[130]*tmp[53] - tmp[161]*tmp[30];
	X_new[0] = X[0] + tmp[64]*tmp[66] + tmp[70]*tmp[71] + tmp[76]*tmp[77];
	X_new[1] = X[1] + tmp[66]*tmp[79] + tmp[71]*tmp[81] + tmp[77]*tmp[83];
	X_new[2] = X[2] + tmp[66]*tmp[85] + tmp[71]*tmp[87] + tmp[77]*tmp[89];
	X_new[3] = X[3] + tmp[66]*tmp[92] + tmp[71]*tmp[94] + tmp[77]*tmp[96];
	X_new[4] = X[4] + tmp[101]*tmp[71] + tmp[103]*tmp[77] + tmp[66]*tmp[99];
	X_new[5] = X[5] + tmp[106]*tmp[66] + tmp[108]*tmp[71] + tmp[110]*tmp[77];
	X_new[6] = X[6] + tmp[113]*tmp[66] + tmp[115]*tmp[71] + tmp[117]*tmp[77];
	X_new[7] = X[7] + tmp[120]*tmp[66] + tmp[122]*tmp[71] + tmp[124]*tmp[77];
	X_new[8] = X[8] + tmp[127]*tmp[66] + tmp[129]*tmp[71] + tmp[131]*tmp[77];
	P_new[0] = P[0]*(-tmp[132]*tmp[18] - tmp[37]*tmp[68] - tmp[50]*tmp[74] + 1) + P[1]*(-tmp[132]*tmp[27] - tmp[40]*tmp[68] - tmp[52]*tmp[74]) + P[3]*(-tmp[132]*tmp[30] - tmp[41]*tmp[68] - tmp[53]*tmp[74]);
	P_new[1] = P[0]*tmp[134] + P[1]*tmp[136] + P[3]*tmp[135];
	P_new[2] = P[1]*tmp[134] + P[2]*tmp[136] + P[4]*tmp[135];
	P_new[3] = P[0]*tmp[138] + P[1]*tmp[139] + P[3]*tmp[140];
	P_new[4] = P[1]*tmp[138] + P[2]*tmp[139] + P[4]*tmp[140];
	P_new[5] = P[3]*tmp[138] + P[4]*tmp[139] + P[5]*tmp[140];
	P_new[6] = P[0]*tmp[142] + P[1]*tmp[143] + P[3]*tmp[144] + P[6];
	P_new[7] = P[1]*tmp[142] + P[2]*tmp[143] + P[4]*tmp[144] + P[7];
	P_new[8] = P[3]*tmp[142] + P[4]*tmp[143] + P[5]*tmp[144] + P[8];
	P_new[9] = P[6]*tmp[142] + P[7]*tmp[143] + P[8]*tmp[144] + P[9];
	P_new[10] = P[0]*tmp[146] + P[10] + P[1]*tmp[147] + P[3]*tmp[148];
	P_new[11] = P[11] + P[1]*tmp[146] + P[2]*tmp[147] + P[4]*tmp[148];
	P_new[12] = P[12] + P[3]*tmp[146] + P[4]*tmp[147] + P[5]*tmp[148];
	P_new[13] = P[13] + P[6]*tmp[146] + P[7]*tmp[147] + P[8]*tmp[148];
	P_new[14] = P[10]*tmp[146] + P[11]*tmp[147] + P[12]*tmp[148] + P[14];
	P_new[15] = P[0]*tmp[150] + P[15] + P[1]*tmp[151] + P[3]*tmp[152];
	P_new[16] = P[16] + P[1]*tmp[150] + P[2]*tmp[151] + P[4]*tmp[152];
	P_new[17] = P[17] + P[3]*tmp[150] + P[4]*tmp[151] + P[5]*tmp[152];
	P_new[18] = P[18] + P[6]*tmp[150] + P[7]*tmp[151] + P[8]*tmp[152];
	P_new[19] = P[10]*tmp[150] + P[11]*tmp[151] + P[12]*tmp[152] + P[19];
	P_new[20] = P[15]*tmp[150] + P[16]*tmp[151] + P[17]*tmp[152] + P[20];
	P_new[21] = P[0]*tmp[154] + P[1]*tmp[155] + P[21] + P[3]*tmp[156];
	P_new[22] = P[1]*tmp[154] + P[22] + P[2]*tmp[155] + P[4]*tmp[156];
	P_new[23] = P[23] + P[3]*tmp[154] + P[4]*tmp[155] + P[5]*tmp[156];
	P_new[24] = P[24] + P[6]*tmp[154] + P[7]*tmp[155] + P[8]*tmp[156];
	P_new[25] = P[10]*tmp[154] + P[11]*tmp[155] + P[12]*tmp[156] + P[25];
	P_new[26] = P[15]*tmp[154] + P[16]*tmp[155] + P[17]*tmp[156] + P[26];
	P_new[27] = P[21]*tmp[154] + P[22]*tmp[155] + P[23]*tmp[156] + P[27];
	P_new[28] = P[0]*tmp[158] + P[1]*tmp[159] + P[28] + P[3]*tmp[160];
	P_new[29] = P[1]*tmp[158] + P[29] + P[2]*tmp[159] + P[4]*tmp[160];
	P_new[30] = P[30] + P[3]*tmp[158] + P[4]*tmp[159] + P[5]*tmp[160];
	P_new[31] = P[31] + P[6]*tmp[158] + P[7]*tmp[159] + P[8]*tmp[160];
	P_new[32] = P[10]*tmp[158] + P[11]*tmp[159] + P[12]*tmp[160] + P[32];
	P_new[33] = P[15]*tmp[158] + P[16]*tmp[159] + P[17]*tmp[160] + P[33];
	P_new[34] = P[21]*tmp[158] + P[22]*tmp[159] + P[23]*tmp[160] + P[34];
	P_new[35] = P[28]*tmp[158] + P[29]*tmp[159] + P[30]*tmp[160] + P[35];
	P_new[36] = P[0]*tmp[162] + P[1]*tmp[163] + P[36] + P[3]*tmp[164];
	P_new[37] = P[1]*tmp[162] + P[2]*tmp[163] + P[37] + P[4]*tmp[164];
	P_new[38] = P[38] + P[3]*tmp[162] + P[4]*tmp[163] + P[5]*tmp[164];
	P_new[39] = P[39] + P[6]*tmp[162] + P[7]*tmp[163] + P[8]*tmp[164];
	P_new[40] = P[10]*tmp[162] + P[11]*tmp[163] + P[12]*tmp[164] + P[40];
	P_new[41] = P[15]*tmp[162] + P[16]*tmp[163] + P[17]*tmp[164] + P[41];
	P_new[42] = P[21]*tmp[162] + P[22]*tmp[163] + P[23]*tmp[164] + P[42];
	P_new[43] = P[28]*tmp[162] + P[29]*tmp[163] + P[30]*tmp[164] + P[43];
	P_new[44] = P[36]*tmp[162] + P[37]*tmp[163] + P[38]*tmp[164] + P[44];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_update_sixdof(struct FloatVect3 sixdof_pos, struct FloatQuat sixdof_quat) {
    
    // Prepare measurement vector from measurements
	float Z[N_MEASUREMENTS_SIXDOF];
	float *HX = ekf_last_HX_sixdof;
    Z[0] = sixdof_pos.x;
    Z[1] = sixdof_pos.y;
    Z[2] = sixdof_pos.z;
    Z[3] = sixdof_quat.qi;
    Z[4] = sixdof_quat.qx;
    Z[5] = sixdof_quat.qy;
    Z[6] = sixdof_quat.qz;
    
    // Set R pointer to SixDOF measurement noise
    R = ekf_R_sixdof;
    // Read UAV attitude from state estimation interface
    const struct FloatEulers *ned_to_body = stateGetNedToBodyEulers_f();
    const float uav_phi = ned_to_body->phi;
    const float uav_theta = ned_to_body->theta;
    const float uav_psi = ned_to_body->psi;
    // UPDATE STEP X_new, P_new = ...
    tmp[0] = cosf(uav_phi);
	tmp[1] = cosf(uav_theta);
	tmp[2] = tmp[0]*tmp[1];
	tmp[3] = cosf(REMOTE_SENSING_FALCON_PHI);
	tmp[4] = cosf(REMOTE_SENSING_FALCON_THETA);
	tmp[5] = tmp[3]*tmp[4];
	tmp[6] = sinf(REMOTE_SENSING_FALCON_THETA);
	tmp[7] = sinf(uav_phi);
	tmp[8] = sinf(uav_psi);
	tmp[9] = tmp[7]*tmp[8];
	tmp[10] = sinf(uav_theta);
	tmp[11] = cosf(uav_psi);
	tmp[12] = tmp[0]*tmp[11];
	tmp[13] = tmp[10]*tmp[12] + tmp[9];
	tmp[14] = tmp[11]*tmp[7];
	tmp[15] = tmp[0]*tmp[10]*tmp[8] - tmp[14];
	tmp[16] = sinf(REMOTE_SENSING_FALCON_PHI);
	tmp[17] = tmp[16]*tmp[4];
	tmp[18] = -tmp[13]*tmp[6] + tmp[15]*tmp[17] + tmp[2]*tmp[5];
	tmp[19] = -tmp[18];
	tmp[20] = sinf(REMOTE_SENSING_FALCON_PSI);
	tmp[21] = tmp[13]*tmp[4];
	tmp[22] = cosf(REMOTE_SENSING_FALCON_PSI);
	tmp[23] = tmp[16]*tmp[22];
	tmp[24] = tmp[20]*tmp[3]*tmp[6] - tmp[23];
	tmp[25] = tmp[22]*tmp[3];
	tmp[26] = tmp[16]*tmp[20];
	tmp[27] = tmp[25] + tmp[26]*tmp[6];
	tmp[28] = tmp[15]*tmp[27] + tmp[20]*tmp[21] + tmp[24]*tmp[2];
	tmp[29] = -tmp[28];
	tmp[30] = tmp[25]*tmp[6] + tmp[26];
	tmp[31] = -tmp[20]*tmp[3] + tmp[23]*tmp[6];
	tmp[32] = tmp[15]*tmp[31] + tmp[21]*tmp[22] + tmp[2]*tmp[30];
	tmp[33] = -tmp[32];
	tmp[34] = P[0]*tmp[19] + P[1]*tmp[29] + P[3]*tmp[33];
	tmp[35] = P[1]*tmp[19] + P[2]*tmp[29] + P[4]*tmp[33];
	tmp[36] = P[3]*tmp[19] + P[4]*tmp[29] + P[5]*tmp[33];
	tmp[37] = R[0] + tmp[19]*tmp[34] + tmp[29]*tmp[35] + tmp[33]*tmp[36];
	tmp[38] = 1.0/tmp[37];
	tmp[39] = tmp[11]*tmp[1];
	tmp[40] = tmp[1]*tmp[8];
	tmp[41] = tmp[10]*tmp[5] - tmp[17]*tmp[40] + tmp[39]*tmp[6];
	tmp[42] = tmp[39]*tmp[4];
	tmp[43] = -tmp[10]*tmp[24] + tmp[20]*tmp[42] + tmp[27]*tmp[40];
	tmp[44] = -tmp[43];
	tmp[45] = -tmp[10]*tmp[30] + tmp[22]*tmp[42] + tmp[31]*tmp[40];
	tmp[46] = -tmp[45];
	tmp[47] = P[0]*tmp[41] + P[1]*tmp[44] + P[3]*tmp[46];
	tmp[48] = P[1]*tmp[41] + P[2]*tmp[44] + P[4]*tmp[46];
	tmp[49] = P[3]*tmp[41] + P[4]*tmp[44] + P[5]*tmp[46];
	tmp[50] = tmp[19]*tmp[47] + tmp[29]*tmp[48] + tmp[33]*tmp[49];
	tmp[51] = tmp[38]*tmp[50];
	tmp[52] = tmp[1]*tmp[7];
	tmp[53] = -tmp[0]*tmp[8] + tmp[10]*tmp[14];
	tmp[54] = tmp[10]*tmp[9] + tmp[12];
	tmp[55] = tmp[17]*tmp[54] + tmp[52]*tmp[5] - tmp[53]*tmp[6];
	tmp[56] = -tmp[55];
	tmp[57] = tmp[4]*tmp[53];
	tmp[58] = tmp[20]*tmp[57] + tmp[24]*tmp[52] + tmp[27]*tmp[54];
	tmp[59] = -tmp[58];
	tmp[60] = tmp[22]*tmp[57] + tmp[30]*tmp[52] + tmp[31]*tmp[54];
	tmp[61] = -tmp[60];
	tmp[62] = P[0]*tmp[56] + P[1]*tmp[59] + P[3]*tmp[61];
	tmp[63] = P[1]*tmp[56] + P[2]*tmp[59] + P[4]*tmp[61];
	tmp[64] = P[3]*tmp[56] + P[4]*tmp[59] + P[5]*tmp[61];
	tmp[65] = tmp[19]*tmp[62] + tmp[29]*tmp[63] + tmp[33]*tmp[64];
	tmp[66] = tmp[38]*tmp[65];
	tmp[67] = -tmp[34]*tmp[66] + tmp[62];
	tmp[68] = R[1] - tmp[38]*powf(tmp[65], 2) + tmp[56]*tmp[62] + tmp[59]*tmp[63] + tmp[61]*tmp[64];
	tmp[69] = 1.0/tmp[68];
	tmp[70] = tmp[47]*tmp[56] + tmp[48]*tmp[59] + tmp[49]*tmp[61] - tmp[50]*tmp[66];
	tmp[71] = tmp[69]*tmp[70];
	tmp[72] = -tmp[34]*tmp[51] + tmp[47] - tmp[67]*tmp[71];
	tmp[73] = 1.0/(R[2] - tmp[38]*powf(tmp[50], 2) + tmp[41]*tmp[47] + tmp[44]*tmp[48] + tmp[46]*tmp[49] - tmp[69]*powf(tmp[70], 2));
	tmp[74] = tmp[73]*(REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[10] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[40] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[39] - X[0]*tmp[41] + X[1]*tmp[43] + X[2]*tmp[45] + Z[2]);
	tmp[75] = powf(tmp[68], -1.0/2.0);
	tmp[76] = tmp[72]*tmp[73];
	tmp[77] = tmp[70]*tmp[75];
	tmp[78] = tmp[67]*tmp[75] - tmp[76]*tmp[77];
	tmp[79] = tmp[75]*(-REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[52] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[54] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[53] + X[0]*tmp[55] + X[1]*tmp[58] + X[2]*tmp[60] + Z[1]);
	tmp[80] = powf(tmp[37], -1.0/2.0);
	tmp[81] = tmp[50]*tmp[80];
	tmp[82] = tmp[75]*tmp[78];
	tmp[83] = tmp[65]*tmp[80];
	tmp[84] = tmp[34]*tmp[80] - tmp[76]*tmp[81] - tmp[82]*tmp[83];
	tmp[85] = tmp[80]*(-REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[2] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[15] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[13] + X[0]*tmp[18] + X[1]*tmp[28] + X[2]*tmp[32] + Z[0]);
	tmp[86] = -tmp[35]*tmp[66] + tmp[63];
	tmp[87] = -tmp[35]*tmp[51] + tmp[48] - tmp[71]*tmp[86];
	tmp[88] = tmp[73]*tmp[87];
	tmp[89] = tmp[75]*tmp[86] - tmp[77]*tmp[88];
	tmp[90] = tmp[75]*tmp[89];
	tmp[91] = tmp[35]*tmp[80] - tmp[81]*tmp[88] - tmp[83]*tmp[90];
	tmp[92] = -tmp[36]*tmp[66] + tmp[64];
	tmp[93] = -tmp[36]*tmp[51] + tmp[49] - tmp[71]*tmp[92];
	tmp[94] = tmp[73]*tmp[93];
	tmp[95] = tmp[75]*tmp[92] - tmp[77]*tmp[94];
	tmp[96] = tmp[75]*tmp[95];
	tmp[97] = tmp[36]*tmp[80] - tmp[81]*tmp[94] - tmp[83]*tmp[96];
	tmp[98] = P[6]*tmp[19] + P[7]*tmp[29] + P[8]*tmp[33];
	tmp[99] = P[6]*tmp[56] + P[7]*tmp[59] + P[8]*tmp[61] - tmp[66]*tmp[98];
	tmp[100] = P[6]*tmp[41] + P[7]*tmp[44] + P[8]*tmp[46] - tmp[51]*tmp[98] - tmp[71]*tmp[99];
	tmp[101] = tmp[100]*tmp[73];
	tmp[102] = -tmp[101]*tmp[77] + tmp[75]*tmp[99];
	tmp[103] = tmp[102]*tmp[75];
	tmp[104] = -tmp[101]*tmp[81] - tmp[103]*tmp[83] + tmp[80]*tmp[98];
	tmp[105] = P[10]*tmp[19] + P[11]*tmp[29] + P[12]*tmp[33];
	tmp[106] = P[10]*tmp[56] + P[11]*tmp[59] + P[12]*tmp[61] - tmp[105]*tmp[66];
	tmp[107] = P[10]*tmp[41] + P[11]*tmp[44] + P[12]*tmp[46] - tmp[105]*tmp[51] - tmp[106]*tmp[71];
	tmp[108] = tmp[107]*tmp[73];
	tmp[109] = tmp[106]*tmp[75] - tmp[108]*tmp[77];
	tmp[110] = tmp[109]*tmp[75];
	tmp[111] = tmp[105]*tmp[80] - tmp[108]*tmp[81] - tmp[110]*tmp[83];
	tmp[112] = P[15]*tmp[19] + P[16]*tmp[29] + P[17]*tmp[33];
	tmp[113] = P[15]*tmp[56] + P[16]*tmp[59] + P[17]*tmp[61] - tmp[112]*tmp[66];
	tmp[114] = P[15]*tmp[41] + P[16]*tmp[44] + P[17]*tmp[46] - tmp[112]*tmp[51] - tmp[113]*tmp[71];
	tmp[115] = tmp[114]*tmp[73];
	tmp[116] = tmp[113]*tmp[75] - tmp[115]*tmp[77];
	tmp[117] = tmp[116]*tmp[75];
	tmp[118] = tmp[112]*tmp[80] - tmp[115]*tmp[81] - tmp[117]*tmp[83];
	tmp[119] = P[21]*tmp[19] + P[22]*tmp[29] + P[23]*tmp[33];
	tmp[120] = P[21]*tmp[56] + P[22]*tmp[59] + P[23]*tmp[61] - tmp[119]*tmp[66];
	tmp[121] = P[21]*tmp[41] + P[22]*tmp[44] + P[23]*tmp[46] - tmp[119]*tmp[51] - tmp[120]*tmp[71];
	tmp[122] = tmp[121]*tmp[73];
	tmp[123] = tmp[120]*tmp[75] - tmp[122]*tmp[77];
	tmp[124] = tmp[123]*tmp[75];
	tmp[125] = tmp[119]*tmp[80] - tmp[122]*tmp[81] - tmp[124]*tmp[83];
	tmp[126] = P[28]*tmp[19] + P[29]*tmp[29] + P[30]*tmp[33];
	tmp[127] = P[28]*tmp[56] + P[29]*tmp[59] + P[30]*tmp[61] - tmp[126]*tmp[66];
	tmp[128] = P[28]*tmp[41] + P[29]*tmp[44] + P[30]*tmp[46] - tmp[126]*tmp[51] - tmp[127]*tmp[71];
	tmp[129] = tmp[128]*tmp[73];
	tmp[130] = tmp[127]*tmp[75] - tmp[129]*tmp[77];
	tmp[131] = tmp[130]*tmp[75];
	tmp[132] = tmp[126]*tmp[80] - tmp[129]*tmp[81] - tmp[131]*tmp[83];
	tmp[133] = P[36]*tmp[19] + P[37]*tmp[29] + P[38]*tmp[33];
	tmp[134] = P[36]*tmp[56] + P[37]*tmp[59] + P[38]*tmp[61] - tmp[133]*tmp[66];
	tmp[135] = P[36]*tmp[41] + P[37]*tmp[44] + P[38]*tmp[46] - tmp[133]*tmp[51] - tmp[134]*tmp[71];
	tmp[136] = tmp[135]*tmp[73];
	tmp[137] = tmp[134]*tmp[75] - tmp[136]*tmp[77];
	tmp[138] = tmp[137]*tmp[75];
	tmp[139] = tmp[133]*tmp[80] - tmp[136]*tmp[81] - tmp[138]*tmp[83];
	tmp[140] = tmp[80]*tmp[84];
	tmp[141] = tmp[80]*tmp[91];
	tmp[142] = -tmp[141]*tmp[19] - tmp[41]*tmp[88] - tmp[56]*tmp[90];
	tmp[143] = -tmp[141]*tmp[33] - tmp[46]*tmp[88] - tmp[61]*tmp[90];
	tmp[144] = -tmp[141]*tmp[29] - tmp[44]*tmp[88] - tmp[59]*tmp[90] + 1;
	tmp[145] = tmp[80]*tmp[97];
	tmp[146] = -tmp[145]*tmp[19] - tmp[41]*tmp[94] - tmp[56]*tmp[96];
	tmp[147] = -tmp[145]*tmp[29] - tmp[44]*tmp[94] - tmp[59]*tmp[96];
	tmp[148] = -tmp[145]*tmp[33] - tmp[46]*tmp[94] - tmp[61]*tmp[96] + 1;
	tmp[149] = tmp[104]*tmp[80];
	tmp[150] = -tmp[101]*tmp[41] - tmp[103]*tmp[56] - tmp[149]*tmp[19];
	tmp[151] = -tmp[101]*tmp[44] - tmp[103]*tmp[59] - tmp[149]*tmp[29];
	tmp[152] = -tmp[101]*tmp[46] - tmp[103]*tmp[61] - tmp[149]*tmp[33];
	tmp[153] = tmp[111]*tmp[80];
	tmp[154] = -tmp[108]*tmp[41] - tmp[110]*tmp[56] - tmp[153]*tmp[19];
	tmp[155] = -tmp[108]*tmp[44] - tmp[110]*tmp[59] - tmp[153]*tmp[29];
	tmp[156] = -tmp[108]*tmp[46] - tmp[110]*tmp[61] - tmp[153]*tmp[33];
	tmp[157] = tmp[118]*tmp[80];
	tmp[158] = -tmp[115]*tmp[41] - tmp[117]*tmp[56] - tmp[157]*tmp[19];
	tmp[159] = -tmp[115]*tmp[44] - tmp[117]*tmp[59] - tmp[157]*tmp[29];
	tmp[160] = -tmp[115]*tmp[46] - tmp[117]*tmp[61] - tmp[157]*tmp[33];
	tmp[161] = tmp[125]*tmp[80];
	tmp[162] = -tmp[122]*tmp[41] - tmp[124]*tmp[56] - tmp[161]*tmp[19];
	tmp[163] = -tmp[122]*tmp[44] - tmp[124]*tmp[59] - tmp[161]*tmp[29];
	tmp[164] = -tmp[122]*tmp[46] - tmp[124]*tmp[61] - tmp[161]*tmp[33];
	tmp[165] = tmp[132]*tmp[80];
	tmp[166] = -tmp[129]*tmp[41] - tmp[131]*tmp[56] - tmp[165]*tmp[19];
	tmp[167] = -tmp[129]*tmp[44] - tmp[131]*tmp[59] - tmp[165]*tmp[29];
	tmp[168] = -tmp[129]*tmp[46] - tmp[131]*tmp[61] - tmp[165]*tmp[33];
	tmp[169] = tmp[139]*tmp[80];
	tmp[170] = -tmp[136]*tmp[41] - tmp[138]*tmp[56] - tmp[169]*tmp[19];
	tmp[171] = -tmp[136]*tmp[44] - tmp[138]*tmp[59] - tmp[169]*tmp[29];
	tmp[172] = -tmp[136]*tmp[46] - tmp[138]*tmp[61] - tmp[169]*tmp[33];
	X_new[0] = X[0] + tmp[72]*tmp[74] + tmp[78]*tmp[79] + tmp[84]*tmp[85];
	X_new[1] = X[1] + tmp[74]*tmp[87] + tmp[79]*tmp[89] + tmp[85]*tmp[91];
	X_new[2] = X[2] + tmp[74]*tmp[93] + tmp[79]*tmp[95] + tmp[85]*tmp[97];
	X_new[3] = X[3] + tmp[100]*tmp[74] + tmp[102]*tmp[79] + tmp[104]*tmp[85];
	X_new[4] = X[4] + tmp[107]*tmp[74] + tmp[109]*tmp[79] + tmp[111]*tmp[85];
	X_new[5] = X[5] + tmp[114]*tmp[74] + tmp[116]*tmp[79] + tmp[118]*tmp[85];
	X_new[6] = gps_offset_x + tmp[121]*tmp[74] + tmp[123]*tmp[79] + tmp[125]*tmp[85];
	X_new[7] = gps_offset_y + tmp[128]*tmp[74] + tmp[130]*tmp[79] + tmp[132]*tmp[85];
	X_new[8] = gps_offset_z + tmp[135]*tmp[74] + tmp[137]*tmp[79] + tmp[139]*tmp[85];
	P_new[0] = P[0]*(-tmp[140]*tmp[19] - tmp[41]*tmp[76] - tmp[56]*tmp[82] + 1) + P[1]*(-tmp[140]*tmp[29] - tmp[44]*tmp[76] - tmp[59]*tmp[82]) + P[3]*(-tmp[140]*tmp[33] - tmp[46]*tmp[76] - tmp[61]*tmp[82]);
	P_new[1] = P[0]*tmp[142] + P[1]*tmp[144] + P[3]*tmp[143];
	P_new[2] = P[1]*tmp[142] + P[2]*tmp[144] + P[4]*tmp[143];
	P_new[3] = P[0]*tmp[146] + P[1]*tmp[147] + P[3]*tmp[148];
	P_new[4] = P[1]*tmp[146] + P[2]*tmp[147] + P[4]*tmp[148];
	P_new[5] = P[3]*tmp[146] + P[4]*tmp[147] + P[5]*tmp[148];
	P_new[6] = P[0]*tmp[150] + P[1]*tmp[151] + P[3]*tmp[152] + P[6];
	P_new[7] = P[1]*tmp[150] + P[2]*tmp[151] + P[4]*tmp[152] + P[7];
	P_new[8] = P[3]*tmp[150] + P[4]*tmp[151] + P[5]*tmp[152] + P[8];
	P_new[9] = P[6]*tmp[150] + P[7]*tmp[151] + P[8]*tmp[152] + P[9];
	P_new[10] = P[0]*tmp[154] + P[10] + P[1]*tmp[155] + P[3]*tmp[156];
	P_new[11] = P[11] + P[1]*tmp[154] + P[2]*tmp[155] + P[4]*tmp[156];
	P_new[12] = P[12] + P[3]*tmp[154] + P[4]*tmp[155] + P[5]*tmp[156];
	P_new[13] = P[13] + P[6]*tmp[154] + P[7]*tmp[155] + P[8]*tmp[156];
	P_new[14] = P[10]*tmp[154] + P[11]*tmp[155] + P[12]*tmp[156] + P[14];
	P_new[15] = P[0]*tmp[158] + P[15] + P[1]*tmp[159] + P[3]*tmp[160];
	P_new[16] = P[16] + P[1]*tmp[158] + P[2]*tmp[159] + P[4]*tmp[160];
	P_new[17] = P[17] + P[3]*tmp[158] + P[4]*tmp[159] + P[5]*tmp[160];
	P_new[18] = P[18] + P[6]*tmp[158] + P[7]*tmp[159] + P[8]*tmp[160];
	P_new[19] = P[10]*tmp[158] + P[11]*tmp[159] + P[12]*tmp[160] + P[19];
	P_new[20] = P[15]*tmp[158] + P[16]*tmp[159] + P[17]*tmp[160] + P[20];
	P_new[21] = P[0]*tmp[162] + P[1]*tmp[163] + P[21] + P[3]*tmp[164];
	P_new[22] = P[1]*tmp[162] + P[22] + P[2]*tmp[163] + P[4]*tmp[164];
	P_new[23] = P[23] + P[3]*tmp[162] + P[4]*tmp[163] + P[5]*tmp[164];
	P_new[24] = P[24] + P[6]*tmp[162] + P[7]*tmp[163] + P[8]*tmp[164];
	P_new[25] = P[10]*tmp[162] + P[11]*tmp[163] + P[12]*tmp[164] + P[25];
	P_new[26] = P[15]*tmp[162] + P[16]*tmp[163] + P[17]*tmp[164] + P[26];
	P_new[27] = P[21]*tmp[162] + P[22]*tmp[163] + P[23]*tmp[164] + P[27];
	P_new[28] = P[0]*tmp[166] + P[1]*tmp[167] + P[28] + P[3]*tmp[168];
	P_new[29] = P[1]*tmp[166] + P[29] + P[2]*tmp[167] + P[4]*tmp[168];
	P_new[30] = P[30] + P[3]*tmp[166] + P[4]*tmp[167] + P[5]*tmp[168];
	P_new[31] = P[31] + P[6]*tmp[166] + P[7]*tmp[167] + P[8]*tmp[168];
	P_new[32] = P[10]*tmp[166] + P[11]*tmp[167] + P[12]*tmp[168] + P[32];
	P_new[33] = P[15]*tmp[166] + P[16]*tmp[167] + P[17]*tmp[168] + P[33];
	P_new[34] = P[21]*tmp[166] + P[22]*tmp[167] + P[23]*tmp[168] + P[34];
	P_new[35] = P[28]*tmp[166] + P[29]*tmp[167] + P[30]*tmp[168] + P[35];
	P_new[36] = P[0]*tmp[170] + P[1]*tmp[171] + P[36] + P[3]*tmp[172];
	P_new[37] = P[1]*tmp[170] + P[2]*tmp[171] + P[37] + P[4]*tmp[172];
	P_new[38] = P[38] + P[3]*tmp[170] + P[4]*tmp[171] + P[5]*tmp[172];
	P_new[39] = P[39] + P[6]*tmp[170] + P[7]*tmp[171] + P[8]*tmp[172];
	P_new[40] = P[10]*tmp[170] + P[11]*tmp[171] + P[12]*tmp[172] + P[40];
	P_new[41] = P[15]*tmp[170] + P[16]*tmp[171] + P[17]*tmp[172] + P[41];
	P_new[42] = P[21]*tmp[170] + P[22]*tmp[171] + P[23]*tmp[172] + P[42];
	P_new[43] = P[28]*tmp[170] + P[29]*tmp[171] + P[30]*tmp[172] + P[43];
	P_new[44] = P[36]*tmp[170] + P[37]*tmp[171] + P[38]*tmp[172] + P[44];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_update_sixdof_pos_var(struct FloatVect3 sixdof_pos_var) {
    // Read UAV attitude from state estimation interface
    const struct FloatEulers *ned_to_body = stateGetNedToBodyEulers_f();
    const float uav_phi = ned_to_body->phi;
    const float uav_theta = ned_to_body->theta;
    const float uav_psi = ned_to_body->psi;

    // copy variances
    const float sixdof_pos_var_x = sixdof_pos_var.x;
    const float sixdof_pos_var_y = sixdof_pos_var.y;
    const float sixdof_pos_var_z = sixdof_pos_var.z;
    
    // Convert SixDOF position variance to NED frame
    float sixdof_var_ned[3];
    tmp[0] = cosf(uav_phi);
	tmp[1] = cosf(uav_theta);
	tmp[2] = tmp[0]*tmp[1];
	tmp[3] = cosf(REMOTE_SENSING_FALCON_PHI);
	tmp[4] = cosf(REMOTE_SENSING_FALCON_THETA);
	tmp[5] = tmp[3]*tmp[4];
	tmp[6] = sinf(REMOTE_SENSING_FALCON_THETA);
	tmp[7] = sinf(uav_phi);
	tmp[8] = sinf(uav_psi);
	tmp[9] = tmp[7]*tmp[8];
	tmp[10] = sinf(uav_theta);
	tmp[11] = cosf(uav_psi);
	tmp[12] = tmp[0]*tmp[11];
	tmp[13] = tmp[10]*tmp[12] + tmp[9];
	tmp[14] = tmp[11]*tmp[7];
	tmp[15] = tmp[0]*tmp[10]*tmp[8] - tmp[14];
	tmp[16] = sinf(REMOTE_SENSING_FALCON_PHI);
	tmp[17] = tmp[16]*tmp[4];
	tmp[18] = sinf(REMOTE_SENSING_FALCON_PSI);
	tmp[19] = tmp[13]*tmp[4];
	tmp[20] = cosf(REMOTE_SENSING_FALCON_PSI);
	tmp[21] = tmp[16]*tmp[20];
	tmp[22] = tmp[18]*tmp[3]*tmp[6] - tmp[21];
	tmp[23] = tmp[20]*tmp[3];
	tmp[24] = tmp[16]*tmp[18];
	tmp[25] = tmp[23] + tmp[24]*tmp[6];
	tmp[26] = tmp[23]*tmp[6] + tmp[24];
	tmp[27] = -tmp[18]*tmp[3] + tmp[21]*tmp[6];
	tmp[28] = tmp[1]*tmp[7];
	tmp[29] = -tmp[0]*tmp[8] + tmp[10]*tmp[14];
	tmp[30] = tmp[10]*tmp[9] + tmp[12];
	tmp[31] = tmp[29]*tmp[4];
	tmp[32] = tmp[11]*tmp[1];
	tmp[33] = tmp[32]*tmp[4];
	tmp[34] = tmp[1]*tmp[8];
	sixdof_var_ned[0] = -sixdof_pos_var_x*(-tmp[13]*tmp[6] + tmp[15]*tmp[17] + tmp[2]*tmp[5]) - sixdof_pos_var_y*(tmp[15]*tmp[25] + tmp[18]*tmp[19] + tmp[22]*tmp[2]) - sixdof_pos_var_z*(tmp[15]*tmp[27] + tmp[19]*tmp[20] + tmp[26]*tmp[2]);
	sixdof_var_ned[1] = -sixdof_pos_var_x*(tmp[17]*tmp[30] + tmp[28]*tmp[5] - tmp[29]*tmp[6]) - sixdof_pos_var_y*(tmp[18]*tmp[31] + tmp[22]*tmp[28] + tmp[25]*tmp[30]) - sixdof_pos_var_z*(tmp[20]*tmp[31] + tmp[26]*tmp[28] + tmp[27]*tmp[30]);
	sixdof_var_ned[2] = -sixdof_pos_var_x*(-tmp[10]*tmp[5] + tmp[16]*tmp[1]*tmp[4]*tmp[8] - tmp[32]*tmp[6]) - sixdof_pos_var_y*(-tmp[10]*tmp[22] + tmp[18]*tmp[33] + tmp[25]*tmp[34]) - sixdof_pos_var_z*(-tmp[10]*tmp[26] + tmp[20]*tmp[33] + tmp[27]*tmp[34]);
    // Update covariance matrix P with SixDOF position variance
    ekf_R_sixdof[0] = sixdof_var_ned[0];
    ekf_R_sixdof[1] = sixdof_var_ned[1];
    ekf_R_sixdof[2] = sixdof_var_ned[2];
}

void ekf_update_relbeacon(struct FloatVect3 relbeacon_pos) {
    
    // Prepare measurement vector from measurements
	float Z[N_MEASUREMENTS_RELBEACON];
	float *HX = ekf_last_HX_relbeacon;
    Z[0] = relbeacon_pos.x;
    Z[1] = relbeacon_pos.y;
    Z[2] = relbeacon_pos.z;
    
    // Set R pointer to Relbeacon measurement noise
    R = ekf_R_relbeacon;
    // Read UAV attitude from state estimation interface
    const struct FloatEulers *ned_to_body = stateGetNedToBodyEulers_f();
    const float uav_phi = ned_to_body->phi;
    const float uav_theta = ned_to_body->theta;
    const float uav_psi = ned_to_body->psi;
    // UPDATE STEP X_new, P_new = ...
    tmp[0] = cosf(uav_phi);
	tmp[1] = cosf(uav_theta);
	tmp[2] = tmp[0]*tmp[1];
	tmp[3] = cosf(REMOTE_SENSING_FALCON_PHI);
	tmp[4] = cosf(REMOTE_SENSING_FALCON_THETA);
	tmp[5] = tmp[3]*tmp[4];
	tmp[6] = sinf(REMOTE_SENSING_FALCON_THETA);
	tmp[7] = sinf(uav_phi);
	tmp[8] = sinf(uav_psi);
	tmp[9] = tmp[7]*tmp[8];
	tmp[10] = sinf(uav_theta);
	tmp[11] = cosf(uav_psi);
	tmp[12] = tmp[0]*tmp[11];
	tmp[13] = tmp[10]*tmp[12] + tmp[9];
	tmp[14] = tmp[11]*tmp[7];
	tmp[15] = tmp[0]*tmp[10]*tmp[8] - tmp[14];
	tmp[16] = sinf(REMOTE_SENSING_FALCON_PHI);
	tmp[17] = tmp[16]*tmp[4];
	tmp[18] = -tmp[13]*tmp[6] + tmp[15]*tmp[17] + tmp[2]*tmp[5];
	tmp[19] = sinf(REMOTE_SENSING_FALCON_PSI);
	tmp[20] = tmp[13]*tmp[4];
	tmp[21] = cosf(REMOTE_SENSING_FALCON_PSI);
	tmp[22] = tmp[16]*tmp[21];
	tmp[23] = tmp[19]*tmp[3]*tmp[6] - tmp[22];
	tmp[24] = tmp[21]*tmp[3];
	tmp[25] = tmp[16]*tmp[19];
	tmp[26] = tmp[24] + tmp[25]*tmp[6];
	tmp[27] = tmp[15]*tmp[26] + tmp[19]*tmp[20] + tmp[23]*tmp[2];
	tmp[28] = tmp[24]*tmp[6] + tmp[25];
	tmp[29] = -tmp[19]*tmp[3] + tmp[22]*tmp[6];
	tmp[30] = tmp[15]*tmp[29] + tmp[20]*tmp[21] + tmp[28]*tmp[2];
	tmp[31] = P[0]*tmp[18] + P[1]*tmp[27] + P[3]*tmp[30];
	tmp[32] = P[1]*tmp[18] + P[2]*tmp[27] + P[4]*tmp[30];
	tmp[33] = P[3]*tmp[18] + P[4]*tmp[27] + P[5]*tmp[30];
	tmp[34] = R[0] + tmp[18]*tmp[31] + tmp[27]*tmp[32] + tmp[30]*tmp[33];
	tmp[35] = 1.0/tmp[34];
	tmp[36] = tmp[11]*tmp[1];
	tmp[37] = -tmp[10]*tmp[5] + tmp[16]*tmp[1]*tmp[4]*tmp[8] - tmp[36]*tmp[6];
	tmp[38] = tmp[36]*tmp[4];
	tmp[39] = tmp[1]*tmp[8];
	tmp[40] = -tmp[10]*tmp[23] + tmp[19]*tmp[38] + tmp[26]*tmp[39];
	tmp[41] = -tmp[10]*tmp[28] + tmp[21]*tmp[38] + tmp[29]*tmp[39];
	tmp[42] = P[0]*tmp[37] + P[1]*tmp[40] + P[3]*tmp[41];
	tmp[43] = P[1]*tmp[37] + P[2]*tmp[40] + P[4]*tmp[41];
	tmp[44] = P[3]*tmp[37] + P[4]*tmp[40] + P[5]*tmp[41];
	tmp[45] = tmp[18]*tmp[42] + tmp[27]*tmp[43] + tmp[30]*tmp[44];
	tmp[46] = tmp[35]*tmp[45];
	tmp[47] = tmp[1]*tmp[7];
	tmp[48] = -tmp[0]*tmp[8] + tmp[10]*tmp[14];
	tmp[49] = tmp[10]*tmp[9] + tmp[12];
	tmp[50] = tmp[17]*tmp[49] + tmp[47]*tmp[5] - tmp[48]*tmp[6];
	tmp[51] = tmp[48]*tmp[4];
	tmp[52] = tmp[19]*tmp[51] + tmp[23]*tmp[47] + tmp[26]*tmp[49];
	tmp[53] = tmp[21]*tmp[51] + tmp[28]*tmp[47] + tmp[29]*tmp[49];
	tmp[54] = P[0]*tmp[50] + P[1]*tmp[52] + P[3]*tmp[53];
	tmp[55] = P[1]*tmp[50] + P[2]*tmp[52] + P[4]*tmp[53];
	tmp[56] = P[3]*tmp[50] + P[4]*tmp[52] + P[5]*tmp[53];
	tmp[57] = tmp[18]*tmp[54] + tmp[27]*tmp[55] + tmp[30]*tmp[56];
	tmp[58] = tmp[35]*tmp[57];
	tmp[59] = -tmp[31]*tmp[58] + tmp[54];
	tmp[60] = R[1] - tmp[35]*powf(tmp[57], 2) + tmp[50]*tmp[54] + tmp[52]*tmp[55] + tmp[53]*tmp[56];
	tmp[61] = 1.0/tmp[60];
	tmp[62] = tmp[42]*tmp[50] + tmp[43]*tmp[52] + tmp[44]*tmp[53] - tmp[45]*tmp[58];
	tmp[63] = tmp[61]*tmp[62];
	tmp[64] = -tmp[31]*tmp[46] + tmp[42] - tmp[59]*tmp[63];
	tmp[65] = 1.0/(R[2] - tmp[35]*powf(tmp[45], 2) + tmp[37]*tmp[42] + tmp[40]*tmp[43] + tmp[41]*tmp[44] - tmp[61]*powf(tmp[62], 2));
	tmp[66] = tmp[65]*(REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[10] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[39] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[36] - X[0]*tmp[37] - X[1]*tmp[40] - X[2]*tmp[41] + Z[2]);
	tmp[67] = powf(tmp[60], -1.0/2.0);
	tmp[68] = tmp[64]*tmp[65];
	tmp[69] = tmp[62]*tmp[67];
	tmp[70] = tmp[59]*tmp[67] - tmp[68]*tmp[69];
	tmp[71] = tmp[67]*(-REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[47] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[49] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[48] - X[0]*tmp[50] - X[1]*tmp[52] - X[2]*tmp[53] + Z[1]);
	tmp[72] = powf(tmp[34], -1.0/2.0);
	tmp[73] = tmp[45]*tmp[72];
	tmp[74] = tmp[67]*tmp[70];
	tmp[75] = tmp[57]*tmp[72];
	tmp[76] = tmp[31]*tmp[72] - tmp[68]*tmp[73] - tmp[74]*tmp[75];
	tmp[77] = tmp[72]*(-REMOTE_SENSING_FALCON_BODY_OFFSET_X*tmp[2] - REMOTE_SENSING_FALCON_BODY_OFFSET_Y*tmp[15] - REMOTE_SENSING_FALCON_BODY_OFFSET_Z*tmp[13] - X[0]*tmp[18] - X[1]*tmp[27] - X[2]*tmp[30] + Z[0]);
	tmp[78] = -tmp[32]*tmp[58] + tmp[55];
	tmp[79] = -tmp[32]*tmp[46] + tmp[43] - tmp[63]*tmp[78];
	tmp[80] = tmp[65]*tmp[79];
	tmp[81] = tmp[67]*tmp[78] - tmp[69]*tmp[80];
	tmp[82] = tmp[67]*tmp[81];
	tmp[83] = tmp[32]*tmp[72] - tmp[73]*tmp[80] - tmp[75]*tmp[82];
	tmp[84] = -tmp[33]*tmp[58] + tmp[56];
	tmp[85] = -tmp[33]*tmp[46] + tmp[44] - tmp[63]*tmp[84];
	tmp[86] = tmp[65]*tmp[85];
	tmp[87] = tmp[67]*tmp[84] - tmp[69]*tmp[86];
	tmp[88] = tmp[67]*tmp[87];
	tmp[89] = tmp[33]*tmp[72] - tmp[73]*tmp[86] - tmp[75]*tmp[88];
	tmp[90] = P[6]*tmp[18] + P[7]*tmp[27] + P[8]*tmp[30];
	tmp[91] = P[6]*tmp[50] + P[7]*tmp[52] + P[8]*tmp[53] - tmp[58]*tmp[90];
	tmp[92] = P[6]*tmp[37] + P[7]*tmp[40] + P[8]*tmp[41] - tmp[46]*tmp[90] - tmp[63]*tmp[91];
	tmp[93] = tmp[65]*tmp[92];
	tmp[94] = tmp[67]*tmp[91] - tmp[69]*tmp[93];
	tmp[95] = tmp[67]*tmp[94];
	tmp[96] = tmp[72]*tmp[90] - tmp[73]*tmp[93] - tmp[75]*tmp[95];
	tmp[97] = P[10]*tmp[18] + P[11]*tmp[27] + P[12]*tmp[30];
	tmp[98] = P[10]*tmp[50] + P[11]*tmp[52] + P[12]*tmp[53] - tmp[58]*tmp[97];
	tmp[99] = P[10]*tmp[37] + P[11]*tmp[40] + P[12]*tmp[41] - tmp[46]*tmp[97] - tmp[63]*tmp[98];
	tmp[100] = tmp[65]*tmp[99];
	tmp[101] = -tmp[100]*tmp[69] + tmp[67]*tmp[98];
	tmp[102] = tmp[101]*tmp[67];
	tmp[103] = -tmp[100]*tmp[73] - tmp[102]*tmp[75] + tmp[72]*tmp[97];
	tmp[104] = P[15]*tmp[18] + P[16]*tmp[27] + P[17]*tmp[30];
	tmp[105] = P[15]*tmp[50] + P[16]*tmp[52] + P[17]*tmp[53] - tmp[104]*tmp[58];
	tmp[106] = P[15]*tmp[37] + P[16]*tmp[40] + P[17]*tmp[41] - tmp[104]*tmp[46] - tmp[105]*tmp[63];
	tmp[107] = tmp[106]*tmp[65];
	tmp[108] = tmp[105]*tmp[67] - tmp[107]*tmp[69];
	tmp[109] = tmp[108]*tmp[67];
	tmp[110] = tmp[104]*tmp[72] - tmp[107]*tmp[73] - tmp[109]*tmp[75];
	tmp[111] = P[21]*tmp[18] + P[22]*tmp[27] + P[23]*tmp[30];
	tmp[112] = P[21]*tmp[50] + P[22]*tmp[52] + P[23]*tmp[53] - tmp[111]*tmp[58];
	tmp[113] = P[21]*tmp[37] + P[22]*tmp[40] + P[23]*tmp[41] - tmp[111]*tmp[46] - tmp[112]*tmp[63];
	tmp[114] = tmp[113]*tmp[65];
	tmp[115] = tmp[112]*tmp[67] - tmp[114]*tmp[69];
	tmp[116] = tmp[115]*tmp[67];
	tmp[117] = tmp[111]*tmp[72] - tmp[114]*tmp[73] - tmp[116]*tmp[75];
	tmp[118] = P[28]*tmp[18] + P[29]*tmp[27] + P[30]*tmp[30];
	tmp[119] = P[28]*tmp[50] + P[29]*tmp[52] + P[30]*tmp[53] - tmp[118]*tmp[58];
	tmp[120] = P[28]*tmp[37] + P[29]*tmp[40] + P[30]*tmp[41] - tmp[118]*tmp[46] - tmp[119]*tmp[63];
	tmp[121] = tmp[120]*tmp[65];
	tmp[122] = tmp[119]*tmp[67] - tmp[121]*tmp[69];
	tmp[123] = tmp[122]*tmp[67];
	tmp[124] = tmp[118]*tmp[72] - tmp[121]*tmp[73] - tmp[123]*tmp[75];
	tmp[125] = P[36]*tmp[18] + P[37]*tmp[27] + P[38]*tmp[30];
	tmp[126] = P[36]*tmp[50] + P[37]*tmp[52] + P[38]*tmp[53] - tmp[125]*tmp[58];
	tmp[127] = P[36]*tmp[37] + P[37]*tmp[40] + P[38]*tmp[41] - tmp[125]*tmp[46] - tmp[126]*tmp[63];
	tmp[128] = tmp[127]*tmp[65];
	tmp[129] = tmp[126]*tmp[67] - tmp[128]*tmp[69];
	tmp[130] = tmp[129]*tmp[67];
	tmp[131] = tmp[125]*tmp[72] - tmp[128]*tmp[73] - tmp[130]*tmp[75];
	tmp[132] = tmp[72]*tmp[76];
	tmp[133] = tmp[72]*tmp[83];
	tmp[134] = -tmp[133]*tmp[18] - tmp[37]*tmp[80] - tmp[50]*tmp[82];
	tmp[135] = -tmp[133]*tmp[30] - tmp[41]*tmp[80] - tmp[53]*tmp[82];
	tmp[136] = -tmp[133]*tmp[27] - tmp[40]*tmp[80] - tmp[52]*tmp[82] + 1;
	tmp[137] = tmp[72]*tmp[89];
	tmp[138] = -tmp[137]*tmp[18] - tmp[37]*tmp[86] - tmp[50]*tmp[88];
	tmp[139] = -tmp[137]*tmp[27] - tmp[40]*tmp[86] - tmp[52]*tmp[88];
	tmp[140] = -tmp[137]*tmp[30] - tmp[41]*tmp[86] - tmp[53]*tmp[88] + 1;
	tmp[141] = tmp[72]*tmp[96];
	tmp[142] = -tmp[141]*tmp[18] - tmp[37]*tmp[93] - tmp[50]*tmp[95];
	tmp[143] = -tmp[141]*tmp[27] - tmp[40]*tmp[93] - tmp[52]*tmp[95];
	tmp[144] = -tmp[141]*tmp[30] - tmp[41]*tmp[93] - tmp[53]*tmp[95];
	tmp[145] = tmp[103]*tmp[72];
	tmp[146] = -tmp[100]*tmp[37] - tmp[102]*tmp[50] - tmp[145]*tmp[18];
	tmp[147] = -tmp[100]*tmp[40] - tmp[102]*tmp[52] - tmp[145]*tmp[27];
	tmp[148] = -tmp[100]*tmp[41] - tmp[102]*tmp[53] - tmp[145]*tmp[30];
	tmp[149] = tmp[110]*tmp[72];
	tmp[150] = -tmp[107]*tmp[37] - tmp[109]*tmp[50] - tmp[149]*tmp[18];
	tmp[151] = -tmp[107]*tmp[40] - tmp[109]*tmp[52] - tmp[149]*tmp[27];
	tmp[152] = -tmp[107]*tmp[41] - tmp[109]*tmp[53] - tmp[149]*tmp[30];
	tmp[153] = tmp[117]*tmp[72];
	tmp[154] = -tmp[114]*tmp[37] - tmp[116]*tmp[50] - tmp[153]*tmp[18];
	tmp[155] = -tmp[114]*tmp[40] - tmp[116]*tmp[52] - tmp[153]*tmp[27];
	tmp[156] = -tmp[114]*tmp[41] - tmp[116]*tmp[53] - tmp[153]*tmp[30];
	tmp[157] = tmp[124]*tmp[72];
	tmp[158] = -tmp[121]*tmp[37] - tmp[123]*tmp[50] - tmp[157]*tmp[18];
	tmp[159] = -tmp[121]*tmp[40] - tmp[123]*tmp[52] - tmp[157]*tmp[27];
	tmp[160] = -tmp[121]*tmp[41] - tmp[123]*tmp[53] - tmp[157]*tmp[30];
	tmp[161] = tmp[131]*tmp[72];
	tmp[162] = -tmp[128]*tmp[37] - tmp[130]*tmp[50] - tmp[161]*tmp[18];
	tmp[163] = -tmp[128]*tmp[40] - tmp[130]*tmp[52] - tmp[161]*tmp[27];
	tmp[164] = -tmp[128]*tmp[41] - tmp[130]*tmp[53] - tmp[161]*tmp[30];
	X_new[0] = X[0] + tmp[64]*tmp[66] + tmp[70]*tmp[71] + tmp[76]*tmp[77];
	X_new[1] = X[1] + tmp[66]*tmp[79] + tmp[71]*tmp[81] + tmp[77]*tmp[83];
	X_new[2] = X[2] + tmp[66]*tmp[85] + tmp[71]*tmp[87] + tmp[77]*tmp[89];
	X_new[3] = X[3] + tmp[66]*tmp[92] + tmp[71]*tmp[94] + tmp[77]*tmp[96];
	X_new[4] = X[4] + tmp[101]*tmp[71] + tmp[103]*tmp[77] + tmp[66]*tmp[99];
	X_new[5] = X[5] + tmp[106]*tmp[66] + tmp[108]*tmp[71] + tmp[110]*tmp[77];
	X_new[6] = gps_offset_x + tmp[113]*tmp[66] + tmp[115]*tmp[71] + tmp[117]*tmp[77];
	X_new[7] = gps_offset_y + tmp[120]*tmp[66] + tmp[122]*tmp[71] + tmp[124]*tmp[77];
	X_new[8] = gps_offset_z + tmp[127]*tmp[66] + tmp[129]*tmp[71] + tmp[131]*tmp[77];
	P_new[0] = P[0]*(-tmp[132]*tmp[18] - tmp[37]*tmp[68] - tmp[50]*tmp[74] + 1) + P[1]*(-tmp[132]*tmp[27] - tmp[40]*tmp[68] - tmp[52]*tmp[74]) + P[3]*(-tmp[132]*tmp[30] - tmp[41]*tmp[68] - tmp[53]*tmp[74]);
	P_new[1] = P[0]*tmp[134] + P[1]*tmp[136] + P[3]*tmp[135];
	P_new[2] = P[1]*tmp[134] + P[2]*tmp[136] + P[4]*tmp[135];
	P_new[3] = P[0]*tmp[138] + P[1]*tmp[139] + P[3]*tmp[140];
	P_new[4] = P[1]*tmp[138] + P[2]*tmp[139] + P[4]*tmp[140];
	P_new[5] = P[3]*tmp[138] + P[4]*tmp[139] + P[5]*tmp[140];
	P_new[6] = P[0]*tmp[142] + P[1]*tmp[143] + P[3]*tmp[144] + P[6];
	P_new[7] = P[1]*tmp[142] + P[2]*tmp[143] + P[4]*tmp[144] + P[7];
	P_new[8] = P[3]*tmp[142] + P[4]*tmp[143] + P[5]*tmp[144] + P[8];
	P_new[9] = P[6]*tmp[142] + P[7]*tmp[143] + P[8]*tmp[144] + P[9];
	P_new[10] = P[0]*tmp[146] + P[10] + P[1]*tmp[147] + P[3]*tmp[148];
	P_new[11] = P[11] + P[1]*tmp[146] + P[2]*tmp[147] + P[4]*tmp[148];
	P_new[12] = P[12] + P[3]*tmp[146] + P[4]*tmp[147] + P[5]*tmp[148];
	P_new[13] = P[13] + P[6]*tmp[146] + P[7]*tmp[147] + P[8]*tmp[148];
	P_new[14] = P[10]*tmp[146] + P[11]*tmp[147] + P[12]*tmp[148] + P[14];
	P_new[15] = P[0]*tmp[150] + P[15] + P[1]*tmp[151] + P[3]*tmp[152];
	P_new[16] = P[16] + P[1]*tmp[150] + P[2]*tmp[151] + P[4]*tmp[152];
	P_new[17] = P[17] + P[3]*tmp[150] + P[4]*tmp[151] + P[5]*tmp[152];
	P_new[18] = P[18] + P[6]*tmp[150] + P[7]*tmp[151] + P[8]*tmp[152];
	P_new[19] = P[10]*tmp[150] + P[11]*tmp[151] + P[12]*tmp[152] + P[19];
	P_new[20] = P[15]*tmp[150] + P[16]*tmp[151] + P[17]*tmp[152] + P[20];
	P_new[21] = P[0]*tmp[154] + P[1]*tmp[155] + P[21] + P[3]*tmp[156];
	P_new[22] = P[1]*tmp[154] + P[22] + P[2]*tmp[155] + P[4]*tmp[156];
	P_new[23] = P[23] + P[3]*tmp[154] + P[4]*tmp[155] + P[5]*tmp[156];
	P_new[24] = P[24] + P[6]*tmp[154] + P[7]*tmp[155] + P[8]*tmp[156];
	P_new[25] = P[10]*tmp[154] + P[11]*tmp[155] + P[12]*tmp[156] + P[25];
	P_new[26] = P[15]*tmp[154] + P[16]*tmp[155] + P[17]*tmp[156] + P[26];
	P_new[27] = P[21]*tmp[154] + P[22]*tmp[155] + P[23]*tmp[156] + P[27];
	P_new[28] = P[0]*tmp[158] + P[1]*tmp[159] + P[28] + P[3]*tmp[160];
	P_new[29] = P[1]*tmp[158] + P[29] + P[2]*tmp[159] + P[4]*tmp[160];
	P_new[30] = P[30] + P[3]*tmp[158] + P[4]*tmp[159] + P[5]*tmp[160];
	P_new[31] = P[31] + P[6]*tmp[158] + P[7]*tmp[159] + P[8]*tmp[160];
	P_new[32] = P[10]*tmp[158] + P[11]*tmp[159] + P[12]*tmp[160] + P[32];
	P_new[33] = P[15]*tmp[158] + P[16]*tmp[159] + P[17]*tmp[160] + P[33];
	P_new[34] = P[21]*tmp[158] + P[22]*tmp[159] + P[23]*tmp[160] + P[34];
	P_new[35] = P[28]*tmp[158] + P[29]*tmp[159] + P[30]*tmp[160] + P[35];
	P_new[36] = P[0]*tmp[162] + P[1]*tmp[163] + P[36] + P[3]*tmp[164];
	P_new[37] = P[1]*tmp[162] + P[2]*tmp[163] + P[37] + P[4]*tmp[164];
	P_new[38] = P[38] + P[3]*tmp[162] + P[4]*tmp[163] + P[5]*tmp[164];
	P_new[39] = P[39] + P[6]*tmp[162] + P[7]*tmp[163] + P[8]*tmp[164];
	P_new[40] = P[10]*tmp[162] + P[11]*tmp[163] + P[12]*tmp[164] + P[40];
	P_new[41] = P[15]*tmp[162] + P[16]*tmp[163] + P[17]*tmp[164] + P[41];
	P_new[42] = P[21]*tmp[162] + P[22]*tmp[163] + P[23]*tmp[164] + P[42];
	P_new[43] = P[28]*tmp[162] + P[29]*tmp[163] + P[30]*tmp[164] + P[43];
	P_new[44] = P[36]*tmp[162] + P[37]*tmp[163] + P[38]*tmp[164] + P[44];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_update_gps(struct FloatVect3 rtk_pos, struct FloatVect3 rtk_speed) {
    
    // Prepare measurement vector from measurements
	float Z[N_MEASUREMENTS_GPS];
	float *HX = ekf_last_HX_gps;
    Z[0] = rtk_pos.x;
    Z[1] = rtk_pos.y;
    Z[2] = rtk_pos.z;
    Z[3] = rtk_speed.x;
    Z[4] = rtk_speed.y;
    Z[5] = rtk_speed.z;

    // Set R pointer to GPS measurement noise
    R = ekf_R_gps;
    // UPDATE STEP X_new, P_new = ...
    tmp[0] = P[0] + P[21];
	tmp[1] = P[0] + 2*P[21] + P[27] + R[0];
	tmp[2] = 1.0/tmp[1];
	tmp[3] = P[15] + P[26];
	tmp[4] = tmp[2]*tmp[3];
	tmp[5] = P[1] + P[22];
	tmp[6] = P[28] + P[34];
	tmp[7] = tmp[5] + tmp[6];
	tmp[8] = tmp[2]*tmp[7];
	tmp[9] = P[1] + P[28] - tmp[0]*tmp[8];
	tmp[10] = 2*P[29] + P[2] + P[35] + R[1] - tmp[2]*powf(tmp[7], 2);
	tmp[11] = 1.0/tmp[10];
	tmp[12] = P[16] + P[33] - tmp[3]*tmp[8];
	tmp[13] = tmp[11]*tmp[12];
	tmp[14] = P[23] + P[3];
	tmp[15] = P[36] + P[42];
	tmp[16] = tmp[14] + tmp[15];
	tmp[17] = tmp[16]*tmp[2];
	tmp[18] = P[30] + P[4];
	tmp[19] = P[37] + P[43];
	tmp[20] = -tmp[16]*tmp[8] + tmp[18] + tmp[19];
	tmp[21] = tmp[11]*tmp[20];
	tmp[22] = P[36] + P[3] - tmp[0]*tmp[17] - tmp[21]*tmp[9];
	tmp[23] = 2*P[38] + P[44] + P[5] + R[2] - tmp[11]*powf(tmp[20], 2) - powf(tmp[16], 2)*tmp[2];
	tmp[24] = 1.0/tmp[23];
	tmp[25] = P[17] + P[41] - tmp[12]*tmp[21] - tmp[17]*tmp[3];
	tmp[26] = tmp[24]*tmp[25];
	tmp[27] = P[24] + P[6];
	tmp[28] = tmp[27]*tmp[2];
	tmp[29] = P[31] + P[7] - tmp[27]*tmp[8];
	tmp[30] = tmp[11]*tmp[29];
	tmp[31] = P[39] + P[8] - tmp[16]*tmp[28] - tmp[20]*tmp[30];
	tmp[32] = tmp[24]*tmp[31];
	tmp[33] = P[6] - tmp[0]*tmp[28] - tmp[22]*tmp[32] - tmp[30]*tmp[9];
	tmp[34] = -P[9] + tmp[11]*powf(tmp[29], 2) + tmp[24]*powf(tmp[31], 2) + powf(tmp[27], 2)*tmp[2];
	tmp[35] = R[3] - tmp[34];
	tmp[36] = 1.0/tmp[35];
	tmp[37] = -P[18] + tmp[12]*tmp[30] + tmp[25]*tmp[32] + tmp[28]*tmp[3];
	tmp[38] = -tmp[37];
	tmp[39] = tmp[36]*tmp[38];
	tmp[40] = P[10] + P[25];
	tmp[41] = tmp[2]*tmp[40];
	tmp[42] = P[11] + P[32] - tmp[40]*tmp[8];
	tmp[43] = tmp[11]*tmp[42];
	tmp[44] = P[12] + P[40] - tmp[17]*tmp[40] - tmp[21]*tmp[42];
	tmp[45] = tmp[24]*tmp[44];
	tmp[46] = -P[13] + tmp[28]*tmp[40] + tmp[30]*tmp[42] + tmp[32]*tmp[44];
	tmp[47] = -tmp[46];
	tmp[48] = tmp[36]*tmp[47];
	tmp[49] = P[10] - tmp[0]*tmp[41] - tmp[22]*tmp[45] - tmp[33]*tmp[48] - tmp[43]*tmp[9];
	tmp[50] = -P[14] + tmp[11]*powf(tmp[42], 2) + tmp[24]*powf(tmp[44], 2) + tmp[2]*powf(tmp[40], 2) + tmp[36]*powf(tmp[47], 2);
	tmp[51] = R[4] - tmp[50];
	tmp[52] = 1.0/tmp[51];
	tmp[53] = -P[19] + tmp[12]*tmp[43] + tmp[25]*tmp[45] + tmp[38]*tmp[48] + tmp[3]*tmp[41];
	tmp[54] = -tmp[53];
	tmp[55] = tmp[52]*tmp[54];
	tmp[56] = P[15] - tmp[0]*tmp[4] - tmp[13]*tmp[9] - tmp[22]*tmp[26] - tmp[33]*tmp[39] - tmp[49]*tmp[55];
	tmp[57] = -P[20] + tmp[11]*powf(tmp[12], 2) + tmp[24]*powf(tmp[25], 2) + tmp[2]*powf(tmp[3], 2) + tmp[36]*powf(tmp[38], 2) + tmp[52]*powf(tmp[54], 2);
	tmp[58] = 1.0/(R[5] - tmp[57]);
	tmp[59] = -X[5] + Z[5];
	tmp[60] = tmp[58]*tmp[59];
	tmp[61] = powf(tmp[51], -1.0/2.0);
	tmp[62] = tmp[54]*tmp[61];
	tmp[63] = tmp[56]*tmp[58];
	tmp[64] = tmp[49]*tmp[61] - tmp[62]*tmp[63];
	tmp[65] = -X[4] + Z[4];
	tmp[66] = tmp[61]*tmp[65];
	tmp[67] = powf(tmp[35], -1.0/2.0);
	tmp[68] = tmp[38]*tmp[67];
	tmp[69] = tmp[47]*tmp[67];
	tmp[70] = tmp[61]*tmp[64];
	tmp[71] = tmp[33]*tmp[67] - tmp[63]*tmp[68] - tmp[69]*tmp[70];
	tmp[72] = -X[3] + Z[3];
	tmp[73] = tmp[67]*tmp[72];
	tmp[74] = powf(tmp[23], -1.0/2.0);
	tmp[75] = tmp[25]*tmp[74];
	tmp[76] = tmp[44]*tmp[74];
	tmp[77] = tmp[31]*tmp[74];
	tmp[78] = tmp[67]*tmp[71];
	tmp[79] = tmp[22]*tmp[74] - tmp[63]*tmp[75] - tmp[70]*tmp[76] - tmp[77]*tmp[78];
	tmp[80] = -X[2] - X[8] + Z[2];
	tmp[81] = tmp[74]*tmp[80];
	tmp[82] = powf(tmp[10], -1.0/2.0);
	tmp[83] = tmp[12]*tmp[82];
	tmp[84] = tmp[42]*tmp[82];
	tmp[85] = tmp[29]*tmp[82];
	tmp[86] = tmp[74]*tmp[79];
	tmp[87] = tmp[20]*tmp[82];
	tmp[88] = -tmp[63]*tmp[83] - tmp[70]*tmp[84] - tmp[78]*tmp[85] + tmp[82]*tmp[9] - tmp[86]*tmp[87];
	tmp[89] = -X[1] - X[7] + Z[1];
	tmp[90] = tmp[82]*tmp[89];
	tmp[91] = -X[0] - X[6] + Z[0];
	tmp[92] = powf(tmp[1], -1.0/2.0);
	tmp[93] = tmp[3]*tmp[92];
	tmp[94] = tmp[40]*tmp[92];
	tmp[95] = tmp[27]*tmp[92];
	tmp[96] = tmp[16]*tmp[92];
	tmp[97] = tmp[82]*tmp[88];
	tmp[98] = tmp[7]*tmp[92];
	tmp[99] = tmp[92]*(tmp[0]*tmp[92] - tmp[63]*tmp[93] - tmp[70]*tmp[94] - tmp[78]*tmp[95] - tmp[86]*tmp[96] - tmp[97]*tmp[98]);
	tmp[100] = P[29] + P[2] - tmp[5]*tmp[8];
	tmp[101] = P[37] + P[4] - tmp[100]*tmp[21] - tmp[17]*tmp[5];
	tmp[102] = P[7] - tmp[100]*tmp[30] - tmp[101]*tmp[32] - tmp[28]*tmp[5];
	tmp[103] = P[11] - tmp[100]*tmp[43] - tmp[101]*tmp[45] - tmp[102]*tmp[48] - tmp[41]*tmp[5];
	tmp[104] = P[16] - tmp[100]*tmp[13] - tmp[101]*tmp[26] - tmp[102]*tmp[39] - tmp[103]*tmp[55] - tmp[4]*tmp[5];
	tmp[105] = tmp[104]*tmp[58];
	tmp[106] = tmp[103]*tmp[61] - tmp[105]*tmp[62];
	tmp[107] = tmp[106]*tmp[61];
	tmp[108] = tmp[102]*tmp[67] - tmp[105]*tmp[68] - tmp[107]*tmp[69];
	tmp[109] = tmp[108]*tmp[67];
	tmp[110] = tmp[101]*tmp[74] - tmp[105]*tmp[75] - tmp[107]*tmp[76] - tmp[109]*tmp[77];
	tmp[111] = tmp[110]*tmp[74];
	tmp[112] = tmp[82]*(tmp[100]*tmp[82] - tmp[105]*tmp[83] - tmp[107]*tmp[84] - tmp[109]*tmp[85] - tmp[111]*tmp[87]);
	tmp[113] = -tmp[105]*tmp[93] - tmp[107]*tmp[94] - tmp[109]*tmp[95] - tmp[111]*tmp[96] - tmp[112]*tmp[98] + tmp[5]*tmp[92];
	tmp[114] = tmp[91]*tmp[92];
	tmp[115] = -tmp[14]*tmp[8] + tmp[18];
	tmp[116] = P[38] + P[5] - tmp[115]*tmp[21] - tmp[14]*tmp[17];
	tmp[117] = P[8] - tmp[115]*tmp[30] - tmp[116]*tmp[32] - tmp[14]*tmp[28];
	tmp[118] = P[12] - tmp[115]*tmp[43] - tmp[116]*tmp[45] - tmp[117]*tmp[48] - tmp[14]*tmp[41];
	tmp[119] = P[17] - tmp[115]*tmp[13] - tmp[116]*tmp[26] - tmp[117]*tmp[39] - tmp[118]*tmp[55] - tmp[14]*tmp[4];
	tmp[120] = tmp[119]*tmp[58];
	tmp[121] = tmp[118]*tmp[61] - tmp[120]*tmp[62];
	tmp[122] = tmp[121]*tmp[61];
	tmp[123] = tmp[117]*tmp[67] - tmp[120]*tmp[68] - tmp[122]*tmp[69];
	tmp[124] = tmp[123]*tmp[67];
	tmp[125] = tmp[74]*(tmp[116]*tmp[74] - tmp[120]*tmp[75] - tmp[122]*tmp[76] - tmp[124]*tmp[77]);
	tmp[126] = tmp[115]*tmp[82] - tmp[120]*tmp[83] - tmp[122]*tmp[84] - tmp[124]*tmp[85] - tmp[125]*tmp[87];
	tmp[127] = tmp[126]*tmp[82];
	tmp[128] = -tmp[120]*tmp[93] - tmp[122]*tmp[94] - tmp[124]*tmp[95] - tmp[125]*tmp[96] - tmp[127]*tmp[98] + tmp[14]*tmp[92];
	tmp[129] = -tmp[34];
	tmp[130] = -tmp[129]*tmp[48] - tmp[46];
	tmp[131] = -tmp[129]*tmp[39] - tmp[130]*tmp[55] - tmp[37];
	tmp[132] = tmp[131]*tmp[58];
	tmp[133] = tmp[130]*tmp[61] - tmp[132]*tmp[62];
	tmp[134] = tmp[133]*tmp[61];
	tmp[135] = tmp[67]*(tmp[129]*tmp[67] - tmp[132]*tmp[68] - tmp[134]*tmp[69]);
	tmp[136] = -tmp[132]*tmp[75] - tmp[134]*tmp[76] - tmp[135]*tmp[77] + tmp[31]*tmp[74];
	tmp[137] = tmp[136]*tmp[74];
	tmp[138] = -tmp[132]*tmp[83] - tmp[134]*tmp[84] - tmp[135]*tmp[85] - tmp[137]*tmp[87] + tmp[29]*tmp[82];
	tmp[139] = tmp[138]*tmp[82];
	tmp[140] = -tmp[132]*tmp[93] - tmp[134]*tmp[94] - tmp[135]*tmp[95] - tmp[137]*tmp[96] - tmp[139]*tmp[98] + tmp[27]*tmp[92];
	tmp[141] = -tmp[50];
	tmp[142] = -tmp[141]*tmp[55] - tmp[53];
	tmp[143] = tmp[142]*tmp[58];
	tmp[144] = tmp[61]*(tmp[141]*tmp[61] - tmp[143]*tmp[62]);
	tmp[145] = -tmp[143]*tmp[68] - tmp[144]*tmp[69] + tmp[47]*tmp[67];
	tmp[146] = tmp[145]*tmp[67];
	tmp[147] = -tmp[143]*tmp[75] - tmp[144]*tmp[76] - tmp[146]*tmp[77] + tmp[44]*tmp[74];
	tmp[148] = tmp[147]*tmp[74];
	tmp[149] = -tmp[143]*tmp[83] - tmp[144]*tmp[84] - tmp[146]*tmp[85] - tmp[148]*tmp[87] + tmp[42]*tmp[82];
	tmp[150] = tmp[149]*tmp[82];
	tmp[151] = -tmp[143]*tmp[93] - tmp[144]*tmp[94] - tmp[146]*tmp[95] - tmp[148]*tmp[96] - tmp[150]*tmp[98] + tmp[40]*tmp[92];
	tmp[152] = -tmp[57]*tmp[58];
	tmp[153] = -tmp[152]*tmp[62] + tmp[54]*tmp[61];
	tmp[154] = tmp[153]*tmp[61];
	tmp[155] = -tmp[152]*tmp[68] - tmp[154]*tmp[69] + tmp[38]*tmp[67];
	tmp[156] = tmp[155]*tmp[67];
	tmp[157] = -tmp[152]*tmp[75] - tmp[154]*tmp[76] - tmp[156]*tmp[77] + tmp[25]*tmp[74];
	tmp[158] = tmp[157]*tmp[74];
	tmp[159] = tmp[12]*tmp[82] - tmp[152]*tmp[83] - tmp[154]*tmp[84] - tmp[156]*tmp[85] - tmp[158]*tmp[87];
	tmp[160] = tmp[159]*tmp[82];
	tmp[161] = -tmp[152]*tmp[93] - tmp[154]*tmp[94] - tmp[156]*tmp[95] - tmp[158]*tmp[96] - tmp[160]*tmp[98] + tmp[3]*tmp[92];
	tmp[162] = P[21] + P[27];
	tmp[163] = P[22] + P[34] - tmp[162]*tmp[8];
	tmp[164] = P[23] + P[42] - tmp[162]*tmp[17] - tmp[163]*tmp[21];
	tmp[165] = P[24] - tmp[162]*tmp[28] - tmp[163]*tmp[30] - tmp[164]*tmp[32];
	tmp[166] = P[25] - tmp[162]*tmp[41] - tmp[163]*tmp[43] - tmp[164]*tmp[45] - tmp[165]*tmp[48];
	tmp[167] = P[26] - tmp[13]*tmp[163] - tmp[162]*tmp[4] - tmp[164]*tmp[26] - tmp[165]*tmp[39] - tmp[166]*tmp[55];
	tmp[168] = tmp[167]*tmp[58];
	tmp[169] = tmp[166]*tmp[61] - tmp[168]*tmp[62];
	tmp[170] = tmp[169]*tmp[61];
	tmp[171] = tmp[165]*tmp[67] - tmp[168]*tmp[68] - tmp[170]*tmp[69];
	tmp[172] = tmp[171]*tmp[67];
	tmp[173] = tmp[164]*tmp[74] - tmp[168]*tmp[75] - tmp[170]*tmp[76] - tmp[172]*tmp[77];
	tmp[174] = tmp[173]*tmp[74];
	tmp[175] = tmp[163]*tmp[82] - tmp[168]*tmp[83] - tmp[170]*tmp[84] - tmp[172]*tmp[85] - tmp[174]*tmp[87];
	tmp[176] = tmp[175]*tmp[82];
	tmp[177] = tmp[92]*(tmp[162]*tmp[92] - tmp[168]*tmp[93] - tmp[170]*tmp[94] - tmp[172]*tmp[95] - tmp[174]*tmp[96] - tmp[176]*tmp[98]);
	tmp[178] = P[29] + P[35] - tmp[6]*tmp[8];
	tmp[179] = P[30] + P[43] - tmp[178]*tmp[21] - tmp[17]*tmp[6];
	tmp[180] = P[31] - tmp[178]*tmp[30] - tmp[179]*tmp[32] - tmp[28]*tmp[6];
	tmp[181] = P[32] - tmp[178]*tmp[43] - tmp[179]*tmp[45] - tmp[180]*tmp[48] - tmp[41]*tmp[6];
	tmp[182] = P[33] - tmp[13]*tmp[178] - tmp[179]*tmp[26] - tmp[180]*tmp[39] - tmp[181]*tmp[55] - tmp[4]*tmp[6];
	tmp[183] = tmp[182]*tmp[58];
	tmp[184] = tmp[181]*tmp[61] - tmp[183]*tmp[62];
	tmp[185] = tmp[184]*tmp[61];
	tmp[186] = tmp[180]*tmp[67] - tmp[183]*tmp[68] - tmp[185]*tmp[69];
	tmp[187] = tmp[186]*tmp[67];
	tmp[188] = tmp[179]*tmp[74] - tmp[183]*tmp[75] - tmp[185]*tmp[76] - tmp[187]*tmp[77];
	tmp[189] = tmp[188]*tmp[74];
	tmp[190] = tmp[82]*(tmp[178]*tmp[82] - tmp[183]*tmp[83] - tmp[185]*tmp[84] - tmp[187]*tmp[85] - tmp[189]*tmp[87]);
	tmp[191] = -tmp[183]*tmp[93] - tmp[185]*tmp[94] - tmp[187]*tmp[95] - tmp[189]*tmp[96] - tmp[190]*tmp[98] + tmp[6]*tmp[92];
	tmp[192] = -tmp[15]*tmp[8] + tmp[19];
	tmp[193] = P[38] + P[44] - tmp[15]*tmp[17] - tmp[192]*tmp[21];
	tmp[194] = P[39] - tmp[15]*tmp[28] - tmp[192]*tmp[30] - tmp[193]*tmp[32];
	tmp[195] = P[40] - tmp[15]*tmp[41] - tmp[192]*tmp[43] - tmp[193]*tmp[45] - tmp[194]*tmp[48];
	tmp[196] = P[41] - tmp[13]*tmp[192] - tmp[15]*tmp[4] - tmp[193]*tmp[26] - tmp[194]*tmp[39] - tmp[195]*tmp[55];
	tmp[197] = tmp[196]*tmp[58];
	tmp[198] = tmp[195]*tmp[61] - tmp[197]*tmp[62];
	tmp[199] = tmp[198]*tmp[61];
	tmp[200] = tmp[194]*tmp[67] - tmp[197]*tmp[68] - tmp[199]*tmp[69];
	tmp[201] = tmp[200]*tmp[67];
	tmp[202] = tmp[74]*(tmp[193]*tmp[74] - tmp[197]*tmp[75] - tmp[199]*tmp[76] - tmp[201]*tmp[77]);
	tmp[203] = tmp[192]*tmp[82] - tmp[197]*tmp[83] - tmp[199]*tmp[84] - tmp[201]*tmp[85] - tmp[202]*tmp[87];
	tmp[204] = tmp[203]*tmp[82];
	tmp[205] = tmp[15]*tmp[92] - tmp[197]*tmp[93] - tmp[199]*tmp[94] - tmp[201]*tmp[95] - tmp[202]*tmp[96] - tmp[204]*tmp[98];
	tmp[206] = P[15]*tmp[58];
	tmp[207] = P[10]*tmp[61];
	tmp[208] = P[6]*tmp[67];
	tmp[209] = 1 - tmp[112];
	tmp[210] = tmp[113]*tmp[92];
	tmp[211] = P[16]*tmp[58];
	tmp[212] = P[11]*tmp[61];
	tmp[213] = P[7]*tmp[67];
	tmp[214] = 1 - tmp[125];
	tmp[215] = tmp[128]*tmp[92];
	tmp[216] = P[17]*tmp[58];
	tmp[217] = P[12]*tmp[61];
	tmp[218] = P[8]*tmp[67];
	tmp[219] = 1 - tmp[135];
	tmp[220] = tmp[140]*tmp[92];
	tmp[221] = P[18]*tmp[58];
	tmp[222] = P[13]*tmp[61];
	tmp[223] = 1 - tmp[144];
	tmp[224] = tmp[151]*tmp[92];
	tmp[225] = P[19]*tmp[58];
	tmp[226] = 1 - tmp[152];
	tmp[227] = tmp[161]*tmp[92];
	tmp[228] = 1 - tmp[177];
	tmp[229] = 1 - tmp[190];
	tmp[230] = tmp[191]*tmp[92];
	tmp[231] = P[21]*tmp[230];
	tmp[232] = 1 - tmp[202];
	tmp[233] = tmp[205]*tmp[92];
	tmp[234] = P[21]*tmp[233];
	tmp[235] = P[29]*tmp[204];
	X_new[0] = X[0] + tmp[56]*tmp[60] + tmp[64]*tmp[66] + tmp[71]*tmp[73] + tmp[79]*tmp[81] + tmp[88]*tmp[90] + tmp[91]*tmp[99];
	X_new[1] = X[1] + tmp[104]*tmp[60] + tmp[106]*tmp[66] + tmp[108]*tmp[73] + tmp[110]*tmp[81] + tmp[112]*tmp[89] + tmp[113]*tmp[114];
	X_new[2] = X[2] + tmp[114]*tmp[128] + tmp[119]*tmp[60] + tmp[121]*tmp[66] + tmp[123]*tmp[73] + tmp[125]*tmp[80] + tmp[126]*tmp[90];
	X_new[3] = X[3] + tmp[114]*tmp[140] + tmp[131]*tmp[60] + tmp[133]*tmp[66] + tmp[135]*tmp[72] + tmp[136]*tmp[81] + tmp[138]*tmp[90];
	X_new[4] = X[4] + tmp[114]*tmp[151] + tmp[142]*tmp[60] + tmp[144]*tmp[65] + tmp[145]*tmp[73] + tmp[147]*tmp[81] + tmp[149]*tmp[90];
	X_new[5] = X[5] + tmp[114]*tmp[161] + tmp[152]*tmp[59] + tmp[153]*tmp[66] + tmp[155]*tmp[73] + tmp[157]*tmp[81] + tmp[159]*tmp[90];
	X_new[6] = X[6] + tmp[167]*tmp[60] + tmp[169]*tmp[66] + tmp[171]*tmp[73] + tmp[173]*tmp[81] + tmp[175]*tmp[90] + tmp[177]*tmp[91];
	X_new[7] = X[7] + tmp[114]*tmp[191] + tmp[182]*tmp[60] + tmp[184]*tmp[66] + tmp[186]*tmp[73] + tmp[188]*tmp[81] + tmp[190]*tmp[89];
	X_new[8] = X[8] + tmp[114]*tmp[205] + tmp[196]*tmp[60] + tmp[198]*tmp[66] + tmp[200]*tmp[73] + tmp[202]*tmp[80] + tmp[203]*tmp[90];
	P_new[0] = P[0]*(1 - tmp[99]) - P[1]*tmp[97] - P[21]*tmp[99] - P[28]*tmp[97] - P[36]*tmp[86] - P[3]*tmp[86] - tmp[206]*tmp[56] - tmp[207]*tmp[64] - tmp[208]*tmp[71];
	P_new[1] = -P[0]*tmp[210] + P[1]*tmp[209] - P[21]*tmp[210] - P[28]*tmp[112] - P[36]*tmp[111] - P[3]*tmp[111] - tmp[104]*tmp[206] - tmp[106]*tmp[207] - tmp[108]*tmp[208];
	P_new[2] = -P[1]*tmp[210] - P[22]*tmp[210] - P[29]*tmp[112] + P[2]*tmp[209] - P[37]*tmp[111] - P[4]*tmp[111] - tmp[104]*tmp[211] - tmp[106]*tmp[212] - tmp[108]*tmp[213];
	P_new[3] = -P[0]*tmp[215] - P[1]*tmp[127] - P[21]*tmp[215] - P[28]*tmp[127] - P[36]*tmp[125] + P[3]*tmp[214] - tmp[119]*tmp[206] - tmp[121]*tmp[207] - tmp[123]*tmp[208];
	P_new[4] = -P[1]*tmp[215] - P[22]*tmp[215] - P[29]*tmp[127] - P[2]*tmp[127] - P[37]*tmp[125] + P[4]*tmp[214] - tmp[119]*tmp[211] - tmp[121]*tmp[212] - tmp[123]*tmp[213];
	P_new[5] = -P[23]*tmp[215] - P[30]*tmp[127] - P[38]*tmp[125] - P[3]*tmp[215] - P[4]*tmp[127] + P[5]*tmp[214] - tmp[119]*tmp[216] - tmp[121]*tmp[217] - tmp[123]*tmp[218];
	P_new[6] = -P[0]*tmp[220] - P[1]*tmp[139] - P[21]*tmp[220] - P[28]*tmp[139] - P[36]*tmp[137] - P[3]*tmp[137] + P[6]*tmp[219] - tmp[131]*tmp[206] - tmp[133]*tmp[207];
	P_new[7] = -P[1]*tmp[220] - P[22]*tmp[220] - P[29]*tmp[139] - P[2]*tmp[139] - P[37]*tmp[137] - P[4]*tmp[137] + P[7]*tmp[219] - tmp[131]*tmp[211] - tmp[133]*tmp[212];
	P_new[8] = -P[23]*tmp[220] - P[30]*tmp[139] - P[38]*tmp[137] - P[3]*tmp[220] - P[4]*tmp[139] - P[5]*tmp[137] + P[8]*tmp[219] - tmp[131]*tmp[216] - tmp[133]*tmp[217];
	P_new[9] = -P[24]*tmp[220] - P[31]*tmp[139] - P[39]*tmp[137] - P[6]*tmp[220] - P[7]*tmp[139] - P[8]*tmp[137] + P[9]*tmp[219] - tmp[131]*tmp[221] - tmp[133]*tmp[222];
	P_new[10] = -P[0]*tmp[224] + P[10]*tmp[223] - P[1]*tmp[150] - P[21]*tmp[224] - P[28]*tmp[150] - P[36]*tmp[148] - P[3]*tmp[148] - tmp[142]*tmp[206] - tmp[145]*tmp[208];
	P_new[11] = P[11]*tmp[223] - P[1]*tmp[224] - P[22]*tmp[224] - P[29]*tmp[150] - P[2]*tmp[150] - P[37]*tmp[148] - P[4]*tmp[148] - tmp[142]*tmp[211] - tmp[145]*tmp[213];
	P_new[12] = P[12]*tmp[223] - P[23]*tmp[224] - P[30]*tmp[150] - P[38]*tmp[148] - P[3]*tmp[224] - P[4]*tmp[150] - P[5]*tmp[148] - tmp[142]*tmp[216] - tmp[145]*tmp[218];
	P_new[13] = P[13]*tmp[223] - P[24]*tmp[224] - P[31]*tmp[150] - P[39]*tmp[148] - P[6]*tmp[224] - P[7]*tmp[150] - P[8]*tmp[148] - P[9]*tmp[146] - tmp[142]*tmp[221];
	P_new[14] = -P[10]*tmp[224] - P[11]*tmp[150] - P[12]*tmp[148] - P[13]*tmp[146] + P[14]*tmp[223] - P[25]*tmp[224] - P[32]*tmp[150] - P[40]*tmp[148] - tmp[142]*tmp[225];
	P_new[15] = -P[0]*tmp[227] + P[15]*tmp[226] - P[1]*tmp[160] - P[21]*tmp[227] - P[28]*tmp[160] - P[36]*tmp[158] - P[3]*tmp[158] - tmp[153]*tmp[207] - tmp[155]*tmp[208];
	P_new[16] = P[16]*tmp[226] - P[1]*tmp[227] - P[22]*tmp[227] - P[29]*tmp[160] - P[2]*tmp[160] - P[37]*tmp[158] - P[4]*tmp[158] - tmp[153]*tmp[212] - tmp[155]*tmp[213];
	P_new[17] = P[17]*tmp[226] - P[23]*tmp[227] - P[30]*tmp[160] - P[38]*tmp[158] - P[3]*tmp[227] - P[4]*tmp[160] - P[5]*tmp[158] - tmp[153]*tmp[217] - tmp[155]*tmp[218];
	P_new[18] = P[18]*tmp[226] - P[24]*tmp[227] - P[31]*tmp[160] - P[39]*tmp[158] - P[6]*tmp[227] - P[7]*tmp[160] - P[8]*tmp[158] - P[9]*tmp[156] - tmp[153]*tmp[222];
	P_new[19] = -P[10]*tmp[227] - P[11]*tmp[160] - P[12]*tmp[158] - P[13]*tmp[156] - P[14]*tmp[154] + P[19]*tmp[226] - P[25]*tmp[227] - P[32]*tmp[160] - P[40]*tmp[158];
	P_new[20] = -P[15]*tmp[227] - P[16]*tmp[160] - P[17]*tmp[158] - P[18]*tmp[156] - P[19]*tmp[154] + P[20]*tmp[226] - P[26]*tmp[227] - P[33]*tmp[160] - P[41]*tmp[158];
	P_new[21] = -P[0]*tmp[177] - P[1]*tmp[176] + P[21]*tmp[228] - P[28]*tmp[176] - P[36]*tmp[174] - P[3]*tmp[174] - tmp[167]*tmp[206] - tmp[169]*tmp[207] - tmp[171]*tmp[208];
	P_new[22] = -P[1]*tmp[177] + P[22]*tmp[228] - P[29]*tmp[176] - P[2]*tmp[176] - P[37]*tmp[174] - P[4]*tmp[174] - tmp[167]*tmp[211] - tmp[169]*tmp[212] - tmp[171]*tmp[213];
	P_new[23] = P[23]*tmp[228] - P[30]*tmp[176] - P[38]*tmp[174] - P[3]*tmp[177] - P[4]*tmp[176] - P[5]*tmp[174] - tmp[167]*tmp[216] - tmp[169]*tmp[217] - tmp[171]*tmp[218];
	P_new[24] = P[24]*tmp[228] - P[31]*tmp[176] - P[39]*tmp[174] - P[6]*tmp[177] - P[7]*tmp[176] - P[8]*tmp[174] - P[9]*tmp[172] - tmp[167]*tmp[221] - tmp[169]*tmp[222];
	P_new[25] = -P[10]*tmp[177] - P[11]*tmp[176] - P[12]*tmp[174] - P[13]*tmp[172] - P[14]*tmp[170] + P[25]*tmp[228] - P[32]*tmp[176] - P[40]*tmp[174] - tmp[167]*tmp[225];
	P_new[26] = -P[15]*tmp[177] - P[16]*tmp[176] - P[17]*tmp[174] - P[18]*tmp[172] - P[19]*tmp[170] - P[20]*tmp[168] + P[26]*tmp[228] - P[33]*tmp[176] - P[41]*tmp[174];
	P_new[27] = -P[21]*tmp[177] - P[22]*tmp[176] - P[23]*tmp[174] - P[24]*tmp[172] - P[25]*tmp[170] - P[26]*tmp[168] + P[27]*tmp[228] - P[34]*tmp[176] - P[42]*tmp[174];
	P_new[28] = -P[0]*tmp[230] - P[1]*tmp[190] + P[28]*tmp[229] - P[36]*tmp[189] - P[3]*tmp[189] - tmp[182]*tmp[206] - tmp[184]*tmp[207] - tmp[186]*tmp[208] - tmp[231];
	P_new[29] = -P[1]*tmp[230] - P[22]*tmp[230] + P[29]*tmp[229] - P[2]*tmp[190] - P[37]*tmp[189] - P[4]*tmp[189] - tmp[182]*tmp[211] - tmp[184]*tmp[212] - tmp[186]*tmp[213];
	P_new[30] = -P[23]*tmp[230] + P[30]*tmp[229] - P[38]*tmp[189] - P[3]*tmp[230] - P[4]*tmp[190] - P[5]*tmp[189] - tmp[182]*tmp[216] - tmp[184]*tmp[217] - tmp[186]*tmp[218];
	P_new[31] = -P[24]*tmp[230] + P[31]*tmp[229] - P[39]*tmp[189] - P[6]*tmp[230] - P[7]*tmp[190] - P[8]*tmp[189] - P[9]*tmp[187] - tmp[182]*tmp[221] - tmp[184]*tmp[222];
	P_new[32] = -P[10]*tmp[230] - P[11]*tmp[190] - P[12]*tmp[189] - P[13]*tmp[187] - P[14]*tmp[185] - P[25]*tmp[230] + P[32]*tmp[229] - P[40]*tmp[189] - tmp[182]*tmp[225];
	P_new[33] = -P[15]*tmp[230] - P[16]*tmp[190] - P[17]*tmp[189] - P[18]*tmp[187] - P[19]*tmp[185] - P[20]*tmp[183] - P[26]*tmp[230] + P[33]*tmp[229] - P[41]*tmp[189];
	P_new[34] = -P[22]*tmp[190] - P[23]*tmp[189] - P[24]*tmp[187] - P[25]*tmp[185] - P[26]*tmp[183] - P[27]*tmp[230] + P[34]*tmp[229] - P[42]*tmp[189] - tmp[231];
	P_new[35] = -P[28]*tmp[230] - P[29]*tmp[190] - P[30]*tmp[189] - P[31]*tmp[187] - P[32]*tmp[185] - P[33]*tmp[183] - P[34]*tmp[230] + P[35]*tmp[229] - P[43]*tmp[189];
	P_new[36] = -P[0]*tmp[233] - P[1]*tmp[204] - P[28]*tmp[204] + P[36]*tmp[232] - P[3]*tmp[202] - tmp[196]*tmp[206] - tmp[198]*tmp[207] - tmp[200]*tmp[208] - tmp[234];
	P_new[37] = -P[1]*tmp[233] - P[22]*tmp[233] - P[2]*tmp[204] + P[37]*tmp[232] - P[4]*tmp[202] - tmp[196]*tmp[211] - tmp[198]*tmp[212] - tmp[200]*tmp[213] - tmp[235];
	P_new[38] = -P[23]*tmp[233] - P[30]*tmp[204] + P[38]*tmp[232] - P[3]*tmp[233] - P[4]*tmp[204] - P[5]*tmp[202] - tmp[196]*tmp[216] - tmp[198]*tmp[217] - tmp[200]*tmp[218];
	P_new[39] = -P[24]*tmp[233] - P[31]*tmp[204] + P[39]*tmp[232] - P[6]*tmp[233] - P[7]*tmp[204] - P[8]*tmp[202] - P[9]*tmp[201] - tmp[196]*tmp[221] - tmp[198]*tmp[222];
	P_new[40] = -P[10]*tmp[233] - P[11]*tmp[204] - P[12]*tmp[202] - P[13]*tmp[201] - P[14]*tmp[199] - P[25]*tmp[233] - P[32]*tmp[204] + P[40]*tmp[232] - tmp[196]*tmp[225];
	P_new[41] = -P[15]*tmp[233] - P[16]*tmp[204] - P[17]*tmp[202] - P[18]*tmp[201] - P[19]*tmp[199] - P[20]*tmp[197] - P[26]*tmp[233] - P[33]*tmp[204] + P[41]*tmp[232];
	P_new[42] = -P[22]*tmp[204] - P[23]*tmp[202] - P[24]*tmp[201] - P[25]*tmp[199] - P[26]*tmp[197] - P[27]*tmp[233] - P[34]*tmp[204] + P[42]*tmp[232] - tmp[234];
	P_new[43] = -P[28]*tmp[233] - P[30]*tmp[202] - P[31]*tmp[201] - P[32]*tmp[199] - P[33]*tmp[197] - P[34]*tmp[233] - P[35]*tmp[204] + P[43]*tmp[232] - tmp[235];
	P_new[44] = -P[36]*tmp[233] - P[37]*tmp[204] - P[38]*tmp[202] - P[39]*tmp[201] - P[40]*tmp[199] - P[41]*tmp[197] - P[42]*tmp[233] - P[43]*tmp[204] + P[44]*tmp[232];

    // swap X, X_new and P, P_new pointers
    swap_ptr = X;
    X = X_new;
    X_new = swap_ptr;

    swap_ptr = P;
    P = P_new;
    P_new = swap_ptr;
}

void ekf_clip_covariance() {
    // Clip diagonal covariance elements to prevent over-confidence or instability
    #ifdef REMOTE_SENSING_EKF_CLIP_P
    #if REMOTE_SENSING_EKF_CLIP_P
    for (int i = 0; i < N_STATES; i++) {
        // Diagonal element is at index i*(i+1)/2+i
        int idx = i * (i + 1) / 2 + i;
        if (P[idx] < REMOTE_SENSING_EKF_P_MIN) {
            P[idx] = REMOTE_SENSING_EKF_P_MIN;
        }
        if (P[idx] > REMOTE_SENSING_EKF_P_MAX) {
            P[idx] = REMOTE_SENSING_EKF_P_MAX;
        }
    }
    #endif
    #endif
}
